In [1]:
import geopandas as gpd
import numpy as np
import pandas as pd
import swifter
import time
import warnings

from src import meteorological_api
import src.utils as utils

In [2]:
warnings.filterwarnings('ignore')

In [3]:
response_var = pd.read_parquet('../data/interim/storm_outages_2014_2023.parquet')
counties = gpd.read_parquet('../data/external/county.parquet')

In [4]:
counties['fips_code_id'] = counties['STATEFP'] + counties['COUNTYFP'] 
outages_storms = response_var[response_var.storm_caused_outage==1]

In [5]:
random_seed = 42

In [6]:
def get_url_params_from_row_point(storm_outage_row, desired_point=None):
    lon = storm_outage_row[desired_point].x
    lat = storm_outage_row[desired_point].y
    start = storm_outage_row.one_day_before_storm
    end = storm_outage_row.one_day_after_storm
    identifier = storm_outage_row['episode_fips_id']
    save_path = f'../data/raw/meteorological/{identifier}.json'
    filexists = utils.check_if_filepath_exists(save_path)
    if not filexists:
        url = meteorological_api.get_api_url(lat=lat, lon=lon, datetime_start=start, datetime_end=end)
        return url
    return np.nan

def save_meteorological_info_from_row_point(storm_outage_row_iterated):
    idx, storm_outage_row = storm_outage_row_iterated
    identifier = storm_outage_row['episode_fips_id']
    meteorological_info = storm_outage_row['meteorological_info__cntroid']
    validate = meteorological_info.get('properties')
    save_path = f'../data/raw/meteorological/{identifier}.json'
    filexists = utils.check_if_filepath_exists(save_path)
    if (not filexists) and (validate is not None):
        meteorological_api.save_meteorological_information(information=meteorological_info, path=save_path)
        #print(f'Saving info at: {save_path}')
        return 1
    return np.nan

In [7]:
element_nb = 2200

In [318]:
condition = 100

In [320]:
while condition:
    # Transform data
    print('Starting')
    element_nb += 200
    sample_outages_storms = outages_storms.sample(element_nb, random_state=random_seed)
    meaning_dict = {'begin_datetime': 'storm_start', 'end_datetime': 'storm_end', 'run_start_time_min': 'outage_start', 'run_start_time_max': 'outage_end'}
    sample_outages_storms = sample_outages_storms.rename(
        columns=meaning_dict
    )
    sample_outages_storms['one_day_before_storm'] = (sample_outages_storms['storm_start'] - pd.Timedelta(1, unit='D')).dt.date
    sample_outages_storms['one_day_after_storm'] = (sample_outages_storms['storm_end'] + pd.Timedelta(1, unit='D')).dt.date
    sample_outages_storms = sample_outages_storms.merge(counties[['fips_code_id', 'geometry']], on='fips_code_id')
    sample_outages_storms = gpd.GeoDataFrame(sample_outages_storms)
    sample_outages_storms['cntroid'] = sample_outages_storms.geometry.centroid
    sample_outages_storms['url__cntroid'] = sample_outages_storms.apply(get_url_params_from_row_point, desired_point='cntroid', axis=1)
    sample_outages_storms = sample_outages_storms[sample_outages_storms['url__cntroid'].notna()]
        # Request meteorological data
    t0= time.perf_counter()
    sample_outages_storms['meteorological_info__cntroid'] = sample_outages_storms.url__cntroid.swifter.allow_dask_on_strings(
        enable=True
    ).apply(
        meteorological_api.get_meteorological_info
    )
    t1 = time.perf_counter()
    print(f'time it took {t1-t0}')
    # Save data
    for row in sample_outages_storms.iterrows():
        save_meteorological_info_from_row_point(row)
    print('Done with saving.')
    # Wait.
    time.sleep(30)
    condition = condition - 1
    # Repeat.

Starting

Dask Apply:   0%|          | 0/41 [00:00<?, ?it/s]

/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)

time it took 1603.9848179580003
Saving info at: ../data/raw/meteorological/103872_25017.json
Saving info at: ../data/raw/meteorological/141313_15003.json
Saving info at: ../data/raw/meteorological/168421_48085.json
Saving info at: ../data/raw/meteorological/121858_28035.json
Saving info at: ../data/raw/meteorological/149876_19153.json
Saving info at: ../data/raw/meteorological/150658_06013.json
Saving info at: ../data/raw/meteorological/155465_48085.json
Saving info at: ../data/raw/meteorological/155768_53061.json
Saving info at: ../data/raw/meteorological/103927_40099.json
Saving info at: ../data/raw/meteorological/99352_06065.json
Saving info at: ../data/raw/meteorological/125586_46099.json
Saving info at: ../data/raw/meteorological/182296_48067.json
Saving info at: ../data/raw/meteorological/168039_28011.json
Saving info at: ../data/raw/meteorological/167527_22051.json
Saving info at: ../data/raw/meteorological/155465_48363.json
Saving info at: ../data/raw/meteorological/110691_39035.json
Saving info at: ../data/raw/meteorological/118207_55023.json
Saving info at: ../data/raw/meteorological/141356_36059.json
Saving info at: ../data/raw/meteorological/154146_48439.json
Saving info at: ../data/raw/meteorological/178171_25015.json
Saving info at: ../data/raw/meteorological/107731_06037.json
Saving info at: ../data/raw/meteorological/106513_45051.json
Saving info at: ../data/raw/meteorological/144846_39077.json
Saving info at: ../data/raw/meteorological/173178_15003.json
Saving info at: ../data/raw/meteorological/108497_12021.json
Saving info at: ../data/raw/meteorological/93685_12081.json
Saving info at: ../data/raw/meteorological/174566_45015.json
Saving info at: ../data/raw/meteorological/153368_17195.json
Saving info at: ../data/raw/meteorological/162967_06059.json
Saving info at: ../data/raw/meteorological/123714_25021.json
Saving info at: ../data/raw/meteorological/134675_48455.json
Saving info at: ../data/raw/meteorological/149397_24003.json
Saving info at: ../data/raw/meteorological/165135_37183.json
Saving info at: ../data/raw/meteorological/169115_48439.json
Saving info at: ../data/raw/meteorological/143723_13207.json
Saving info at: ../data/raw/meteorological/181932_11001.json
Saving info at: ../data/raw/meteorological/155558_15003.json
Saving info at: ../data/raw/meteorological/126373_21047.json
Saving info at: ../data/raw/meteorological/115553_12009.json
Saving info at: ../data/raw/meteorological/165689_25001.json
Saving info at: ../data/raw/meteorological/134091_06053.json
Saving info at: ../data/raw/meteorological/178741_21029.json
Saving info at: ../data/raw/meteorological/124002_48423.json
Saving info at: ../data/raw/meteorological/150908_41019.json
Saving info at: ../data/raw/meteorological/166910_13051.json
Saving info at: ../data/raw/meteorological/127438_21111.json
Saving info at: ../data/raw/meteorological/158421_47037.json
Saving info at: ../data/raw/meteorological/140387_51107.json
Saving info at: ../data/raw/meteorological/179622_05051.json
Saving info at: ../data/raw/meteorological/148561_26099.json
Saving info at: ../data/raw/meteorological/131166_37057.json
Saving info at: ../data/raw/meteorological/138153_55135.json
Saving info at: ../data/raw/meteorological/173448_26139.json
Saving info at: ../data/raw/meteorological/120243_06031.json
Saving info at: ../data/raw/meteorological/106219_22017.json
Saving info at: ../data/raw/meteorological/154145_48491.json
Saving info at: ../data/raw/meteorological/182798_47157.json
Saving info at: ../data/raw/meteorological/135402_47157.json
Saving info at: ../data/raw/meteorological/135415_13103.json
Saving info at: ../data/raw/meteorological/148234_27111.json
Saving info at: ../data/raw/meteorological/112681_39105.json
Saving info at: ../data/raw/meteorological/130175_06065.json
Saving info at: ../data/raw/meteorological/133377_37071.json
Saving info at: ../data/raw/meteorological/126786_13151.json
Saving info at: ../data/raw/meteorological/163037_06039.json
Saving info at: ../data/raw/meteorological/124414_51061.json
Saving info at: ../data/raw/meteorological/178033_55101.json
Saving info at: ../data/raw/meteorological/181736_28029.json
Saving info at: ../data/raw/meteorological/133033_06037.json
Saving info at: ../data/raw/meteorological/110537_17119.json
Saving info at: ../data/raw/meteorological/181235_22085.json
Saving info at: ../data/raw/meteorological/153673_12085.json
Saving info at: ../data/raw/meteorological/172322_48097.json
Saving info at: ../data/raw/meteorological/130508_55131.json
Saving info at: ../data/raw/meteorological/170201_48091.json
Saving info at: ../data/raw/meteorological/174364_51041.json
Saving info at: ../data/raw/meteorological/139268_06067.json
Saving info at: ../data/raw/meteorological/117251_42017.json
Saving info at: ../data/raw/meteorological/138065_48439.json
Saving info at: ../data/raw/meteorological/149715_42017.json
Saving info at: ../data/raw/meteorological/112090_08001.json
Saving info at: ../data/raw/meteorological/97778_05019.json
Saving info at: ../data/raw/meteorological/113804_24031.json
Saving info at: ../data/raw/meteorological/186068_48291.json
Saving info at: ../data/raw/meteorological/179040_36029.json
Saving info at: ../data/raw/meteorological/95625_54035.json
Saving info at: ../data/raw/meteorological/107353_50027.json
Saving info at: ../data/raw/meteorological/173327_48499.json
Saving info at: ../data/raw/meteorological/159598_15003.json
Saving info at: ../data/raw/meteorological/128822_39141.json
Saving info at: ../data/raw/meteorological/181389_47165.json
Saving info at: ../data/raw/meteorological/182687_51710.json
Saving info at: ../data/raw/meteorological/182300_05143.json
Saving info at: ../data/raw/meteorological/185366_37045.json
Saving info at: ../data/raw/meteorological/93996_54061.json
Saving info at: ../data/raw/meteorological/173918_48085.json
Saving info at: ../data/raw/meteorological/155127_33017.json
Saving info at: ../data/raw/meteorological/150297_12095.json
Saving info at: ../data/raw/meteorological/160787_15003.json
Saving info at: ../data/raw/meteorological/92465_54013.json
Saving info at: ../data/raw/meteorological/152230_06065.json
Saving info at: ../data/raw/meteorological/143288_48113.json
Saving info at: ../data/raw/meteorological/120877_53073.json
Saving info at: ../data/raw/meteorological/149241_13015.json
Saving info at: ../data/raw/meteorological/122191_01115.json
Saving info at: ../data/raw/meteorological/132666_36103.json
Saving info at: ../data/raw/meteorological/110923_45013.json
Saving info at: ../data/raw/meteorological/124015_25025.json
Saving info at: ../data/raw/meteorological/166358_05143.json
Saving info at: ../data/raw/meteorological/104433_48361.json
Saving info at: ../data/raw/meteorological/166407_42051.json
Saving info at: ../data/raw/meteorological/171588_06077.json
Saving info at: ../data/raw/meteorological/98079_45041.json
Saving info at: ../data/raw/meteorological/93249_40143.json
Saving info at: ../data/raw/meteorological/173284_04017.json
Saving info at: ../data/raw/meteorological/184076_50021.json
Saving info at: ../data/raw/meteorological/152384_36119.json
Saving info at: ../data/raw/meteorological/151567_26047.json
Saving info at: ../data/raw/meteorological/185539_40027.json
Saving info at: ../data/raw/meteorological/176520_37119.json
Saving info at: ../data/raw/meteorological/160158_42015.json
Saving info at: ../data/raw/meteorological/121269_53073.json
Saving info at: ../data/raw/meteorological/113212_13311.json
Saving info at: ../data/raw/meteorological/121203_06067.json
Saving info at: ../data/raw/meteorological/178880_39045.json
Saving info at: ../data/raw/meteorological/115279_39113.json
Saving info at: ../data/raw/meteorological/148121_06075.json
Saving info at: ../data/raw/meteorological/96896_36029.json
Saving info at: ../data/raw/meteorological/114818_48085.json
Saving info at: ../data/raw/meteorological/116615_13123.json
Saving info at: ../data/raw/meteorological/124083_37089.json
Saving info at: ../data/raw/meteorological/186458_48423.json
Saving info at: ../data/raw/meteorological/165194_06057.json
Saving info at: ../data/raw/meteorological/138875_22051.json
Saving info at: ../data/raw/meteorological/112571_42077.json
Saving info at: ../data/raw/meteorological/174402_06077.json
Saving info at: ../data/raw/meteorological/105535_54041.json
Saving info at: ../data/raw/meteorological/147423_12086.json
Saving info at: ../data/raw/meteorological/132982_25027.json
Saving info at: ../data/raw/meteorological/107886_24031.json
Saving info at: ../data/raw/meteorological/176182_12073.json
Saving info at: ../data/raw/meteorological/172322_48085.json
Saving info at: ../data/raw/meteorological/184517_29083.json
Saving info at: ../data/raw/meteorological/103692_05027.json
Saving info at: ../data/raw/meteorological/154469_26135.json
Saving info at: ../data/raw/meteorological/184038_13021.json
Saving info at: ../data/raw/meteorological/139391_42133.json
Saving info at: ../data/raw/meteorological/105956_21123.json
Saving info at: ../data/raw/meteorological/155668_19113.json
Saving info at: ../data/raw/meteorological/117434_12083.json
Saving info at: ../data/raw/meteorological/129650_48113.json
Saving info at: ../data/raw/meteorological/103356_42101.json
Saving info at: ../data/raw/meteorological/160593_28085.json
Saving info at: ../data/raw/meteorological/138656_18105.json
Saving info at: ../data/raw/meteorological/137871_48199.json
Saving info at: ../data/raw/meteorological/181929_24033.json
Saving info at: ../data/raw/meteorological/131796_17031.json
Saving info at: ../data/raw/meteorological/184741_33015.json
Saving info at: ../data/raw/meteorological/128213_45083.json
Saving info at: ../data/raw/meteorological/178653_48491.json
Saving info at: ../data/raw/meteorological/120347_13217.json
Saving info at: ../data/raw/meteorological/164060_15003.json
Saving info at: ../data/raw/meteorological/111192_25009.json
Saving info at: ../data/raw/meteorological/157288_48463.json
Saving info at: ../data/raw/meteorological/133010_06029.json
Saving info at: ../data/raw/meteorological/132172_51117.json
Saving info at: ../data/raw/meteorological/176789_06041.json
Saving info at: ../data/raw/meteorological/104613_48185.json
Saving info at: ../data/raw/meteorological/152321_22001.json
Saving info at: ../data/raw/meteorological/129165_34023.json
Saving info at: ../data/raw/meteorological/186260_47049.json
Saving info at: ../data/raw/meteorological/152629_13281.json
Saving info at: ../data/raw/meteorological/119863_39133.json
Saving info at: ../data/raw/meteorological/115662_42017.json
Saving info at: ../data/raw/meteorological/186436_48439.json
Saving info at: ../data/raw/meteorological/111238_51700.json
Saving info at: ../data/raw/meteorological/130410_45079.json
Saving info at: ../data/raw/meteorological/150417_28107.json
Saving info at: ../data/raw/meteorological/95589_34011.json
Saving info at: ../data/raw/meteorological/175066_26143.json
Saving info at: ../data/raw/meteorological/91734_23021.json
Saving info at: ../data/raw/meteorological/119273_29183.json
Saving info at: ../data/raw/meteorological/158965_48339.json
Saving info at: ../data/raw/meteorological/131166_37165.json
Saving info at: ../data/raw/meteorological/135439_55059.json
Saving info at: ../data/raw/meteorological/162164_06075.json
Saving info at: ../data/raw/meteorological/176686_48423.json
Saving info at: ../data/raw/meteorological/127617_54011.json
Saving info at: ../data/raw/meteorological/111830_34005.json
Saving info at: ../data/raw/meteorological/159491_06093.json
Saving info at: ../data/raw/meteorological/124686_12127.json
Saving info at: ../data/raw/meteorological/156822_48085.json
Saving info at: ../data/raw/meteorological/176320_36115.json
Saving info at: ../data/raw/meteorological/183907_06067.json
Saving info at: ../data/raw/meteorological/148346_48491.json
Saving info at: ../data/raw/meteorological/155708_53073.json
Saving info at: ../data/raw/meteorological/103695_37183.json
Saving info at: ../data/raw/meteorological/153861_23017.json
Saving info at: ../data/raw/meteorological/186219_48113.json
Saving info at: ../data/raw/meteorological/146307_28007.json
Saving info at: ../data/raw/meteorological/150951_01125.json
Saving info at: ../data/raw/meteorological/155011_51800.json
Saving info at: ../data/raw/meteorological/182356_39049.json
Saving info at: ../data/raw/meteorological/169034_12031.json
Saving info at: ../data/raw/meteorological/186673_48029.json
Saving info at: ../data/raw/meteorological/184430_40031.json
Saving info at: ../data/raw/meteorological/143591_55079.json
Saving info at: ../data/raw/meteorological/164411_20209.json
Saving info at: ../data/raw/meteorological/180197_13021.json
Saving info at: ../data/raw/meteorological/100103_45007.json
Saving info at: ../data/raw/meteorological/109780_37055.json
Saving info at: ../data/raw/meteorological/150772_24003.json
Saving info at: ../data/raw/meteorological/186163_22005.json
Saving info at: ../data/raw/meteorological/175197_24027.json
Saving info at: ../data/raw/meteorological/178321_48215.json
Saving info at: ../data/raw/meteorological/108944_29047.json
Saving info at: ../data/raw/meteorological/185246_12115.json
Saving info at: ../data/raw/meteorological/141588_04013.json
Saving info at: ../data/raw/meteorological/176336_06033.json
Saving info at: ../data/raw/meteorological/95194_48185.json
Saving info at: ../data/raw/meteorological/170695_42117.json
Saving info at: ../data/raw/meteorological/155773_22031.json
Saving info at: ../data/raw/meteorological/138764_08031.json
Saving info at: ../data/raw/meteorological/177352_48257.json
Saving info at: ../data/raw/meteorological/107879_17099.json
Saving info at: ../data/raw/meteorological/92014_42101.json
Saving info at: ../data/raw/meteorological/156251_48339.json
Saving info at: ../data/raw/meteorological/153553_01027.json
Saving info at: ../data/raw/meteorological/157887_34023.json
Saving info at: ../data/raw/meteorological/119145_51710.json
Saving info at: ../data/raw/meteorological/174430_48085.json
Saving info at: ../data/raw/meteorological/165640_06063.json
Saving info at: ../data/raw/meteorological/115662_42095.json
Saving info at: ../data/raw/meteorological/177373_31177.json
Saving info at: ../data/raw/meteorological/161793_19153.json
Saving info at: ../data/raw/meteorological/119797_49035.json
Saving info at: ../data/raw/meteorological/108779_24510.json
Saving info at: ../data/raw/meteorological/115950_37063.json
Saving info at: ../data/raw/meteorological/186568_23015.json
Saving info at: ../data/raw/meteorological/170197_48491.json
Saving info at: ../data/raw/meteorological/108073_39023.json
Saving info at: ../data/raw/meteorological/166186_48183.json
Saving info at: ../data/raw/meteorological/167527_22071.json
Saving info at: ../data/raw/meteorological/118465_51059.json
Saving info at: ../data/raw/meteorological/104363_34023.json
Saving info at: ../data/raw/meteorological/108267_26149.json
Saving info at: ../data/raw/meteorological/101433_34023.json
Saving info at: ../data/raw/meteorological/156415_48489.json
Saving info at: ../data/raw/meteorological/133801_06053.json
Saving info at: ../data/raw/meteorological/162302_12063.json
Saving info at: ../data/raw/meteorological/97249_20103.json
Saving info at: ../data/raw/meteorological/147575_06065.json
Saving info at: ../data/raw/meteorological/140507_36103.json
Saving info at: ../data/raw/meteorological/156913_12117.json
Saving info at: ../data/raw/meteorological/169761_06065.json
Saving info at: ../data/raw/meteorological/172574_47093.json
Saving info at: ../data/raw/meteorological/161553_45091.json
Saving info at: ../data/raw/meteorological/146705_23009.json
Saving info at: ../data/raw/meteorological/178634_06071.json
Saving info at: ../data/raw/meteorological/176603_08041.json
Saving info at: ../data/raw/meteorological/105483_54039.json
Saving info at: ../data/raw/meteorological/146038_22015.json
Saving info at: ../data/raw/meteorological/162858_26011.json
Saving info at: ../data/raw/meteorological/134903_29189.json
Saving info at: ../data/raw/meteorological/124677_44007.json
Saving info at: ../data/raw/meteorological/129371_42045.json
Saving info at: ../data/raw/meteorological/115305_32003.json
Saving info at: ../data/raw/meteorological/138817_47147.json
Saving info at: ../data/raw/meteorological/112859_34015.json
Saving info at: ../data/raw/meteorological/139139_12083.json
Saving info at: ../data/raw/meteorological/153803_51013.json
Saving info at: ../data/raw/meteorological/157169_05011.json
Saving info at: ../data/raw/meteorological/185418_22105.json
Saving info at: ../data/raw/meteorological/173148_36085.json
Saving info at: ../data/raw/meteorological/170432_18089.json
Saving info at: ../data/raw/meteorological/152592_04019.json
Saving info at: ../data/raw/meteorological/158634_28099.json
Saving info at: ../data/raw/meteorological/169090_17157.json
Saving info at: ../data/raw/meteorological/101751_10005.json
Saving info at: ../data/raw/meteorological/181234_48449.json
Saving info at: ../data/raw/meteorological/95542_48215.json
Saving info at: ../data/raw/meteorological/116395_36115.json
Saving info at: ../data/raw/meteorological/171856_17031.json
Saving info at: ../data/raw/meteorological/148845_37119.json
Saving info at: ../data/raw/meteorological/172480_51147.json
Saving info at: ../data/raw/meteorological/153553_01001.json
Saving info at: ../data/raw/meteorological/182345_39049.json
Saving info at: ../data/raw/meteorological/148281_40097.json
Saving info at: ../data/raw/meteorological/120172_12009.json
Saving info at: ../data/raw/meteorological/180550_55055.json
Saving info at: ../data/raw/meteorological/106866_12031.json
Saving info at: ../data/raw/meteorological/142527_48453.json
Saving info at: ../data/raw/meteorological/121053_36001.json
Saving info at: ../data/raw/meteorological/107373_12095.json
Saving info at: ../data/raw/meteorological/172729_48439.json
Saving info at: ../data/raw/meteorological/185927_48467.json
Saving info at: ../data/raw/meteorological/163876_22019.json
Saving info at: ../data/raw/meteorological/170843_18043.json
Saving info at: ../data/raw/meteorological/153454_40027.json
Saving info at: ../data/raw/meteorological/118136_16001.json
Saving info at: ../data/raw/meteorological/164104_06057.json
Saving info at: ../data/raw/meteorological/147279_37017.json
Saving info at: ../data/raw/meteorological/158867_26159.json
Saving info at: ../data/raw/meteorological/106373_42071.json
Saving info at: ../data/raw/meteorological/116909_55075.json
Saving info at: ../data/raw/meteorological/122056_22039.json
Saving info at: ../data/raw/meteorological/155123_44009.json
Saving info at: ../data/raw/meteorological/180065_48027.json
Saving info at: ../data/raw/meteorological/145776_33011.json
Saving info at: ../data/raw/meteorological/175579_54039.json
Saving info at: ../data/raw/meteorological/172847_38035.json
Saving info at: ../data/raw/meteorological/160090_26115.json
Saving info at: ../data/raw/meteorological/183217_21183.json
Saving info at: ../data/raw/meteorological/124558_36025.json
Saving info at: ../data/raw/meteorological/115121_51047.json
Saving info at: ../data/raw/meteorological/109645_37101.json
Saving info at: ../data/raw/meteorological/148771_19153.json
Saving info at: ../data/raw/meteorological/164604_42101.json
Saving info at: ../data/raw/meteorological/142490_44009.json
Saving info at: ../data/raw/meteorological/176525_04027.json
Saving info at: ../data/raw/meteorological/164800_27039.json
Saving info at: ../data/raw/meteorological/165572_21221.json
Saving info at: ../data/raw/meteorological/179474_29095.json
Saving info at: ../data/raw/meteorological/153287_48085.json
Saving info at: ../data/raw/meteorological/159281_25005.json
Saving info at: ../data/raw/meteorological/182873_28033.json
Saving info at: ../data/raw/meteorological/185117_48453.json

Dask Apply:   0%|          | 0/41 [00:00<?, ?it/s]

/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)

time it took 935.8509486390103
Saving info at: ../data/raw/meteorological/154745_06071.json
Saving info at: ../data/raw/meteorological/101754_42101.json
Saving info at: ../data/raw/meteorological/175799_48439.json
Saving info at: ../data/raw/meteorological/175156_23015.json
Saving info at: ../data/raw/meteorological/169280_18051.json
Saving info at: ../data/raw/meteorological/176503_34041.json
Saving info at: ../data/raw/meteorological/140719_39003.json
Saving info at: ../data/raw/meteorological/177683_48201.json
Saving info at: ../data/raw/meteorological/106634_51177.json
Saving info at: ../data/raw/meteorological/91316_17197.json
Saving info at: ../data/raw/meteorological/132172_51057.json
Saving info at: ../data/raw/meteorological/132199_51111.json
Saving info at: ../data/raw/meteorological/151821_35049.json
Saving info at: ../data/raw/meteorological/151778_17015.json
Saving info at: ../data/raw/meteorological/122622_51041.json
Saving info at: ../data/raw/meteorological/150724_51177.json
Saving info at: ../data/raw/meteorological/178404_06087.json
Saving info at: ../data/raw/meteorological/151189_06071.json
Saving info at: ../data/raw/meteorological/108000_06067.json
Saving info at: ../data/raw/meteorological/144194_24023.json
Saving info at: ../data/raw/meteorological/172672_02020.json
Saving info at: ../data/raw/meteorological/147284_20155.json
Saving info at: ../data/raw/meteorological/182589_26093.json
Saving info at: ../data/raw/meteorological/124671_39025.json
Saving info at: ../data/raw/meteorological/155803_40135.json
Saving info at: ../data/raw/meteorological/185161_42101.json
Saving info at: ../data/raw/meteorological/110923_45019.json
Saving info at: ../data/raw/meteorological/156723_48233.json
Saving info at: ../data/raw/meteorological/163173_40143.json
Saving info at: ../data/raw/meteorological/155343_48049.json
Saving info at: ../data/raw/meteorological/154096_49049.json
Saving info at: ../data/raw/meteorological/175139_48061.json
Saving info at: ../data/raw/meteorological/120032_51069.json
Saving info at: ../data/raw/meteorological/181519_48085.json
Saving info at: ../data/raw/meteorological/122230_22103.json
Saving info at: ../data/raw/meteorological/103033_06071.json
Saving info at: ../data/raw/meteorological/151861_17143.json
Saving info at: ../data/raw/meteorological/158052_06073.json
Saving info at: ../data/raw/meteorological/172856_48315.json
Saving info at: ../data/raw/meteorological/105535_54001.json
Saving info at: ../data/raw/meteorological/156216_21067.json
Saving info at: ../data/raw/meteorological/186776_23011.json
Saving info at: ../data/raw/meteorological/154273_41011.json
Saving info at: ../data/raw/meteorological/103628_51083.json
Saving info at: ../data/raw/meteorological/113249_36011.json
Saving info at: ../data/raw/meteorological/116698_12057.json
Saving info at: ../data/raw/meteorological/185367_45059.json
Saving info at: ../data/raw/meteorological/120754_02020.json
Saving info at: ../data/raw/meteorological/98950_55027.json
Saving info at: ../data/raw/meteorological/142408_29189.json
Saving info at: ../data/raw/meteorological/177358_06085.json
Saving info at: ../data/raw/meteorological/128176_01115.json
Saving info at: ../data/raw/meteorological/111316_51550.json
Saving info at: ../data/raw/meteorological/166303_13187.json
Saving info at: ../data/raw/meteorological/158630_34025.json
Saving info at: ../data/raw/meteorological/153852_27003.json
Saving info at: ../data/raw/meteorological/137873_55095.json
Saving info at: ../data/raw/meteorological/160374_48439.json
Saving info at: ../data/raw/meteorological/166129_06039.json
Saving info at: ../data/raw/meteorological/184222_17011.json
Saving info at: ../data/raw/meteorological/116220_54107.json
Saving info at: ../data/raw/meteorological/157844_48073.json
Saving info at: ../data/raw/meteorological/113358_23029.json
Saving info at: ../data/raw/meteorological/138092_36055.json
Saving info at: ../data/raw/meteorological/157711_27053.json
Saving info at: ../data/raw/meteorological/175555_23011.json
Saving info at: ../data/raw/meteorological/163866_55017.json
Saving info at: ../data/raw/meteorological/163929_55029.json
Saving info at: ../data/raw/meteorological/140016_55133.json
Saving info at: ../data/raw/meteorological/164230_01089.json
Saving info at: ../data/raw/meteorological/160789_06029.json
Saving info at: ../data/raw/meteorological/136180_48005.json
Saving info at: ../data/raw/meteorological/119057_29095.json
Saving info at: ../data/raw/meteorological/186569_33011.json
Saving info at: ../data/raw/meteorological/105128_54025.json
Saving info at: ../data/raw/meteorological/184040_12083.json
Saving info at: ../data/raw/meteorological/158049_21015.json
Saving info at: ../data/raw/meteorological/144368_48401.json
Saving info at: ../data/raw/meteorological/158296_40015.json
Saving info at: ../data/raw/meteorological/144421_36055.json
Saving info at: ../data/raw/meteorological/146711_48027.json
Saving info at: ../data/raw/meteorological/132768_42129.json
Saving info at: ../data/raw/meteorological/139571_13151.json
Saving info at: ../data/raw/meteorological/175144_42101.json
Saving info at: ../data/raw/meteorological/150613_34003.json
Saving info at: ../data/raw/meteorological/130874_13069.json
Saving info at: ../data/raw/meteorological/131096_08001.json
Saving info at: ../data/raw/meteorological/162111_12109.json
Saving info at: ../data/raw/meteorological/138885_22121.json
Saving info at: ../data/raw/meteorological/146765_39061.json
Saving info at: ../data/raw/meteorological/175840_23005.json
Saving info at: ../data/raw/meteorological/120347_13011.json
Saving info at: ../data/raw/meteorological/124502_39061.json
Saving info at: ../data/raw/meteorological/156035_47099.json
Saving info at: ../data/raw/meteorological/112357_12129.json
Saving info at: ../data/raw/meteorological/189340_13135.json
Saving info at: ../data/raw/meteorological/125155_12011.json
Saving info at: ../data/raw/meteorological/183905_48309.json
Saving info at: ../data/raw/meteorological/144407_39089.json
Saving info at: ../data/raw/meteorological/110200_12127.json
Saving info at: ../data/raw/meteorological/103719_22017.json
Saving info at: ../data/raw/meteorological/113981_06037.json
Saving info at: ../data/raw/meteorological/138591_42101.json
Saving info at: ../data/raw/meteorological/177588_04017.json
Saving info at: ../data/raw/meteorological/147528_29099.json
Saving info at: ../data/raw/meteorological/176742_47055.json
Saving info at: ../data/raw/meteorological/168023_26043.json
Saving info at: ../data/raw/meteorological/108294_55079.json
Saving info at: ../data/raw/meteorological/148561_26049.json
Saving info at: ../data/raw/meteorological/109049_51740.json
Saving info at: ../data/raw/meteorological/149215_34027.json
Saving info at: ../data/raw/meteorological/137530_24027.json
Saving info at: ../data/raw/meteorological/109126_01089.json
Saving info at: ../data/raw/meteorological/127108_55079.json
Saving info at: ../data/raw/meteorological/158171_48215.json
Saving info at: ../data/raw/meteorological/137027_40109.json
Saving info at: ../data/raw/meteorological/132113_51007.json
Saving info at: ../data/raw/meteorological/148405_36091.json
Saving info at: ../data/raw/meteorological/132529_47073.json
Saving info at: ../data/raw/meteorological/162128_22121.json
Saving info at: ../data/raw/meteorological/107595_36119.json
Saving info at: ../data/raw/meteorological/180893_47119.json
Saving info at: ../data/raw/meteorological/153195_53041.json
Saving info at: ../data/raw/meteorological/101405_18149.json
Saving info at: ../data/raw/meteorological/157830_01003.json
Saving info at: ../data/raw/meteorological/181931_24037.json
Saving info at: ../data/raw/meteorological/148749_45007.json
Saving info at: ../data/raw/meteorological/150749_22015.json
Saving info at: ../data/raw/meteorological/120075_26163.json
Saving info at: ../data/raw/meteorological/143446_55083.json
Saving info at: ../data/raw/meteorological/101433_34029.json
Saving info at: ../data/raw/meteorological/174464_20009.json
Saving info at: ../data/raw/meteorological/146782_06059.json
Saving info at: ../data/raw/meteorological/141108_39061.json
Saving info at: ../data/raw/meteorological/182909_48061.json
Saving info at: ../data/raw/meteorological/127948_22017.json
Saving info at: ../data/raw/meteorological/180867_48209.json
Saving info at: ../data/raw/meteorological/114183_08041.json
Saving info at: ../data/raw/meteorological/183892_46099.json
Saving info at: ../data/raw/meteorological/112013_40109.json
Saving info at: ../data/raw/meteorological/154537_06067.json
Saving info at: ../data/raw/meteorological/137435_55085.json
Saving info at: ../data/raw/meteorological/163357_06063.json
Saving info at: ../data/raw/meteorological/153965_26027.json
Saving info at: ../data/raw/meteorological/178369_42003.json
Saving info at: ../data/raw/meteorological/169448_06077.json
Saving info at: ../data/raw/meteorological/116220_54095.json
Saving info at: ../data/raw/meteorological/168402_06071.json
Saving info at: ../data/raw/meteorological/150003_39133.json
Saving info at: ../data/raw/meteorological/157275_13089.json
Saving info at: ../data/raw/meteorological/131308_42007.json
Saving info at: ../data/raw/meteorological/155883_06089.json
Saving info at: ../data/raw/meteorological/101409_26161.json
Saving info at: ../data/raw/meteorological/183309_22019.json
Saving info at: ../data/raw/meteorological/93876_37033.json
Saving info at: ../data/raw/meteorological/161088_19033.json
Saving info at: ../data/raw/meteorological/139752_29101.json
Saving info at: ../data/raw/meteorological/153994_37141.json
Saving info at: ../data/raw/meteorological/100975_17001.json
Saving info at: ../data/raw/meteorological/167755_18093.json
Saving info at: ../data/raw/meteorological/178226_06111.json
Saving info at: ../data/raw/meteorological/151300_22095.json
Saving info at: ../data/raw/meteorological/138754_48329.json
Saving info at: ../data/raw/meteorological/133132_53033.json
Saving info at: ../data/raw/meteorological/183554_20009.json
Saving info at: ../data/raw/meteorological/171941_06093.json
Saving info at: ../data/raw/meteorological/122362_42041.json
Saving info at: ../data/raw/meteorological/179559_48225.json
Saving info at: ../data/raw/meteorological/143841_23021.json
Saving info at: ../data/raw/meteorological/152510_53063.json
Saving info at: ../data/raw/meteorological/174224_17113.json
Saving info at: ../data/raw/meteorological/161655_47157.json
Saving info at: ../data/raw/meteorological/152460_33015.json
Saving info at: ../data/raw/meteorological/150658_06097.json
Saving info at: ../data/raw/meteorological/158914_06071.json
Saving info at: ../data/raw/meteorological/117013_36107.json
Saving info at: ../data/raw/meteorological/136244_05019.json
Saving info at: ../data/raw/meteorological/97961_51075.json
Saving info at: ../data/raw/meteorological/115199_40031.json
Saving info at: ../data/raw/meteorological/94371_54065.json
Saving info at: ../data/raw/meteorological/93515_45077.json
Saving info at: ../data/raw/meteorological/101406_26059.json
Saving info at: ../data/raw/meteorological/180484_12089.json
Saving info at: ../data/raw/meteorological/147583_48215.json
Saving info at: ../data/raw/meteorological/151319_12099.json
Saving info at: ../data/raw/meteorological/154849_06073.json
Saving info at: ../data/raw/meteorological/143907_06059.json
Saving info at: ../data/raw/meteorological/168977_39165.json
Saving info at: ../data/raw/meteorological/170273_48439.json
Saving info at: ../data/raw/meteorological/106620_34037.json
Saving info at: ../data/raw/meteorological/158860_12109.json
Saving info at: ../data/raw/meteorological/104939_25005.json
Saving info at: ../data/raw/meteorological/149633_48113.json
Saving info at: ../data/raw/meteorological/121189_06065.json
Saving info at: ../data/raw/meteorological/93818_21111.json
Saving info at: ../data/raw/meteorological/148150_12086.json
Saving info at: ../data/raw/meteorological/145844_21013.json
Saving info at: ../data/raw/meteorological/91856_33013.json
Saving info at: ../data/raw/meteorological/175336_55033.json
Saving info at: ../data/raw/meteorological/147554_05103.json
Saving info at: ../data/raw/meteorological/94026_13121.json
Saving info at: ../data/raw/meteorological/135032_42087.json
Saving info at: ../data/raw/meteorological/142888_37141.json
Saving info at: ../data/raw/meteorological/169187_48469.json
Saving info at: ../data/raw/meteorological/111358_18157.json
Saving info at: ../data/raw/meteorological/110729_34037.json
Saving info at: ../data/raw/meteorological/95396_39113.json
Saving info at: ../data/raw/meteorological/137830_48401.json
Saving info at: ../data/raw/meteorological/104973_42029.json
Saving info at: ../data/raw/meteorological/142092_37081.json
Saving info at: ../data/raw/meteorological/105214_37101.json
Saving info at: ../data/raw/meteorological/127108_55133.json
Saving info at: ../data/raw/meteorological/134840_42087.json
Saving info at: ../data/raw/meteorological/103395_17031.json
Saving info at: ../data/raw/meteorological/115032_28089.json
Saving info at: ../data/raw/meteorological/97744_26081.json
Saving info at: ../data/raw/meteorological/147225_48465.json
Saving info at: ../data/raw/meteorological/165711_37171.json
Done with saving.
Starting

Dask Apply:   0%|          | 0/41 [00:00<?, ?it/s]

/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)

time it took 889.6187344810023
Saving info at: ../data/raw/meteorological/129405_12086.json
Saving info at: ../data/raw/meteorological/142205_48061.json
Saving info at: ../data/raw/meteorological/162426_06071.json
Saving info at: ../data/raw/meteorological/103952_48339.json
Saving info at: ../data/raw/meteorological/126735_42069.json
Saving info at: ../data/raw/meteorological/163146_40143.json
Saving info at: ../data/raw/meteorological/146295_01097.json
Saving info at: ../data/raw/meteorological/141883_36081.json
Saving info at: ../data/raw/meteorological/118459_24033.json
Saving info at: ../data/raw/meteorological/100467_48029.json
Saving info at: ../data/raw/meteorological/184479_17157.json
Saving info at: ../data/raw/meteorological/175404_22017.json
Saving info at: ../data/raw/meteorological/151466_48355.json
Saving info at: ../data/raw/meteorological/172348_26005.json
Saving info at: ../data/raw/meteorological/129536_36099.json
Saving info at: ../data/raw/meteorological/117250_34041.json
Saving info at: ../data/raw/meteorological/130567_04005.json
Saving info at: ../data/raw/meteorological/180247_01089.json
Saving info at: ../data/raw/meteorological/153243_08001.json
Saving info at: ../data/raw/meteorological/93917_22051.json
Saving info at: ../data/raw/meteorological/138581_34023.json
Saving info at: ../data/raw/meteorological/143979_37043.json
Saving info at: ../data/raw/meteorological/143917_32003.json
Saving info at: ../data/raw/meteorological/107997_06067.json
Saving info at: ../data/raw/meteorological/116473_47157.json
Saving info at: ../data/raw/meteorological/179804_17031.json
Saving info at: ../data/raw/meteorological/99606_10001.json
Saving info at: ../data/raw/meteorological/110526_06059.json
Saving info at: ../data/raw/meteorological/176407_37089.json
Saving info at: ../data/raw/meteorological/156709_12035.json
Saving info at: ../data/raw/meteorological/107715_51059.json
Saving info at: ../data/raw/meteorological/124272_36091.json
Saving info at: ../data/raw/meteorological/171798_13089.json
Saving info at: ../data/raw/meteorological/147407_28039.json
Saving info at: ../data/raw/meteorological/110972_41051.json
Saving info at: ../data/raw/meteorological/98283_36055.json
Saving info at: ../data/raw/meteorological/109224_36029.json
Saving info at: ../data/raw/meteorological/127789_08001.json
Saving info at: ../data/raw/meteorological/186219_48309.json
Saving info at: ../data/raw/meteorological/120347_13067.json
Saving info at: ../data/raw/meteorological/167492_42125.json
Saving info at: ../data/raw/meteorological/131807_06087.json
Saving info at: ../data/raw/meteorological/127617_54039.json
Saving info at: ../data/raw/meteorological/102693_41067.json
Saving info at: ../data/raw/meteorological/146705_23021.json
Saving info at: ../data/raw/meteorological/185741_32019.json
Saving info at: ../data/raw/meteorological/112454_17077.json
Saving info at: ../data/raw/meteorological/165008_02020.json
Saving info at: ../data/raw/meteorological/186574_06019.json
Saving info at: ../data/raw/meteorological/159360_13089.json
Saving info at: ../data/raw/meteorological/165243_53061.json
Saving info at: ../data/raw/meteorological/162041_36021.json
Saving info at: ../data/raw/meteorological/134142_36093.json
Saving info at: ../data/raw/meteorological/102565_34037.json
Saving info at: ../data/raw/meteorological/92280_37049.json
Saving info at: ../data/raw/meteorological/145200_42011.json
Saving info at: ../data/raw/meteorological/104684_26113.json
Saving info at: ../data/raw/meteorological/155036_06057.json
Saving info at: ../data/raw/meteorological/143358_48029.json
Saving info at: ../data/raw/meteorological/160664_26067.json
Saving info at: ../data/raw/meteorological/177615_55069.json
Saving info at: ../data/raw/meteorological/130023_39151.json
Saving info at: ../data/raw/meteorological/181173_12123.json
Saving info at: ../data/raw/meteorological/161434_17197.json
Saving info at: ../data/raw/meteorological/148294_48215.json
Saving info at: ../data/raw/meteorological/132141_51111.json
Saving info at: ../data/raw/meteorological/97379_39025.json
Saving info at: ../data/raw/meteorological/183298_25021.json
Saving info at: ../data/raw/meteorological/142645_42017.json
Saving info at: ../data/raw/meteorological/115838_12071.json
Saving info at: ../data/raw/meteorological/99606_10005.json
Saving info at: ../data/raw/meteorological/145578_37081.json
Saving info at: ../data/raw/meteorological/117250_34005.json
Saving info at: ../data/raw/meteorological/163582_25021.json
Saving info at: ../data/raw/meteorological/153851_37035.json
Saving info at: ../data/raw/meteorological/163357_06077.json
Saving info at: ../data/raw/meteorological/157379_42095.json
Saving info at: ../data/raw/meteorological/174577_12073.json
Saving info at: ../data/raw/meteorological/121189_06073.json
Saving info at: ../data/raw/meteorological/159617_31055.json
Saving info at: ../data/raw/meteorological/170366_12011.json
Saving info at: ../data/raw/meteorological/126569_26163.json
Saving info at: ../data/raw/meteorological/102980_28029.json
Saving info at: ../data/raw/meteorological/113173_36103.json
Saving info at: ../data/raw/meteorological/163015_39095.json
Saving info at: ../data/raw/meteorological/175132_50019.json
Saving info at: ../data/raw/meteorological/151830_36115.json
Saving info at: ../data/raw/meteorological/138700_28085.json
Saving info at: ../data/raw/meteorological/126531_01051.json
Saving info at: ../data/raw/meteorological/139623_51041.json
Saving info at: ../data/raw/meteorological/171673_47165.json
Saving info at: ../data/raw/meteorological/163015_39123.json
Saving info at: ../data/raw/meteorological/140127_51107.json
Saving info at: ../data/raw/meteorological/175402_48423.json
Saving info at: ../data/raw/meteorological/163841_20173.json
Saving info at: ../data/raw/meteorological/179357_36091.json
Saving info at: ../data/raw/meteorological/154968_01073.json
Saving info at: ../data/raw/meteorological/153127_17031.json
Saving info at: ../data/raw/meteorological/118772_12085.json
Saving info at: ../data/raw/meteorological/142760_06029.json
Saving info at: ../data/raw/meteorological/131036_37033.json
Saving info at: ../data/raw/meteorological/131166_37081.json
Saving info at: ../data/raw/meteorological/119495_17097.json
Saving info at: ../data/raw/meteorological/135617_12041.json
Saving info at: ../data/raw/meteorological/156579_47031.json
Saving info at: ../data/raw/meteorological/157188_48215.json
Saving info at: ../data/raw/meteorological/109310_27001.json
Saving info at: ../data/raw/meteorological/124003_39007.json
Saving info at: ../data/raw/meteorological/143448_06083.json
Saving info at: ../data/raw/meteorological/182053_48293.json
Saving info at: ../data/raw/meteorological/140427_51179.json
Saving info at: ../data/raw/meteorological/149215_34021.json
Saving info at: ../data/raw/meteorological/166765_36019.json
Saving info at: ../data/raw/meteorological/160411_06077.json
Saving info at: ../data/raw/meteorological/147601_22001.json
Saving info at: ../data/raw/meteorological/137393_24021.json
Saving info at: ../data/raw/meteorological/186801_47165.json
Saving info at: ../data/raw/meteorological/104560_40143.json
Saving info at: ../data/raw/meteorological/187867_34027.json
Saving info at: ../data/raw/meteorological/130821_26011.json
Saving info at: ../data/raw/meteorological/154756_06085.json
Saving info at: ../data/raw/meteorological/108647_51161.json
Saving info at: ../data/raw/meteorological/133839_06065.json
Saving info at: ../data/raw/meteorological/91663_48329.json
Saving info at: ../data/raw/meteorological/185529_40027.json
Saving info at: ../data/raw/meteorological/173253_48029.json
Saving info at: ../data/raw/meteorological/168818_48251.json
Saving info at: ../data/raw/meteorological/181487_48085.json
Saving info at: ../data/raw/meteorological/183275_26099.json
Saving info at: ../data/raw/meteorological/168695_17089.json
Saving info at: ../data/raw/meteorological/157637_48113.json
Saving info at: ../data/raw/meteorological/157176_48215.json
Saving info at: ../data/raw/meteorological/112997_51810.json
Saving info at: ../data/raw/meteorological/178551_06007.json
Saving info at: ../data/raw/meteorological/158314_06019.json
Saving info at: ../data/raw/meteorological/138516_46099.json
Saving info at: ../data/raw/meteorological/114280_13139.json
Saving info at: ../data/raw/meteorological/161144_34013.json
Saving info at: ../data/raw/meteorological/179177_06023.json
Saving info at: ../data/raw/meteorological/96898_13067.json
Saving info at: ../data/raw/meteorological/131003_25021.json
Saving info at: ../data/raw/meteorological/112538_39093.json
Saving info at: ../data/raw/meteorological/167648_48113.json
Saving info at: ../data/raw/meteorological/112075_25023.json
Saving info at: ../data/raw/meteorological/119520_12053.json
Saving info at: ../data/raw/meteorological/159735_47055.json
Saving info at: ../data/raw/meteorological/185129_08101.json
Saving info at: ../data/raw/meteorological/171300_48453.json
Saving info at: ../data/raw/meteorological/154924_23009.json
Saving info at: ../data/raw/meteorological/171588_06067.json
Saving info at: ../data/raw/meteorological/116311_18105.json
Saving info at: ../data/raw/meteorological/178509_36001.json
Saving info at: ../data/raw/meteorological/103539_23003.json
Saving info at: ../data/raw/meteorological/181988_55021.json
Saving info at: ../data/raw/meteorological/150384_19157.json
Saving info at: ../data/raw/meteorological/105746_54081.json
Saving info at: ../data/raw/meteorological/171185_39009.json
Saving info at: ../data/raw/meteorological/94222_48325.json
Saving info at: ../data/raw/meteorological/179774_02020.json
Saving info at: ../data/raw/meteorological/117625_23019.json
Saving info at: ../data/raw/meteorological/171798_13121.json
Saving info at: ../data/raw/meteorological/153601_12057.json
Saving info at: ../data/raw/meteorological/109309_19061.json
Saving info at: ../data/raw/meteorological/128273_51179.json
Saving info at: ../data/raw/meteorological/176511_20091.json
Saving info at: ../data/raw/meteorological/143513_36059.json
Saving info at: ../data/raw/meteorological/143689_26019.json
Saving info at: ../data/raw/meteorological/137112_13001.json
Saving info at: ../data/raw/meteorological/96660_37153.json
Saving info at: ../data/raw/meteorological/147387_01045.json
Saving info at: ../data/raw/meteorological/158066_06029.json
Saving info at: ../data/raw/meteorological/156931_12117.json
Saving info at: ../data/raw/meteorological/177882_06023.json
Saving info at: ../data/raw/meteorological/177572_18163.json
Saving info at: ../data/raw/meteorological/171662_12086.json
Saving info at: ../data/raw/meteorological/175063_47149.json
Saving info at: ../data/raw/meteorological/176632_48279.json
Saving info at: ../data/raw/meteorological/159591_42045.json
Saving info at: ../data/raw/meteorological/156159_46099.json
Saving info at: ../data/raw/meteorological/96168_54005.json
Saving info at: ../data/raw/meteorological/179036_36055.json
Saving info at: ../data/raw/meteorological/127287_04013.json
Saving info at: ../data/raw/meteorological/169577_40143.json
Saving info at: ../data/raw/meteorological/124017_44007.json
Saving info at: ../data/raw/meteorological/156281_48491.json
Saving info at: ../data/raw/meteorological/186653_12083.json
Saving info at: ../data/raw/meteorological/154803_29047.json
Saving info at: ../data/raw/meteorological/153528_22001.json
Saving info at: ../data/raw/meteorological/175962_06059.json
Saving info at: ../data/raw/meteorological/104861_10003.json
Saving info at: ../data/raw/meteorological/138645_34005.json
Saving info at: ../data/raw/meteorological/116899_06067.json
Saving info at: ../data/raw/meteorological/169242_55097.json
Saving info at: ../data/raw/meteorological/158932_06067.json
Saving info at: ../data/raw/meteorological/142365_06073.json
Saving info at: ../data/raw/meteorological/173043_26111.json
Done with saving.
Starting

Dask Apply:   0%|          | 0/41 [00:00<?, ?it/s]

/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)

time it took 784.0700198230043
Saving info at: ../data/raw/meteorological/137840_47157.json
Saving info at: ../data/raw/meteorological/156286_22039.json
Saving info at: ../data/raw/meteorological/132156_06065.json
Saving info at: ../data/raw/meteorological/105903_37183.json
Saving info at: ../data/raw/meteorological/182883_47047.json
Saving info at: ../data/raw/meteorological/133968_29047.json
Saving info at: ../data/raw/meteorological/185769_39095.json
Saving info at: ../data/raw/meteorological/112345_12011.json
Saving info at: ../data/raw/meteorological/171625_37081.json
Saving info at: ../data/raw/meteorological/170075_49035.json
Saving info at: ../data/raw/meteorological/117791_01101.json
Saving info at: ../data/raw/meteorological/143739_13135.json
Saving info at: ../data/raw/meteorological/164287_26009.json
Saving info at: ../data/raw/meteorological/115032_28049.json
Saving info at: ../data/raw/meteorological/146211_48215.json
Saving info at: ../data/raw/meteorological/103054_39045.json
Saving info at: ../data/raw/meteorological/151991_37073.json
Saving info at: ../data/raw/meteorological/150850_55127.json
Saving info at: ../data/raw/meteorological/144697_18163.json
Saving info at: ../data/raw/meteorological/121545_18009.json
Saving info at: ../data/raw/meteorological/103068_36059.json
Saving info at: ../data/raw/meteorological/163500_06063.json
Saving info at: ../data/raw/meteorological/136083_42011.json
Saving info at: ../data/raw/meteorological/128216_19013.json
Saving info at: ../data/raw/meteorological/158047_39165.json
Saving info at: ../data/raw/meteorological/113586_25017.json
Saving info at: ../data/raw/meteorological/116601_29095.json
Saving info at: ../data/raw/meteorological/181004_45003.json
Saving info at: ../data/raw/meteorological/159470_48215.json
Saving info at: ../data/raw/meteorological/136819_22033.json
Saving info at: ../data/raw/meteorological/122910_21141.json
Saving info at: ../data/raw/meteorological/167531_22033.json
Saving info at: ../data/raw/meteorological/187595_13077.json
Saving info at: ../data/raw/meteorological/97298_25009.json
Saving info at: ../data/raw/meteorological/134771_34029.json
Saving info at: ../data/raw/meteorological/142429_22017.json
Saving info at: ../data/raw/meteorological/174875_42119.json
Saving info at: ../data/raw/meteorological/134898_39007.json
Saving info at: ../data/raw/meteorological/146032_48201.json
Saving info at: ../data/raw/meteorological/124379_36013.json
Saving info at: ../data/raw/meteorological/119571_17031.json
Saving info at: ../data/raw/meteorological/138786_17197.json
Saving info at: ../data/raw/meteorological/176142_17031.json
Saving info at: ../data/raw/meteorological/187411_34017.json
Saving info at: ../data/raw/meteorological/120974_12011.json
Saving info at: ../data/raw/meteorological/148937_33013.json
Saving info at: ../data/raw/meteorological/177357_21111.json
Saving info at: ../data/raw/meteorological/182975_25005.json
Saving info at: ../data/raw/meteorological/119913_13185.json
Saving info at: ../data/raw/meteorological/176013_48029.json
Saving info at: ../data/raw/meteorological/183341_55057.json
Saving info at: ../data/raw/meteorological/113706_05093.json
Saving info at: ../data/raw/meteorological/173917_48339.json
Saving info at: ../data/raw/meteorological/103694_26125.json
Saving info at: ../data/raw/meteorological/98896_37063.json
Saving info at: ../data/raw/meteorological/146077_36027.json
Saving info at: ../data/raw/meteorological/107754_51061.json
Saving info at: ../data/raw/meteorological/170609_24043.json
Saving info at: ../data/raw/meteorological/174309_05007.json
Saving info at: ../data/raw/meteorological/125520_22033.json
Saving info at: ../data/raw/meteorological/180138_23005.json
Saving info at: ../data/raw/meteorological/175323_44007.json
Saving info at: ../data/raw/meteorological/181995_08035.json
Saving info at: ../data/raw/meteorological/137142_21083.json
Saving info at: ../data/raw/meteorological/173822_17097.json
Saving info at: ../data/raw/meteorological/138528_47093.json
Saving info at: ../data/raw/meteorological/164119_06029.json
Saving info at: ../data/raw/meteorological/179540_06029.json
Saving info at: ../data/raw/meteorological/167901_22049.json
Saving info at: ../data/raw/meteorological/184452_39153.json
Saving info at: ../data/raw/meteorological/129739_47157.json
Saving info at: ../data/raw/meteorological/121720_48201.json
Saving info at: ../data/raw/meteorological/112507_13199.json
Saving info at: ../data/raw/meteorological/158599_51680.json
Saving info at: ../data/raw/meteorological/184104_34037.json
Saving info at: ../data/raw/meteorological/94022_22019.json
Saving info at: ../data/raw/meteorological/122471_39007.json
Saving info at: ../data/raw/meteorological/183757_41047.json
Saving info at: ../data/raw/meteorological/120166_26125.json
Saving info at: ../data/raw/meteorological/142500_44009.json
Saving info at: ../data/raw/meteorological/168980_53063.json
Saving info at: ../data/raw/meteorological/174610_06071.json
Saving info at: ../data/raw/meteorological/151560_51103.json
Saving info at: ../data/raw/meteorological/97571_42085.json
Saving info at: ../data/raw/meteorological/171732_27111.json
Saving info at: ../data/raw/meteorological/137918_42069.json
Saving info at: ../data/raw/meteorological/127341_04013.json
Saving info at: ../data/raw/meteorological/168368_06059.json
Saving info at: ../data/raw/meteorological/179854_13059.json
Saving info at: ../data/raw/meteorological/145578_37135.json
Saving info at: ../data/raw/meteorological/179603_48029.json
Saving info at: ../data/raw/meteorological/130653_37183.json
Saving info at: ../data/raw/meteorological/130495_17031.json
Saving info at: ../data/raw/meteorological/174297_29023.json
Saving info at: ../data/raw/meteorological/130769_54039.json
Saving info at: ../data/raw/meteorological/162841_26049.json
Saving info at: ../data/raw/meteorological/152629_13077.json
Saving info at: ../data/raw/meteorological/111830_34009.json
Saving info at: ../data/raw/meteorological/120347_13199.json
Saving info at: ../data/raw/meteorological/161965_39035.json
Saving info at: ../data/raw/meteorological/182357_48439.json
Saving info at: ../data/raw/meteorological/97098_12019.json
Saving info at: ../data/raw/meteorological/123769_48497.json
Saving info at: ../data/raw/meteorological/132631_39071.json
Saving info at: ../data/raw/meteorological/92204_19113.json
Saving info at: ../data/raw/meteorological/115031_13311.json
Saving info at: ../data/raw/meteorological/179800_17107.json
Saving info at: ../data/raw/meteorological/130410_45075.json
Saving info at: ../data/raw/meteorological/160892_36043.json
Saving info at: ../data/raw/meteorological/143510_24003.json
Saving info at: ../data/raw/meteorological/163073_35049.json
Saving info at: ../data/raw/meteorological/93048_12111.json
Saving info at: ../data/raw/meteorological/142456_50023.json
Saving info at: ../data/raw/meteorological/179036_36029.json
Saving info at: ../data/raw/meteorological/125999_36019.json
Saving info at: ../data/raw/meteorological/177042_06019.json
Saving info at: ../data/raw/meteorological/182359_48085.json
Saving info at: ../data/raw/meteorological/124120_39049.json
Saving info at: ../data/raw/meteorological/95306_12103.json
Saving info at: ../data/raw/meteorological/152172_45051.json
Saving info at: ../data/raw/meteorological/103628_51037.json
Saving info at: ../data/raw/meteorological/152834_12086.json
Saving info at: ../data/raw/meteorological/92226_10005.json
Saving info at: ../data/raw/meteorological/167704_27141.json
Saving info at: ../data/raw/meteorological/131655_13279.json
Saving info at: ../data/raw/meteorological/151873_06037.json
Saving info at: ../data/raw/meteorological/121846_35049.json
Saving info at: ../data/raw/meteorological/155094_34013.json
Saving info at: ../data/raw/meteorological/116689_34019.json
Saving info at: ../data/raw/meteorological/155530_21165.json
Saving info at: ../data/raw/meteorological/149331_06071.json
Saving info at: ../data/raw/meteorological/183368_01101.json
Saving info at: ../data/raw/meteorological/175490_40109.json
Saving info at: ../data/raw/meteorological/112362_12133.json
Saving info at: ../data/raw/meteorological/133020_06001.json
Saving info at: ../data/raw/meteorological/124155_42041.json
Saving info at: ../data/raw/meteorological/151683_51041.json
Saving info at: ../data/raw/meteorological/155812_48085.json
Saving info at: ../data/raw/meteorological/182946_20209.json
Saving info at: ../data/raw/meteorological/138717_05043.json
Saving info at: ../data/raw/meteorological/153200_33013.json
Saving info at: ../data/raw/meteorological/175377_55079.json
Saving info at: ../data/raw/meteorological/148561_26125.json
Saving info at: ../data/raw/meteorological/146450_39087.json
Saving info at: ../data/raw/meteorological/113171_13129.json
Saving info at: ../data/raw/meteorological/180842_28049.json
Saving info at: ../data/raw/meteorological/164721_23005.json
Saving info at: ../data/raw/meteorological/148846_12099.json
Saving info at: ../data/raw/meteorological/165384_22033.json
Saving info at: ../data/raw/meteorological/141702_04013.json
Saving info at: ../data/raw/meteorological/146053_06065.json
Saving info at: ../data/raw/meteorological/158052_06059.json
Saving info at: ../data/raw/meteorological/183129_13135.json
Saving info at: ../data/raw/meteorological/138885_22033.json
Saving info at: ../data/raw/meteorological/183176_12009.json
Saving info at: ../data/raw/meteorological/184928_55101.json
Saving info at: ../data/raw/meteorological/169576_15003.json
Saving info at: ../data/raw/meteorological/167157_38017.json
Saving info at: ../data/raw/meteorological/138830_39089.json
Saving info at: ../data/raw/meteorological/114548_39003.json
Saving info at: ../data/raw/meteorological/117742_32003.json
Saving info at: ../data/raw/meteorological/150658_06087.json
Saving info at: ../data/raw/meteorological/158811_17183.json
Saving info at: ../data/raw/meteorological/180197_13113.json
Saving info at: ../data/raw/meteorological/126324_17025.json
Saving info at: ../data/raw/meteorological/167841_20079.json
Saving info at: ../data/raw/meteorological/91705_50025.json
Saving info at: ../data/raw/meteorological/153348_25003.json
Saving info at: ../data/raw/meteorological/154120_48439.json
Saving info at: ../data/raw/meteorological/167655_06077.json
Saving info at: ../data/raw/meteorological/143657_53041.json
Saving info at: ../data/raw/meteorological/127327_40109.json
Saving info at: ../data/raw/meteorological/149327_47179.json
Saving info at: ../data/raw/meteorological/167809_46135.json
Saving info at: ../data/raw/meteorological/120347_13195.json
Saving info at: ../data/raw/meteorological/132272_06085.json
Saving info at: ../data/raw/meteorological/120628_44009.json
Done with saving.
Starting

Dask Apply:   0%|          | 0/41 [00:00<?, ?it/s]

/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)

time it took 911.637804375001
Saving info at: ../data/raw/meteorological/110638_25027.json
Saving info at: ../data/raw/meteorological/128175_37021.json
Saving info at: ../data/raw/meteorological/149489_26147.json
Saving info at: ../data/raw/meteorological/140662_36001.json
Saving info at: ../data/raw/meteorological/164555_53009.json
Saving info at: ../data/raw/meteorological/103158_37085.json
Saving info at: ../data/raw/meteorological/177882_06045.json
Saving info at: ../data/raw/meteorological/150117_48439.json
Saving info at: ../data/raw/meteorological/153876_25027.json
Saving info at: ../data/raw/meteorological/156288_37169.json
Saving info at: ../data/raw/meteorological/178741_21155.json
Saving info at: ../data/raw/meteorological/125774_39049.json
Saving info at: ../data/raw/meteorological/153320_36077.json
Saving info at: ../data/raw/meteorological/160411_06089.json
Saving info at: ../data/raw/meteorological/183877_04019.json
Saving info at: ../data/raw/meteorological/177576_39027.json
Saving info at: ../data/raw/meteorological/148719_26037.json
Saving info at: ../data/raw/meteorological/95212_22011.json
Saving info at: ../data/raw/meteorological/140548_37107.json
Saving info at: ../data/raw/meteorological/184745_23007.json
Saving info at: ../data/raw/meteorological/115543_34025.json
Saving info at: ../data/raw/meteorological/111275_25015.json
Saving info at: ../data/raw/meteorological/125060_26073.json
Saving info at: ../data/raw/meteorological/156258_51041.json
Saving info at: ../data/raw/meteorological/156255_48381.json
Saving info at: ../data/raw/meteorological/158622_39085.json
Saving info at: ../data/raw/meteorological/91736_23009.json
Saving info at: ../data/raw/meteorological/140448_37183.json
Saving info at: ../data/raw/meteorological/145809_37039.json
Saving info at: ../data/raw/meteorological/149329_47155.json
Saving info at: ../data/raw/meteorological/173625_04021.json
Saving info at: ../data/raw/meteorological/166336_42079.json
Saving info at: ../data/raw/meteorological/182542_48253.json
Saving info at: ../data/raw/meteorological/112675_36091.json
Saving info at: ../data/raw/meteorological/175641_48019.json
Saving info at: ../data/raw/meteorological/161501_06077.json
Saving info at: ../data/raw/meteorological/146393_34027.json
Saving info at: ../data/raw/meteorological/109965_25027.json
Saving info at: ../data/raw/meteorological/111649_06059.json
Saving info at: ../data/raw/meteorological/167287_49049.json
Saving info at: ../data/raw/meteorological/129036_06071.json
Saving info at: ../data/raw/meteorological/184042_13229.json
Saving info at: ../data/raw/meteorological/112506_13121.json
Saving info at: ../data/raw/meteorological/157494_06029.json
Saving info at: ../data/raw/meteorological/179218_18061.json
Saving info at: ../data/raw/meteorological/139052_22017.json
Saving info at: ../data/raw/meteorological/96130_48113.json
Saving info at: ../data/raw/meteorological/183299_44007.json
Saving info at: ../data/raw/meteorological/120818_39093.json
Saving info at: ../data/raw/meteorological/123916_55117.json
Saving info at: ../data/raw/meteorological/142900_46083.json
Saving info at: ../data/raw/meteorological/171893_06077.json
Saving info at: ../data/raw/meteorological/143175_36111.json
Saving info at: ../data/raw/meteorological/132113_51041.json
Saving info at: ../data/raw/meteorological/174642_12081.json
Saving info at: ../data/raw/meteorological/138882_19065.json
Saving info at: ../data/raw/meteorological/108298_39055.json
Saving info at: ../data/raw/meteorological/174656_47037.json
Saving info at: ../data/raw/meteorological/133994_06013.json
Saving info at: ../data/raw/meteorological/91472_39049.json
Saving info at: ../data/raw/meteorological/169058_54039.json
Saving info at: ../data/raw/meteorological/142287_37097.json
Saving info at: ../data/raw/meteorological/176789_06087.json
Saving info at: ../data/raw/meteorological/158073_48027.json
Saving info at: ../data/raw/meteorological/173447_26139.json
Saving info at: ../data/raw/meteorological/184928_55059.json
Saving info at: ../data/raw/meteorological/105272_28151.json
Saving info at: ../data/raw/meteorological/145828_47155.json
Saving info at: ../data/raw/meteorological/168818_48113.json
Saving info at: ../data/raw/meteorological/130412_13245.json
Saving info at: ../data/raw/meteorological/128935_39085.json
Saving info at: ../data/raw/meteorological/105025_55085.json
Saving info at: ../data/raw/meteorological/128176_01121.json
Saving info at: ../data/raw/meteorological/181967_51083.json
Saving info at: ../data/raw/meteorological/105073_36059.json
Saving info at: ../data/raw/meteorological/138274_29095.json
Saving info at: ../data/raw/meteorological/180202_18055.json
Saving info at: ../data/raw/meteorological/177066_06019.json
Saving info at: ../data/raw/meteorological/142435_42089.json
Saving info at: ../data/raw/meteorological/148037_36091.json
Saving info at: ../data/raw/meteorological/186424_28089.json
Saving info at: ../data/raw/meteorological/140079_46099.json
Saving info at: ../data/raw/meteorological/175252_06043.json
Saving info at: ../data/raw/meteorological/176689_35005.json
Saving info at: ../data/raw/meteorological/146063_51107.json
Saving info at: ../data/raw/meteorological/150749_22031.json
Saving info at: ../data/raw/meteorological/173448_26081.json
Saving info at: ../data/raw/meteorological/105259_48245.json
Saving info at: ../data/raw/meteorological/144712_29189.json
Saving info at: ../data/raw/meteorological/126371_21157.json
Saving info at: ../data/raw/meteorological/156555_37087.json
Saving info at: ../data/raw/meteorological/155704_48491.json
Saving info at: ../data/raw/meteorological/184901_40109.json
Saving info at: ../data/raw/meteorological/186011_51710.json
Saving info at: ../data/raw/meteorological/167986_21037.json
Saving info at: ../data/raw/meteorological/174275_48491.json
Saving info at: ../data/raw/meteorological/97203_51107.json
Saving info at: ../data/raw/meteorological/169118_06065.json
Saving info at: ../data/raw/meteorological/103888_36091.json
Saving info at: ../data/raw/meteorological/95439_39077.json
Saving info at: ../data/raw/meteorological/164160_45003.json
Saving info at: ../data/raw/meteorological/122855_10003.json
Saving info at: ../data/raw/meteorological/108544_29021.json
Saving info at: ../data/raw/meteorological/135643_28087.json
Saving info at: ../data/raw/meteorological/172990_47037.json
Saving info at: ../data/raw/meteorological/150749_22043.json
Saving info at: ../data/raw/meteorological/91638_39035.json
Saving info at: ../data/raw/meteorological/127773_36111.json
Saving info at: ../data/raw/meteorological/132982_25023.json
Saving info at: ../data/raw/meteorological/106615_24015.json
Saving info at: ../data/raw/meteorological/117867_13135.json
Saving info at: ../data/raw/meteorological/138154_55097.json
Saving info at: ../data/raw/meteorological/154105_37195.json
Saving info at: ../data/raw/meteorological/149912_26125.json
Saving info at: ../data/raw/meteorological/134608_42019.json
Saving info at: ../data/raw/meteorological/169556_06077.json
Saving info at: ../data/raw/meteorological/157080_48029.json
Saving info at: ../data/raw/meteorological/120460_47037.json
Saving info at: ../data/raw/meteorological/181333_40109.json
Saving info at: ../data/raw/meteorological/164819_15009.json
Saving info at: ../data/raw/meteorological/178023_55079.json
Saving info at: ../data/raw/meteorological/171798_13067.json
Saving info at: ../data/raw/meteorological/152384_36087.json
Saving info at: ../data/raw/meteorological/168513_48029.json
Saving info at: ../data/raw/meteorological/124954_39025.json
Saving info at: ../data/raw/meteorological/177661_32031.json
Saving info at: ../data/raw/meteorological/137519_51107.json
Saving info at: ../data/raw/meteorological/164097_26151.json
Saving info at: ../data/raw/meteorological/102310_06071.json
Saving info at: ../data/raw/meteorological/153516_46099.json
Saving info at: ../data/raw/meteorological/177029_06061.json
Saving info at: ../data/raw/meteorological/173856_48085.json
Saving info at: ../data/raw/meteorological/127944_04019.json
Saving info at: ../data/raw/meteorological/107517_13051.json
Saving info at: ../data/raw/meteorological/140548_37013.json
Saving info at: ../data/raw/meteorological/136142_40121.json
Saving info at: ../data/raw/meteorological/110001_51033.json
Saving info at: ../data/raw/meteorological/104592_25027.json
Saving info at: ../data/raw/meteorological/141220_48201.json
Saving info at: ../data/raw/meteorological/99650_06067.json
Saving info at: ../data/raw/meteorological/183905_48121.json
Saving info at: ../data/raw/meteorological/159944_06065.json
Saving info at: ../data/raw/meteorological/124410_01015.json
Saving info at: ../data/raw/meteorological/159944_06073.json
Saving info at: ../data/raw/meteorological/180221_17167.json
Saving info at: ../data/raw/meteorological/163687_36089.json
Saving info at: ../data/raw/meteorological/99760_24510.json
Saving info at: ../data/raw/meteorological/170873_51107.json
Saving info at: ../data/raw/meteorological/156415_48215.json
Saving info at: ../data/raw/meteorological/113515_13073.json
Saving info at: ../data/raw/meteorological/182432_05137.json
Saving info at: ../data/raw/meteorological/152427_25001.json
Saving info at: ../data/raw/meteorological/182640_42017.json
Saving info at: ../data/raw/meteorological/91886_54031.json
Saving info at: ../data/raw/meteorological/166766_50023.json
Saving info at: ../data/raw/meteorological/133650_42091.json
Saving info at: ../data/raw/meteorological/178509_36115.json
Saving info at: ../data/raw/meteorological/114107_42027.json
Saving info at: ../data/raw/meteorological/125667_36117.json
Saving info at: ../data/raw/meteorological/138794_42003.json
Saving info at: ../data/raw/meteorological/162202_04025.json
Saving info at: ../data/raw/meteorological/99962_34029.json
Saving info at: ../data/raw/meteorological/93964_25009.json
Saving info at: ../data/raw/meteorological/180218_17041.json
Saving info at: ../data/raw/meteorological/103526_26005.json
Saving info at: ../data/raw/meteorological/102383_41051.json
Saving info at: ../data/raw/meteorological/97151_13089.json
Saving info at: ../data/raw/meteorological/176366_37189.json
Saving info at: ../data/raw/meteorological/99672_29189.json
Saving info at: ../data/raw/meteorological/172577_48085.json
Saving info at: ../data/raw/meteorological/107732_06037.json
Saving info at: ../data/raw/meteorological/174880_06073.json
Saving info at: ../data/raw/meteorological/113729_06073.json
Saving info at: ../data/raw/meteorological/108810_36007.json
Saving info at: ../data/raw/meteorological/178652_48491.json
Saving info at: ../data/raw/meteorological/164182_12071.json
Saving info at: ../data/raw/meteorological/108735_51083.json
Saving info at: ../data/raw/meteorological/179878_48355.json
Saving info at: ../data/raw/meteorological/153650_28113.json
Saving info at: ../data/raw/meteorological/98227_40109.json
Saving info at: ../data/raw/meteorological/181654_36111.json
Saving info at: ../data/raw/meteorological/142071_37081.json
Saving info at: ../data/raw/meteorological/134216_49035.json
Saving info at: ../data/raw/meteorological/111172_45027.json
Saving info at: ../data/raw/meteorological/150211_42091.json
Saving info at: ../data/raw/meteorological/153709_48085.json
Saving info at: ../data/raw/meteorological/130067_17089.json
Saving info at: ../data/raw/meteorological/135197_39057.json
Saving info at: ../data/raw/meteorological/118781_37183.json
Saving info at: ../data/raw/meteorological/172729_48157.json
Saving info at: ../data/raw/meteorological/158707_48141.json
Saving info at: ../data/raw/meteorological/127401_24510.json
Saving info at: ../data/raw/meteorological/146171_23015.json
Saving info at: ../data/raw/meteorological/158926_48187.json
Saving info at: ../data/raw/meteorological/121504_13241.json
Saving info at: ../data/raw/meteorological/120533_37089.json
Saving info at: ../data/raw/meteorological/132199_51115.json
Saving info at: ../data/raw/meteorological/109367_48325.json
Saving info at: ../data/raw/meteorological/167488_05137.json
Saving info at: ../data/raw/meteorological/178637_20173.json
Saving info at: ../data/raw/meteorological/179239_30063.json
Saving info at: ../data/raw/meteorological/112807_27137.json
Saving info at: ../data/raw/meteorological/180900_26163.json
Saving info at: ../data/raw/meteorological/139835_26015.json
Done with saving.
Starting

Dask Apply:   0%|          | 0/41 [00:00<?, ?it/s]

/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)

time it took 788.0204542569991
Saving info at: ../data/raw/meteorological/93453_47031.json
Saving info at: ../data/raw/meteorological/131024_28059.json
Saving info at: ../data/raw/meteorological/110815_36055.json
Saving info at: ../data/raw/meteorological/151113_06073.json
Saving info at: ../data/raw/meteorological/170023_27035.json
Saving info at: ../data/raw/meteorological/130300_06071.json
Saving info at: ../data/raw/meteorological/149446_05119.json
Saving info at: ../data/raw/meteorological/93325_36055.json
Saving info at: ../data/raw/meteorological/105583_36033.json
Saving info at: ../data/raw/meteorological/130074_55001.json
Saving info at: ../data/raw/meteorological/132215_37149.json
Saving info at: ../data/raw/meteorological/187526_48401.json
Saving info at: ../data/raw/meteorological/122553_34005.json
Saving info at: ../data/raw/meteorological/153230_06063.json
Saving info at: ../data/raw/meteorological/130672_48085.json
Saving info at: ../data/raw/meteorological/98969_23031.json
Saving info at: ../data/raw/meteorological/168994_48365.json
Saving info at: ../data/raw/meteorological/169038_48439.json
Saving info at: ../data/raw/meteorological/153454_40075.json
Saving info at: ../data/raw/meteorological/131166_37063.json
Saving info at: ../data/raw/meteorological/186678_22071.json
Saving info at: ../data/raw/meteorological/164574_19153.json
Saving info at: ../data/raw/meteorological/95117_44007.json
Saving info at: ../data/raw/meteorological/120347_13171.json
Saving info at: ../data/raw/meteorological/149494_24025.json
Saving info at: ../data/raw/meteorological/115439_26147.json
Saving info at: ../data/raw/meteorological/126708_08031.json
Saving info at: ../data/raw/meteorological/159276_48249.json
Saving info at: ../data/raw/meteorological/140135_12099.json
Saving info at: ../data/raw/meteorological/167678_39049.json
Saving info at: ../data/raw/meteorological/148996_08123.json
Saving info at: ../data/raw/meteorological/153861_23005.json
Saving info at: ../data/raw/meteorological/131955_37167.json
Saving info at: ../data/raw/meteorological/172322_48139.json
Saving info at: ../data/raw/meteorological/161144_34003.json
Saving info at: ../data/raw/meteorological/185161_42077.json
Saving info at: ../data/raw/meteorological/185452_22071.json
Saving info at: ../data/raw/meteorological/105382_21065.json
Saving info at: ../data/raw/meteorological/102866_19153.json
Saving info at: ../data/raw/meteorological/127521_48469.json
Saving info at: ../data/raw/meteorological/104393_55133.json
Saving info at: ../data/raw/meteorological/119584_12065.json
Saving info at: ../data/raw/meteorological/163233_42079.json
Saving info at: ../data/raw/meteorological/117243_55013.json
Saving info at: ../data/raw/meteorological/127068_18005.json
Saving info at: ../data/raw/meteorological/171798_13135.json
Saving info at: ../data/raw/meteorological/175468_05119.json
Saving info at: ../data/raw/meteorological/124185_36071.json
Saving info at: ../data/raw/meteorological/183232_18077.json
Saving info at: ../data/raw/meteorological/171237_47113.json
Saving info at: ../data/raw/meteorological/184910_49005.json
Saving info at: ../data/raw/meteorological/90680_12031.json
Saving info at: ../data/raw/meteorological/133337_37151.json
Saving info at: ../data/raw/meteorological/184043_13291.json
Saving info at: ../data/raw/meteorological/184933_06071.json
Saving info at: ../data/raw/meteorological/107963_17183.json
Saving info at: ../data/raw/meteorological/114914_55101.json
Saving info at: ../data/raw/meteorological/178363_12009.json
Saving info at: ../data/raw/meteorological/183241_04015.json
Saving info at: ../data/raw/meteorological/131257_05093.json
Saving info at: ../data/raw/meteorological/144255_39123.json
Saving info at: ../data/raw/meteorological/158806_48039.json
Saving info at: ../data/raw/meteorological/178920_35037.json
Saving info at: ../data/raw/meteorological/150658_06053.json
Saving info at: ../data/raw/meteorological/178441_39157.json
Saving info at: ../data/raw/meteorological/130186_13177.json
Saving info at: ../data/raw/meteorological/186779_25023.json
Saving info at: ../data/raw/meteorological/102117_12099.json
Saving info at: ../data/raw/meteorological/140115_11001.json
Saving info at: ../data/raw/meteorological/109705_44007.json
Saving info at: ../data/raw/meteorological/129470_51047.json
Saving info at: ../data/raw/meteorological/164624_55079.json
Saving info at: ../data/raw/meteorological/96863_37063.json
Saving info at: ../data/raw/meteorological/96975_45051.json
Saving info at: ../data/raw/meteorological/169808_26017.json
Saving info at: ../data/raw/meteorological/103428_45045.json
Saving info at: ../data/raw/meteorological/182216_13051.json
Saving info at: ../data/raw/meteorological/158930_22019.json
Saving info at: ../data/raw/meteorological/174275_48453.json
Saving info at: ../data/raw/meteorological/175176_18097.json
Saving info at: ../data/raw/meteorological/156729_36027.json
Saving info at: ../data/raw/meteorological/149671_10003.json
Saving info at: ../data/raw/meteorological/115399_12031.json
Saving info at: ../data/raw/meteorological/162944_48005.json
Saving info at: ../data/raw/meteorological/186436_48099.json
Saving info at: ../data/raw/meteorological/139454_17097.json
Saving info at: ../data/raw/meteorological/156769_37081.json
Saving info at: ../data/raw/meteorological/148319_48449.json
Saving info at: ../data/raw/meteorological/182291_55001.json
Saving info at: ../data/raw/meteorological/92727_42017.json
Saving info at: ../data/raw/meteorological/172049_26081.json
Saving info at: ../data/raw/meteorological/153133_28021.json
Saving info at: ../data/raw/meteorological/170574_06037.json
Saving info at: ../data/raw/meteorological/146215_37129.json
Saving info at: ../data/raw/meteorological/125225_36035.json
Saving info at: ../data/raw/meteorological/148740_39143.json
Saving info at: ../data/raw/meteorological/98710_51019.json
Saving info at: ../data/raw/meteorological/146782_06071.json
Saving info at: ../data/raw/meteorological/159276_48007.json
Saving info at: ../data/raw/meteorological/111263_51810.json
Saving info at: ../data/raw/meteorological/111278_51550.json
Saving info at: ../data/raw/meteorological/155149_36087.json
Saving info at: ../data/raw/meteorological/159788_48039.json
Saving info at: ../data/raw/meteorological/133543_55101.json
Saving info at: ../data/raw/meteorological/108576_12115.json
Saving info at: ../data/raw/meteorological/178191_39061.json
Saving info at: ../data/raw/meteorological/163146_40111.json
Saving info at: ../data/raw/meteorological/146307_28043.json
Saving info at: ../data/raw/meteorological/122686_50027.json
Saving info at: ../data/raw/meteorological/117632_42049.json
Saving info at: ../data/raw/meteorological/170677_12057.json
Saving info at: ../data/raw/meteorological/149406_51510.json
Saving info at: ../data/raw/meteorological/180550_55079.json
Saving info at: ../data/raw/meteorological/146130_13077.json
Saving info at: ../data/raw/meteorological/122079_06071.json
Saving info at: ../data/raw/meteorological/106356_12127.json
Saving info at: ../data/raw/meteorological/151792_17133.json
Saving info at: ../data/raw/meteorological/147978_48029.json
Saving info at: ../data/raw/meteorological/166009_41051.json
Saving info at: ../data/raw/meteorological/131695_44007.json
Saving info at: ../data/raw/meteorological/154495_41033.json
Saving info at: ../data/raw/meteorological/110230_51087.json
Saving info at: ../data/raw/meteorological/146895_42125.json
Saving info at: ../data/raw/meteorological/171752_48439.json
Saving info at: ../data/raw/meteorological/161217_48039.json
Saving info at: ../data/raw/meteorological/113493_36043.json
Saving info at: ../data/raw/meteorological/143561_06111.json
Saving info at: ../data/raw/meteorological/142822_06073.json
Saving info at: ../data/raw/meteorological/184642_08001.json
Saving info at: ../data/raw/meteorological/153528_22011.json
Saving info at: ../data/raw/meteorological/151802_42063.json
Saving info at: ../data/raw/meteorological/113022_28085.json
Saving info at: ../data/raw/meteorological/134675_48201.json
Saving info at: ../data/raw/meteorological/154258_13111.json
Saving info at: ../data/raw/meteorological/150206_23031.json
Saving info at: ../data/raw/meteorological/151990_51650.json
Saving info at: ../data/raw/meteorological/158385_18089.json
Saving info at: ../data/raw/meteorological/128282_51003.json
Saving info at: ../data/raw/meteorological/130979_37013.json
Saving info at: ../data/raw/meteorological/142589_26161.json
Saving info at: ../data/raw/meteorological/180221_17021.json
Saving info at: ../data/raw/meteorological/143077_55009.json
Saving info at: ../data/raw/meteorological/177352_48139.json
Saving info at: ../data/raw/meteorological/100582_23019.json
Saving info at: ../data/raw/meteorological/91050_12057.json
Saving info at: ../data/raw/meteorological/150051_01097.json
Saving info at: ../data/raw/meteorological/135129_45057.json
Saving info at: ../data/raw/meteorological/166536_12001.json
Saving info at: ../data/raw/meteorological/175183_48439.json
Saving info at: ../data/raw/meteorological/133024_06037.json
Saving info at: ../data/raw/meteorological/99190_55133.json
Saving info at: ../data/raw/meteorological/142499_25007.json
Saving info at: ../data/raw/meteorological/100133_06083.json
Saving info at: ../data/raw/meteorological/186270_48359.json
Saving info at: ../data/raw/meteorological/116943_51650.json
Saving info at: ../data/raw/meteorological/175615_48113.json
Saving info at: ../data/raw/meteorological/91727_25015.json
Saving info at: ../data/raw/meteorological/186405_55067.json
Saving info at: ../data/raw/meteorological/132113_51147.json
Saving info at: ../data/raw/meteorological/173253_48491.json
Saving info at: ../data/raw/meteorological/130226_47157.json
Saving info at: ../data/raw/meteorological/164410_29021.json
Saving info at: ../data/raw/meteorological/105651_04021.json
Saving info at: ../data/raw/meteorological/106345_12057.json
Saving info at: ../data/raw/meteorological/162302_12133.json
Saving info at: ../data/raw/meteorological/184201_17201.json
Saving info at: ../data/raw/meteorological/105025_55125.json
Saving info at: ../data/raw/meteorological/168403_06073.json
Saving info at: ../data/raw/meteorological/164097_26093.json
Saving info at: ../data/raw/meteorological/182705_54107.json
Saving info at: ../data/raw/meteorological/183858_21067.json
Saving info at: ../data/raw/meteorological/126014_20073.json
Saving info at: ../data/raw/meteorological/112730_34029.json
Saving info at: ../data/raw/meteorological/186498_48491.json
Done with saving.
Starting

Dask Apply:   0%|          | 0/41 [00:00<?, ?it/s]

/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)

time it took 896.1116803470068
Saving info at: ../data/raw/meteorological/147536_01047.json
Saving info at: ../data/raw/meteorological/167604_48183.json
Saving info at: ../data/raw/meteorological/166613_48085.json
Saving info at: ../data/raw/meteorological/166900_22031.json
Saving info at: ../data/raw/meteorological/120285_06065.json
Saving info at: ../data/raw/meteorological/99639_29003.json
Saving info at: ../data/raw/meteorological/133024_06111.json
Saving info at: ../data/raw/meteorological/156653_48469.json
Saving info at: ../data/raw/meteorological/92654_48397.json
Saving info at: ../data/raw/meteorological/148496_18089.json
Saving info at: ../data/raw/meteorological/174831_48453.json
Saving info at: ../data/raw/meteorological/183473_24033.json
Saving info at: ../data/raw/meteorological/173069_13089.json
Saving info at: ../data/raw/meteorological/176783_39071.json
Saving info at: ../data/raw/meteorological/158067_06029.json
Saving info at: ../data/raw/meteorological/187595_13067.json
Saving info at: ../data/raw/meteorological/109192_34039.json
Saving info at: ../data/raw/meteorological/114321_22085.json
Saving info at: ../data/raw/meteorological/161328_55109.json
Saving info at: ../data/raw/meteorological/112504_13121.json
Saving info at: ../data/raw/meteorological/136630_48049.json
Saving info at: ../data/raw/meteorological/153297_41039.json
Saving info at: ../data/raw/meteorological/185191_48141.json
Saving info at: ../data/raw/meteorological/112444_12121.json
Saving info at: ../data/raw/meteorological/183370_55073.json
Saving info at: ../data/raw/meteorological/160576_48257.json
Saving info at: ../data/raw/meteorological/109428_48375.json
Saving info at: ../data/raw/meteorological/174918_06085.json
Saving info at: ../data/raw/meteorological/169640_48029.json
Saving info at: ../data/raw/meteorological/183612_48453.json
Saving info at: ../data/raw/meteorological/136210_42085.json
Saving info at: ../data/raw/meteorological/119584_12073.json
Saving info at: ../data/raw/meteorological/100507_19153.json
Saving info at: ../data/raw/meteorological/162917_24037.json
Saving info at: ../data/raw/meteorological/186673_48091.json
Saving info at: ../data/raw/meteorological/172729_48039.json
Saving info at: ../data/raw/meteorological/178191_39017.json
Saving info at: ../data/raw/meteorological/130631_04003.json
Saving info at: ../data/raw/meteorological/123111_48215.json
Saving info at: ../data/raw/meteorological/163701_18095.json
Saving info at: ../data/raw/meteorological/152282_37053.json
Saving info at: ../data/raw/meteorological/153553_01117.json
Saving info at: ../data/raw/meteorological/180547_06071.json
Saving info at: ../data/raw/meteorological/111278_51650.json
Saving info at: ../data/raw/meteorological/136629_17137.json
Saving info at: ../data/raw/meteorological/184049_13135.json
Saving info at: ../data/raw/meteorological/181617_01103.json
Saving info at: ../data/raw/meteorological/122206_48113.json
Saving info at: ../data/raw/meteorological/180073_22017.json
Saving info at: ../data/raw/meteorological/138005_05027.json
Saving info at: ../data/raw/meteorological/175102_55089.json
Saving info at: ../data/raw/meteorological/112539_13121.json
Saving info at: ../data/raw/meteorological/92170_10003.json
Saving info at: ../data/raw/meteorological/186547_01073.json
Saving info at: ../data/raw/meteorological/136492_12031.json
Saving info at: ../data/raw/meteorological/144846_39093.json
Saving info at: ../data/raw/meteorological/147394_48201.json
Saving info at: ../data/raw/meteorological/105596_39027.json
Saving info at: ../data/raw/meteorological/142671_34023.json
Saving info at: ../data/raw/meteorological/153679_42029.json
Saving info at: ../data/raw/meteorological/122689_54081.json
Saving info at: ../data/raw/meteorological/167070_48113.json
Saving info at: ../data/raw/meteorological/144200_12086.json
Saving info at: ../data/raw/meteorological/153851_37109.json
Saving info at: ../data/raw/meteorological/120347_13279.json
Saving info at: ../data/raw/meteorological/132672_51121.json
Saving info at: ../data/raw/meteorological/138605_48183.json
Saving info at: ../data/raw/meteorological/175191_39087.json
Saving info at: ../data/raw/meteorological/168538_54039.json
Saving info at: ../data/raw/meteorological/172719_33013.json
Saving info at: ../data/raw/meteorological/132582_48249.json
Saving info at: ../data/raw/meteorological/134769_10001.json
Saving info at: ../data/raw/meteorological/107071_36029.json
Saving info at: ../data/raw/meteorological/128183_17119.json
Saving info at: ../data/raw/meteorological/149810_13089.json
Saving info at: ../data/raw/meteorological/154181_22017.json
Saving info at: ../data/raw/meteorological/184459_12011.json
Saving info at: ../data/raw/meteorological/103818_36111.json
Saving info at: ../data/raw/meteorological/118714_04013.json
Saving info at: ../data/raw/meteorological/107378_42071.json
Saving info at: ../data/raw/meteorological/123655_15003.json
Saving info at: ../data/raw/meteorological/140637_22099.json
Saving info at: ../data/raw/meteorological/171442_42115.json
Saving info at: ../data/raw/meteorological/110417_51153.json
Saving info at: ../data/raw/meteorological/169093_51179.json
Saving info at: ../data/raw/meteorological/104206_36081.json
Saving info at: ../data/raw/meteorological/178330_06019.json
Saving info at: ../data/raw/meteorological/158562_54039.json
Saving info at: ../data/raw/meteorological/167112_12073.json
Saving info at: ../data/raw/meteorological/115365_05085.json
Saving info at: ../data/raw/meteorological/103945_12033.json
Saving info at: ../data/raw/meteorological/184125_04021.json
Saving info at: ../data/raw/meteorological/168863_21117.json
Saving info at: ../data/raw/meteorological/159512_36027.json
Saving info at: ../data/raw/meteorological/179618_12086.json
Saving info at: ../data/raw/meteorological/135643_28049.json
Saving info at: ../data/raw/meteorological/115658_10005.json
Saving info at: ../data/raw/meteorological/165339_49035.json
Saving info at: ../data/raw/meteorological/128290_37091.json
Saving info at: ../data/raw/meteorological/133371_37087.json
Saving info at: ../data/raw/meteorological/178183_48309.json
Saving info at: ../data/raw/meteorological/132148_36037.json
Saving info at: ../data/raw/meteorological/153713_48065.json
Saving info at: ../data/raw/meteorological/100753_06073.json
Saving info at: ../data/raw/meteorological/140378_39139.json
Saving info at: ../data/raw/meteorological/164083_06067.json
Saving info at: ../data/raw/meteorological/177895_47011.json
Saving info at: ../data/raw/meteorological/187097_12099.json
Saving info at: ../data/raw/meteorological/173232_48183.json
Saving info at: ../data/raw/meteorological/161965_39139.json
Saving info at: ../data/raw/meteorological/164904_17111.json
Saving info at: ../data/raw/meteorological/165315_39093.json
Saving info at: ../data/raw/meteorological/164082_06057.json
Saving info at: ../data/raw/meteorological/118788_48375.json
Saving info at: ../data/raw/meteorological/136880_01057.json
Saving info at: ../data/raw/meteorological/151062_40097.json
Saving info at: ../data/raw/meteorological/146318_42003.json
Saving info at: ../data/raw/meteorological/110815_36063.json
Saving info at: ../data/raw/meteorological/185382_37025.json
Saving info at: ../data/raw/meteorological/120347_13013.json
Saving info at: ../data/raw/meteorological/144697_18147.json
Saving info at: ../data/raw/meteorological/183164_27007.json
Saving info at: ../data/raw/meteorological/152460_33003.json
Saving info at: ../data/raw/meteorological/117467_05097.json
Saving info at: ../data/raw/meteorological/96719_29095.json
Saving info at: ../data/raw/meteorological/146711_48113.json
Saving info at: ../data/raw/meteorological/181327_40119.json
Saving info at: ../data/raw/meteorological/108298_39103.json
Saving info at: ../data/raw/meteorological/154803_29021.json
Saving info at: ../data/raw/meteorological/117701_55111.json
Saving info at: ../data/raw/meteorological/172634_37191.json
Saving info at: ../data/raw/meteorological/168795_40109.json
Saving info at: ../data/raw/meteorological/170379_48113.json
Saving info at: ../data/raw/meteorological/179014_27037.json
Saving info at: ../data/raw/meteorological/113468_25007.json
Saving info at: ../data/raw/meteorological/172877_04005.json
Saving info at: ../data/raw/meteorological/118778_37119.json
Saving info at: ../data/raw/meteorological/105020_12031.json
Saving info at: ../data/raw/meteorological/154385_36007.json
Saving info at: ../data/raw/meteorological/109814_05119.json
Saving info at: ../data/raw/meteorological/112845_29145.json
Saving info at: ../data/raw/meteorological/171279_37067.json
Saving info at: ../data/raw/meteorological/177681_40109.json
Saving info at: ../data/raw/meteorological/103672_25021.json
Saving info at: ../data/raw/meteorological/153851_37179.json
Saving info at: ../data/raw/meteorological/161265_04021.json
Saving info at: ../data/raw/meteorological/185623_40031.json
Saving info at: ../data/raw/meteorological/145830_47155.json
Saving info at: ../data/raw/meteorological/150528_04021.json
Saving info at: ../data/raw/meteorological/119635_26129.json
Saving info at: ../data/raw/meteorological/164648_06063.json
Saving info at: ../data/raw/meteorological/181606_36013.json
Saving info at: ../data/raw/meteorological/158908_12071.json
Saving info at: ../data/raw/meteorological/181889_24003.json
Saving info at: ../data/raw/meteorological/145415_48289.json
Saving info at: ../data/raw/meteorological/152280_51001.json
Saving info at: ../data/raw/meteorological/151952_06037.json
Saving info at: ../data/raw/meteorological/136479_06029.json
Saving info at: ../data/raw/meteorological/145575_46083.json
Saving info at: ../data/raw/meteorological/168619_36093.json
Saving info at: ../data/raw/meteorological/184733_04019.json
Saving info at: ../data/raw/meteorological/142465_42043.json
Saving info at: ../data/raw/meteorological/123625_20173.json
Saving info at: ../data/raw/meteorological/156223_48201.json
Saving info at: ../data/raw/meteorological/148297_48215.json
Saving info at: ../data/raw/meteorological/163701_18035.json
Saving info at: ../data/raw/meteorological/153250_06059.json
Saving info at: ../data/raw/meteorological/177450_06077.json
Saving info at: ../data/raw/meteorological/99903_12109.json
Saving info at: ../data/raw/meteorological/174642_12101.json
Saving info at: ../data/raw/meteorological/120347_13269.json
Saving info at: ../data/raw/meteorological/158782_12099.json
Saving info at: ../data/raw/meteorological/133032_06111.json
Saving info at: ../data/raw/meteorological/177397_06073.json
Saving info at: ../data/raw/meteorological/179014_27171.json
Saving info at: ../data/raw/meteorological/110718_51810.json
Saving info at: ../data/raw/meteorological/101265_06067.json
Saving info at: ../data/raw/meteorological/118235_41029.json
Saving info at: ../data/raw/meteorological/153665_34037.json
Saving info at: ../data/raw/meteorological/123486_51061.json
Saving info at: ../data/raw/meteorological/135034_26161.json
Saving info at: ../data/raw/meteorological/174699_36119.json
Saving info at: ../data/raw/meteorological/131071_42095.json
Saving info at: ../data/raw/meteorological/162858_26129.json
Saving info at: ../data/raw/meteorological/160428_25001.json
Saving info at: ../data/raw/meteorological/170606_06019.json
Saving info at: ../data/raw/meteorological/142638_12086.json
Saving info at: ../data/raw/meteorological/164104_06095.json
Saving info at: ../data/raw/meteorological/123915_26145.json
Saving info at: ../data/raw/meteorological/167275_36093.json
Saving info at: ../data/raw/meteorological/162302_12005.json
Saving info at: ../data/raw/meteorological/168248_24033.json
Saving info at: ../data/raw/meteorological/171675_48085.json
Saving info at: ../data/raw/meteorological/136923_51087.json
Saving info at: ../data/raw/meteorological/143288_48439.json
Saving info at: ../data/raw/meteorological/145964_25017.json
Saving info at: ../data/raw/meteorological/161552_45077.json
Saving info at: ../data/raw/meteorological/103930_25017.json
Saving info at: ../data/raw/meteorological/145900_21145.json
Saving info at: ../data/raw/meteorological/179447_28075.json
Saving info at: ../data/raw/meteorological/119417_40109.json
Saving info at: ../data/raw/meteorological/128331_37021.json
Done with saving.
Starting

Dask Apply:   0%|          | 0/41 [00:00<?, ?it/s]

/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)

time it took 823.1212541530113
Saving info at: ../data/raw/meteorological/147747_37097.json
Saving info at: ../data/raw/meteorological/127825_08001.json
Saving info at: ../data/raw/meteorological/134609_54061.json
Saving info at: ../data/raw/meteorological/164746_17119.json
Saving info at: ../data/raw/meteorological/183670_36071.json
Saving info at: ../data/raw/meteorological/92942_28043.json
Saving info at: ../data/raw/meteorological/126778_13057.json
Saving info at: ../data/raw/meteorological/104160_28047.json
Saving info at: ../data/raw/meteorological/95504_48113.json
Saving info at: ../data/raw/meteorological/147189_42101.json
Saving info at: ../data/raw/meteorological/134699_04007.json
Saving info at: ../data/raw/meteorological/105342_55069.json
Saving info at: ../data/raw/meteorological/178060_26005.json
Saving info at: ../data/raw/meteorological/151560_51133.json
Saving info at: ../data/raw/meteorological/143274_06019.json
Saving info at: ../data/raw/meteorological/176686_48499.json
Saving info at: ../data/raw/meteorological/147588_22005.json
Saving info at: ../data/raw/meteorological/103793_18127.json
Saving info at: ../data/raw/meteorological/132011_51077.json
Saving info at: ../data/raw/meteorological/157378_34041.json
Saving info at: ../data/raw/meteorological/171158_42091.json
Saving info at: ../data/raw/meteorological/119265_45085.json
Saving info at: ../data/raw/meteorological/171939_41033.json
Saving info at: ../data/raw/meteorological/179937_22071.json
Saving info at: ../data/raw/meteorological/156000_25017.json
Saving info at: ../data/raw/meteorological/100753_06071.json
Saving info at: ../data/raw/meteorological/131149_15003.json
Saving info at: ../data/raw/meteorological/180565_21059.json
Saving info at: ../data/raw/meteorological/156936_06065.json
Saving info at: ../data/raw/meteorological/182803_48491.json
Saving info at: ../data/raw/meteorological/153052_51041.json
Saving info at: ../data/raw/meteorological/109645_37037.json
Saving info at: ../data/raw/meteorological/172270_06073.json
Saving info at: ../data/raw/meteorological/131166_37183.json
Saving info at: ../data/raw/meteorological/147468_22033.json
Saving info at: ../data/raw/meteorological/154753_34029.json
Saving info at: ../data/raw/meteorological/169093_51171.json
Saving info at: ../data/raw/meteorological/128049_40149.json
Saving info at: ../data/raw/meteorological/127501_17031.json
Saving info at: ../data/raw/meteorological/145639_48183.json
Saving info at: ../data/raw/meteorological/165130_37057.json
Saving info at: ../data/raw/meteorological/95400_42011.json
Saving info at: ../data/raw/meteorological/177696_25023.json
Saving info at: ../data/raw/meteorological/127318_48485.json
Saving info at: ../data/raw/meteorological/143895_12086.json
Saving info at: ../data/raw/meteorological/154819_34027.json
Saving info at: ../data/raw/meteorological/159646_40109.json
Saving info at: ../data/raw/meteorological/152736_49005.json
Saving info at: ../data/raw/meteorological/163899_49005.json
Saving info at: ../data/raw/meteorological/135729_39035.json
Saving info at: ../data/raw/meteorological/170480_05145.json
Saving info at: ../data/raw/meteorological/162295_34025.json
Saving info at: ../data/raw/meteorological/151704_06071.json
Saving info at: ../data/raw/meteorological/159813_39035.json
Saving info at: ../data/raw/meteorological/181298_45019.json
Saving info at: ../data/raw/meteorological/171442_42131.json
Saving info at: ../data/raw/meteorological/172125_36111.json
Saving info at: ../data/raw/meteorological/119392_17099.json
Saving info at: ../data/raw/meteorological/159556_12023.json
Saving info at: ../data/raw/meteorological/180204_45079.json
Saving info at: ../data/raw/meteorological/118772_12117.json
Saving info at: ../data/raw/meteorological/118289_06093.json
Saving info at: ../data/raw/meteorological/168104_47105.json
Saving info at: ../data/raw/meteorological/177463_37119.json
Saving info at: ../data/raw/meteorological/155010_23017.json
Saving info at: ../data/raw/meteorological/125835_24017.json
Saving info at: ../data/raw/meteorological/177592_21177.json
Saving info at: ../data/raw/meteorological/131808_06075.json
Saving info at: ../data/raw/meteorological/186620_28075.json
Saving info at: ../data/raw/meteorological/156223_48015.json
Saving info at: ../data/raw/meteorological/153199_23015.json
Saving info at: ../data/raw/meteorological/116144_40041.json
Saving info at: ../data/raw/meteorological/152076_31055.json
Saving info at: ../data/raw/meteorological/163611_15009.json
Saving info at: ../data/raw/meteorological/183129_13089.json
Saving info at: ../data/raw/meteorological/146154_21161.json
Saving info at: ../data/raw/meteorological/99804_25027.json
Saving info at: ../data/raw/meteorological/99519_05093.json
Saving info at: ../data/raw/meteorological/146138_32003.json
Saving info at: ../data/raw/meteorological/104890_40033.json
Saving info at: ../data/raw/meteorological/162322_26125.json
Saving info at: ../data/raw/meteorological/171294_48491.json
Saving info at: ../data/raw/meteorological/168338_45057.json
Saving info at: ../data/raw/meteorological/127676_29165.json
Saving info at: ../data/raw/meteorological/160403_33001.json
Saving info at: ../data/raw/meteorological/184481_41033.json
Saving info at: ../data/raw/meteorological/166353_55085.json
Saving info at: ../data/raw/meteorological/141837_48499.json
Saving info at: ../data/raw/meteorological/112723_47037.json
Saving info at: ../data/raw/meteorological/152059_19015.json
Saving info at: ../data/raw/meteorological/110358_51179.json
Saving info at: ../data/raw/meteorological/173722_51041.json
Saving info at: ../data/raw/meteorological/141508_11001.json
Saving info at: ../data/raw/meteorological/150949_08005.json
Saving info at: ../data/raw/meteorological/168264_51177.json
Saving info at: ../data/raw/meteorological/142940_20091.json
Saving info at: ../data/raw/meteorological/182946_20091.json
Saving info at: ../data/raw/meteorological/145908_18173.json
Saving info at: ../data/raw/meteorological/179101_12099.json
Saving info at: ../data/raw/meteorological/158634_28075.json
Saving info at: ../data/raw/meteorological/99698_26161.json
Saving info at: ../data/raw/meteorological/134555_24510.json
Saving info at: ../data/raw/meteorological/185369_48201.json
Saving info at: ../data/raw/meteorological/172766_37021.json
Saving info at: ../data/raw/meteorological/160640_26005.json
Saving info at: ../data/raw/meteorological/112122_01089.json
Saving info at: ../data/raw/meteorological/120790_36119.json
Saving info at: ../data/raw/meteorological/164455_04021.json
Saving info at: ../data/raw/meteorological/134073_48113.json
Saving info at: ../data/raw/meteorological/132113_51730.json
Saving info at: ../data/raw/meteorological/106365_29031.json
Saving info at: ../data/raw/meteorological/173069_13121.json
Saving info at: ../data/raw/meteorological/117157_13089.json
Saving info at: ../data/raw/meteorological/162686_45045.json
Saving info at: ../data/raw/meteorological/151791_29113.json
Saving info at: ../data/raw/meteorological/146904_47035.json
Saving info at: ../data/raw/meteorological/102057_34007.json
Saving info at: ../data/raw/meteorological/121050_23013.json
Saving info at: ../data/raw/meteorological/178226_06083.json
Saving info at: ../data/raw/meteorological/181466_48029.json
Saving info at: ../data/raw/meteorological/93891_48121.json
Saving info at: ../data/raw/meteorological/175840_23001.json
Saving info at: ../data/raw/meteorological/139569_13085.json
Saving info at: ../data/raw/meteorological/185294_41039.json
Saving info at: ../data/raw/meteorological/119753_48373.json
Saving info at: ../data/raw/meteorological/109696_36103.json
Saving info at: ../data/raw/meteorological/175102_55131.json
Saving info at: ../data/raw/meteorological/91606_48439.json
Saving info at: ../data/raw/meteorological/181487_48439.json
Saving info at: ../data/raw/meteorological/153230_06067.json
Saving info at: ../data/raw/meteorological/117044_34007.json
Saving info at: ../data/raw/meteorological/146034_48201.json
Saving info at: ../data/raw/meteorological/147470_22079.json
Saving info at: ../data/raw/meteorological/129526_48449.json
Saving info at: ../data/raw/meteorological/172488_48035.json
Saving info at: ../data/raw/meteorological/174626_32003.json
Saving info at: ../data/raw/meteorological/131249_22043.json
Saving info at: ../data/raw/meteorological/157275_13045.json
Saving info at: ../data/raw/meteorological/113493_36111.json
Saving info at: ../data/raw/meteorological/173918_48139.json
Saving info at: ../data/raw/meteorological/183079_15009.json
Saving info at: ../data/raw/meteorological/167076_39057.json
Saving info at: ../data/raw/meteorological/161280_26107.json
Saving info at: ../data/raw/meteorological/127493_26081.json
Saving info at: ../data/raw/meteorological/142405_29183.json
Saving info at: ../data/raw/meteorological/154466_33011.json
Saving info at: ../data/raw/meteorological/164083_06089.json
Saving info at: ../data/raw/meteorological/134511_06065.json
Saving info at: ../data/raw/meteorological/103258_06067.json
Saving info at: ../data/raw/meteorological/186551_48061.json
Saving info at: ../data/raw/meteorological/150888_04013.json
Saving info at: ../data/raw/meteorological/120361_17031.json
Saving info at: ../data/raw/meteorological/146748_55083.json
Saving info at: ../data/raw/meteorological/114730_17031.json
Saving info at: ../data/raw/meteorological/112615_13067.json
Saving info at: ../data/raw/meteorological/147100_41059.json
Saving info at: ../data/raw/meteorological/150445_26011.json
Saving info at: ../data/raw/meteorological/148592_29077.json
Saving info at: ../data/raw/meteorological/146171_23013.json
Saving info at: ../data/raw/meteorological/107556_06059.json
Saving info at: ../data/raw/meteorological/183904_48439.json
Saving info at: ../data/raw/meteorological/172537_48315.json
Saving info at: ../data/raw/meteorological/160980_48453.json
Saving info at: ../data/raw/meteorological/128176_01123.json
Saving info at: ../data/raw/meteorological/179396_48041.json
Saving info at: ../data/raw/meteorological/133650_42011.json
Saving info at: ../data/raw/meteorological/148749_45045.json
Saving info at: ../data/raw/meteorological/155391_06037.json
Saving info at: ../data/raw/meteorological/123912_39027.json
Saving info at: ../data/raw/meteorological/166579_06037.json
Saving info at: ../data/raw/meteorological/175132_50021.json
Saving info at: ../data/raw/meteorological/138587_42029.json
Saving info at: ../data/raw/meteorological/164782_20041.json
Saving info at: ../data/raw/meteorological/182298_21061.json
Saving info at: ../data/raw/meteorological/170141_26137.json
Saving info at: ../data/raw/meteorological/146747_39049.json
Saving info at: ../data/raw/meteorological/185528_04019.json
Saving info at: ../data/raw/meteorological/109820_39167.json
Saving info at: ../data/raw/meteorological/124414_51107.json
Saving info at: ../data/raw/meteorological/172745_40143.json
Saving info at: ../data/raw/meteorological/139539_37053.json
Saving info at: ../data/raw/meteorological/157390_39089.json
Saving info at: ../data/raw/meteorological/183612_48029.json
Done with saving.
Starting

Dask Apply:   0%|          | 0/41 [00:00<?, ?it/s]

/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)

time it took 817.1956806829985
Saving info at: ../data/raw/meteorological/151861_17095.json
Saving info at: ../data/raw/meteorological/155121_25009.json
Saving info at: ../data/raw/meteorological/146151_37077.json
Saving info at: ../data/raw/meteorological/170606_06029.json
Saving info at: ../data/raw/meteorological/153859_51143.json
Saving info at: ../data/raw/meteorological/164957_51099.json
Saving info at: ../data/raw/meteorological/171377_51141.json
Saving info at: ../data/raw/meteorological/118640_55045.json
Saving info at: ../data/raw/meteorological/156251_48157.json
Saving info at: ../data/raw/meteorological/162054_08005.json
Saving info at: ../data/raw/meteorological/170937_55025.json
Saving info at: ../data/raw/meteorological/153663_22075.json
Saving info at: ../data/raw/meteorological/100549_24510.json
Saving info at: ../data/raw/meteorological/179086_33015.json
Saving info at: ../data/raw/meteorological/151082_13089.json
Saving info at: ../data/raw/meteorological/132686_40031.json
Saving info at: ../data/raw/meteorological/144289_48201.json
Saving info at: ../data/raw/meteorological/159969_55063.json
Saving info at: ../data/raw/meteorological/170775_24043.json
Saving info at: ../data/raw/meteorological/130716_51089.json
Saving info at: ../data/raw/meteorological/180564_18051.json
Saving info at: ../data/raw/meteorological/179175_34021.json
Saving info at: ../data/raw/meteorological/183129_13059.json
Saving info at: ../data/raw/meteorological/186569_33015.json
Saving info at: ../data/raw/meteorological/122362_42133.json
Saving info at: ../data/raw/meteorological/130185_12131.json
Saving info at: ../data/raw/meteorological/156276_51031.json
Saving info at: ../data/raw/meteorological/139574_36011.json
Saving info at: ../data/raw/meteorological/100747_06073.json
Saving info at: ../data/raw/meteorological/185248_16001.json
Saving info at: ../data/raw/meteorological/177695_05103.json
Saving info at: ../data/raw/meteorological/182772_18055.json
Saving info at: ../data/raw/meteorological/175774_05131.json
Saving info at: ../data/raw/meteorological/108896_42011.json
Saving info at: ../data/raw/meteorological/138071_48133.json
Saving info at: ../data/raw/meteorological/175536_23007.json
Saving info at: ../data/raw/meteorological/160578_39099.json
Saving info at: ../data/raw/meteorological/109263_36059.json
Saving info at: ../data/raw/meteorological/127705_29165.json
Saving info at: ../data/raw/meteorological/159618_42133.json
Saving info at: ../data/raw/meteorological/93942_48073.json
Saving info at: ../data/raw/meteorological/182570_45079.json
Saving info at: ../data/raw/meteorological/154672_06085.json
Saving info at: ../data/raw/meteorological/141545_51810.json
Saving info at: ../data/raw/meteorological/150363_17201.json
Saving info at: ../data/raw/meteorological/175897_12099.json
Saving info at: ../data/raw/meteorological/157378_34029.json
Saving info at: ../data/raw/meteorological/141002_21111.json
Saving info at: ../data/raw/meteorological/178427_39095.json
Saving info at: ../data/raw/meteorological/132524_47073.json
Saving info at: ../data/raw/meteorological/112615_13121.json
Saving info at: ../data/raw/meteorological/143807_25027.json
Saving info at: ../data/raw/meteorological/149215_34029.json
Saving info at: ../data/raw/meteorological/133969_20121.json
Saving info at: ../data/raw/meteorological/123243_23031.json
Saving info at: ../data/raw/meteorological/133137_48245.json
Saving info at: ../data/raw/meteorological/173010_48209.json
Saving info at: ../data/raw/meteorological/168743_53055.json
Saving info at: ../data/raw/meteorological/167822_21093.json
Saving info at: ../data/raw/meteorological/120347_13159.json
Saving info at: ../data/raw/meteorological/150595_34003.json
Saving info at: ../data/raw/meteorological/100334_22069.json
Saving info at: ../data/raw/meteorological/153345_08005.json
Saving info at: ../data/raw/meteorological/167967_48355.json
Saving info at: ../data/raw/meteorological/138897_55087.json
Saving info at: ../data/raw/meteorological/170027_48469.json
Saving info at: ../data/raw/meteorological/171453_23011.json
Saving info at: ../data/raw/meteorological/142888_37129.json
Saving info at: ../data/raw/meteorological/127362_04021.json
Saving info at: ../data/raw/meteorological/152434_48245.json
Saving info at: ../data/raw/meteorological/127903_42011.json
Saving info at: ../data/raw/meteorological/181271_27025.json
Saving info at: ../data/raw/meteorological/182167_40109.json
Saving info at: ../data/raw/meteorological/182808_18105.json
Saving info at: ../data/raw/meteorological/163723_36075.json
Saving info at: ../data/raw/meteorological/182947_29177.json
Saving info at: ../data/raw/meteorological/153250_06065.json
Saving info at: ../data/raw/meteorological/184513_19155.json
Saving info at: ../data/raw/meteorological/121858_28129.json
Saving info at: ../data/raw/meteorological/96188_42091.json
Saving info at: ../data/raw/meteorological/126268_29031.json
Saving info at: ../data/raw/meteorological/115292_26105.json
Saving info at: ../data/raw/meteorological/148405_36115.json
Saving info at: ../data/raw/meteorological/131689_37071.json
Saving info at: ../data/raw/meteorological/186004_48423.json
Saving info at: ../data/raw/meteorological/181070_27003.json
Saving info at: ../data/raw/meteorological/131454_20045.json
Saving info at: ../data/raw/meteorological/167388_34003.json
Saving info at: ../data/raw/meteorological/139316_01101.json
Saving info at: ../data/raw/meteorological/100009_55087.json
Saving info at: ../data/raw/meteorological/99606_10003.json
Saving info at: ../data/raw/meteorological/147190_34021.json
Saving info at: ../data/raw/meteorological/117157_13015.json
Saving info at: ../data/raw/meteorological/91638_39153.json
Saving info at: ../data/raw/meteorological/135072_39095.json
Saving info at: ../data/raw/meteorological/141330_12073.json
Saving info at: ../data/raw/meteorological/115313_12031.json
Saving info at: ../data/raw/meteorological/171774_51173.json
Saving info at: ../data/raw/meteorological/184245_04025.json
Saving info at: ../data/raw/meteorological/180756_20209.json
Saving info at: ../data/raw/meteorological/150003_39035.json
Saving info at: ../data/raw/meteorological/157994_21015.json
Saving info at: ../data/raw/meteorological/126525_01073.json
Saving info at: ../data/raw/meteorological/182690_12091.json
Saving info at: ../data/raw/meteorological/116463_22097.json
Saving info at: ../data/raw/meteorological/158304_50027.json
Saving info at: ../data/raw/meteorological/113249_36013.json
Saving info at: ../data/raw/meteorological/141118_45083.json
Saving info at: ../data/raw/meteorological/138452_22015.json
Saving info at: ../data/raw/meteorological/178226_06037.json
Saving info at: ../data/raw/meteorological/171002_48315.json
Saving info at: ../data/raw/meteorological/137746_29183.json
Saving info at: ../data/raw/meteorological/139155_39155.json
Saving info at: ../data/raw/meteorological/138650_18105.json
Saving info at: ../data/raw/meteorological/115944_25017.json
Saving info at: ../data/raw/meteorological/145154_01111.json
Saving info at: ../data/raw/meteorological/122423_42011.json
Saving info at: ../data/raw/meteorological/151081_13057.json
Saving info at: ../data/raw/meteorological/134872_12017.json
Saving info at: ../data/raw/meteorological/161629_04013.json
Saving info at: ../data/raw/meteorological/180559_37049.json
Saving info at: ../data/raw/meteorological/133020_06085.json
Saving info at: ../data/raw/meteorological/136359_51810.json
Saving info at: ../data/raw/meteorological/115640_42083.json
Saving info at: ../data/raw/meteorological/127225_12031.json
Saving info at: ../data/raw/meteorological/177702_24015.json
Saving info at: ../data/raw/meteorological/181057_22049.json
Saving info at: ../data/raw/meteorological/171114_01073.json
Saving info at: ../data/raw/meteorological/175193_06019.json
Saving info at: ../data/raw/meteorological/134401_06071.json
Saving info at: ../data/raw/meteorological/182207_42133.json
Saving info at: ../data/raw/meteorological/178208_41015.json
Saving info at: ../data/raw/meteorological/143490_44007.json
Saving info at: ../data/raw/meteorological/181273_27067.json
Saving info at: ../data/raw/meteorological/106595_18097.json
Saving info at: ../data/raw/meteorological/158208_39129.json
Saving info at: ../data/raw/meteorological/172900_48097.json
Saving info at: ../data/raw/meteorological/122641_36087.json
Saving info at: ../data/raw/meteorological/110782_51041.json
Saving info at: ../data/raw/meteorological/151240_37193.json
Saving info at: ../data/raw/meteorological/113114_45063.json
Saving info at: ../data/raw/meteorological/165590_54039.json
Saving info at: ../data/raw/meteorological/102630_51095.json
Saving info at: ../data/raw/meteorological/162724_39051.json
Saving info at: ../data/raw/meteorological/176742_47049.json
Saving info at: ../data/raw/meteorological/179516_48215.json
Saving info at: ../data/raw/meteorological/137266_22073.json
Saving info at: ../data/raw/meteorological/174194_37155.json
Saving info at: ../data/raw/meteorological/153471_30057.json
Saving info at: ../data/raw/meteorological/128366_27037.json
Saving info at: ../data/raw/meteorological/153664_28059.json
Saving info at: ../data/raw/meteorological/112682_54047.json
Saving info at: ../data/raw/meteorological/136880_01117.json
Saving info at: ../data/raw/meteorological/188705_39123.json
Saving info at: ../data/raw/meteorological/146318_42019.json
Saving info at: ../data/raw/meteorological/157671_48303.json
Saving info at: ../data/raw/meteorological/119140_17177.json
Saving info at: ../data/raw/meteorological/111172_45063.json
Saving info at: ../data/raw/meteorological/182053_48161.json
Saving info at: ../data/raw/meteorological/176407_37109.json
Saving info at: ../data/raw/meteorological/171587_06057.json
Saving info at: ../data/raw/meteorological/116398_50003.json
Saving info at: ../data/raw/meteorological/184145_34023.json
Saving info at: ../data/raw/meteorological/136732_37135.json
Saving info at: ../data/raw/meteorological/135635_48423.json
Saving info at: ../data/raw/meteorological/187410_36087.json
Saving info at: ../data/raw/meteorological/152230_06071.json
Saving info at: ../data/raw/meteorological/179804_17111.json
Saving info at: ../data/raw/meteorological/112766_21187.json
Saving info at: ../data/raw/meteorological/147589_37057.json
Saving info at: ../data/raw/meteorological/150658_06085.json
Saving info at: ../data/raw/meteorological/168667_12087.json
Saving info at: ../data/raw/meteorological/168122_56033.json
Saving info at: ../data/raw/meteorological/161618_32003.json
Saving info at: ../data/raw/meteorological/159172_13097.json
Saving info at: ../data/raw/meteorological/164955_26005.json
Saving info at: ../data/raw/meteorological/166194_37129.json
Saving info at: ../data/raw/meteorological/152995_48303.json
Saving info at: ../data/raw/meteorological/124244_48355.json
Saving info at: ../data/raw/meteorological/184652_10005.json
Saving info at: ../data/raw/meteorological/116111_22041.json
Saving info at: ../data/raw/meteorological/186486_48085.json
Saving info at: ../data/raw/meteorological/170831_45045.json
Saving info at: ../data/raw/meteorological/121837_37089.json
Saving info at: ../data/raw/meteorological/165468_40017.json
Saving info at: ../data/raw/meteorological/182630_48401.json
Saving info at: ../data/raw/meteorological/126923_51087.json
Saving info at: ../data/raw/meteorological/101580_22051.json
Done with saving.
Starting

Dask Apply:   0%|          | 0/41 [00:00<?, ?it/s]

/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)

time it took 824.3083102170058
Saving info at: ../data/raw/meteorological/156171_51111.json
Saving info at: ../data/raw/meteorological/167457_48171.json
Saving info at: ../data/raw/meteorological/106950_55007.json
Saving info at: ../data/raw/meteorological/125544_36043.json
Saving info at: ../data/raw/meteorological/163613_06077.json
Saving info at: ../data/raw/meteorological/186168_22007.json
Saving info at: ../data/raw/meteorological/150751_36091.json
Saving info at: ../data/raw/meteorological/169797_36043.json
Saving info at: ../data/raw/meteorological/154424_42129.json
Saving info at: ../data/raw/meteorological/179926_18105.json
Saving info at: ../data/raw/meteorological/141581_40027.json
Saving info at: ../data/raw/meteorological/166312_12103.json
Saving info at: ../data/raw/meteorological/148866_47053.json
Saving info at: ../data/raw/meteorological/182189_40047.json
Saving info at: ../data/raw/meteorological/118772_12009.json
Saving info at: ../data/raw/meteorological/163037_06019.json
Saving info at: ../data/raw/meteorological/154073_39095.json
Saving info at: ../data/raw/meteorological/156923_45055.json
Saving info at: ../data/raw/meteorological/177506_41007.json
Saving info at: ../data/raw/meteorological/177854_39155.json
Saving info at: ../data/raw/meteorological/104264_26123.json
Saving info at: ../data/raw/meteorological/175321_25005.json
Saving info at: ../data/raw/meteorological/162782_49057.json
Saving info at: ../data/raw/meteorological/152750_48049.json
Saving info at: ../data/raw/meteorological/175436_22073.json
Saving info at: ../data/raw/meteorological/180197_13169.json
Saving info at: ../data/raw/meteorological/180670_40017.json
Saving info at: ../data/raw/meteorological/114040_18019.json
Saving info at: ../data/raw/meteorological/123199_42087.json
Saving info at: ../data/raw/meteorological/123199_42041.json
Saving info at: ../data/raw/meteorological/133275_06053.json
Saving info at: ../data/raw/meteorological/166189_22073.json
Saving info at: ../data/raw/meteorological/157283_48029.json
Saving info at: ../data/raw/meteorological/131655_13175.json
Saving info at: ../data/raw/meteorological/129269_37001.json
Saving info at: ../data/raw/meteorological/187073_48439.json
Saving info at: ../data/raw/meteorological/180767_37135.json
Saving info at: ../data/raw/meteorological/185473_22007.json
Saving info at: ../data/raw/meteorological/140921_26093.json
Saving info at: ../data/raw/meteorological/104890_40137.json
Saving info at: ../data/raw/meteorological/152231_06071.json
Saving info at: ../data/raw/meteorological/175535_33015.json
Saving info at: ../data/raw/meteorological/186141_48113.json
Saving info at: ../data/raw/meteorological/185927_48085.json
Saving info at: ../data/raw/meteorological/95212_22003.json
Saving info at: ../data/raw/meteorological/152460_33009.json
Saving info at: ../data/raw/meteorological/161581_04019.json
Saving info at: ../data/raw/meteorological/152201_36105.json
Saving info at: ../data/raw/meteorological/92963_48325.json
Saving info at: ../data/raw/meteorological/115139_17157.json
Saving info at: ../data/raw/meteorological/142645_42029.json
Saving info at: ../data/raw/meteorological/113471_44003.json
Saving info at: ../data/raw/meteorological/153635_32003.json
Saving info at: ../data/raw/meteorological/148533_39017.json
Saving info at: ../data/raw/meteorological/176128_06067.json
Saving info at: ../data/raw/meteorological/186163_22105.json
Saving info at: ../data/raw/meteorological/93460_45003.json
Saving info at: ../data/raw/meteorological/143510_24021.json
Saving info at: ../data/raw/meteorological/145411_48439.json
Saving info at: ../data/raw/meteorological/97980_37033.json
Saving info at: ../data/raw/meteorological/103861_34003.json
Saving info at: ../data/raw/meteorological/93491_24021.json
Saving info at: ../data/raw/meteorological/182589_26115.json
Saving info at: ../data/raw/meteorological/148826_29095.json
Saving info at: ../data/raw/meteorological/135534_13135.json
Saving info at: ../data/raw/meteorological/164367_20051.json
Saving info at: ../data/raw/meteorological/103208_45069.json
Saving info at: ../data/raw/meteorological/147122_25021.json
Saving info at: ../data/raw/meteorological/171774_51680.json
Saving info at: ../data/raw/meteorological/107439_24031.json
Saving info at: ../data/raw/meteorological/176366_37193.json
Saving info at: ../data/raw/meteorological/99659_29095.json
Saving info at: ../data/raw/meteorological/160393_25021.json
Saving info at: ../data/raw/meteorological/151246_04021.json
Saving info at: ../data/raw/meteorological/133780_25017.json
Saving info at: ../data/raw/meteorological/185670_19153.json
Saving info at: ../data/raw/meteorological/182167_40039.json
Saving info at: ../data/raw/meteorological/184040_12031.json
Saving info at: ../data/raw/meteorological/154180_30049.json
Saving info at: ../data/raw/meteorological/168999_48183.json
Saving info at: ../data/raw/meteorological/155828_08069.json
Saving info at: ../data/raw/meteorological/156330_28079.json
Saving info at: ../data/raw/meteorological/169832_08119.json
Saving info at: ../data/raw/meteorological/175064_01101.json
Saving info at: ../data/raw/meteorological/165811_12061.json
Saving info at: ../data/raw/meteorological/100296_34025.json
Saving info at: ../data/raw/meteorological/177403_06073.json
Saving info at: ../data/raw/meteorological/142187_12105.json
Saving info at: ../data/raw/meteorological/161616_04015.json
Saving info at: ../data/raw/meteorological/121897_45083.json
Saving info at: ../data/raw/meteorological/140231_24510.json
Saving info at: ../data/raw/meteorological/177122_29225.json
Saving info at: ../data/raw/meteorological/108104_32003.json
Saving info at: ../data/raw/meteorological/142527_48029.json
Saving info at: ../data/raw/meteorological/114153_33015.json
Saving info at: ../data/raw/meteorological/165720_02122.json
Saving info at: ../data/raw/meteorological/116144_40101.json
Saving info at: ../data/raw/meteorological/158066_06019.json
Saving info at: ../data/raw/meteorological/133553_41047.json
Saving info at: ../data/raw/meteorological/174699_36081.json
Saving info at: ../data/raw/meteorological/174597_37123.json
Saving info at: ../data/raw/meteorological/131199_01097.json
Saving info at: ../data/raw/meteorological/140125_24031.json
Saving info at: ../data/raw/meteorological/156955_36101.json
Saving info at: ../data/raw/meteorological/178719_48367.json
Saving info at: ../data/raw/meteorological/137246_40143.json
Saving info at: ../data/raw/meteorological/171146_06107.json
Saving info at: ../data/raw/meteorological/90680_12019.json
Saving info at: ../data/raw/meteorological/162858_26055.json
Saving info at: ../data/raw/meteorological/177098_48085.json
Saving info at: ../data/raw/meteorological/150588_36103.json
Saving info at: ../data/raw/meteorological/114340_36071.json
Saving info at: ../data/raw/meteorological/176690_06033.json
Saving info at: ../data/raw/meteorological/103539_23021.json
Saving info at: ../data/raw/meteorological/171752_48039.json
Saving info at: ../data/raw/meteorological/155586_18059.json
Saving info at: ../data/raw/meteorological/103672_25005.json
Saving info at: ../data/raw/meteorological/94668_12071.json
Saving info at: ../data/raw/meteorological/160989_34015.json
Saving info at: ../data/raw/meteorological/185117_48209.json
Saving info at: ../data/raw/meteorological/96744_51087.json
Saving info at: ../data/raw/meteorological/180169_24003.json
Saving info at: ../data/raw/meteorological/131388_33017.json
Saving info at: ../data/raw/meteorological/118768_37179.json
Saving info at: ../data/raw/meteorological/186886_36059.json
Saving info at: ../data/raw/meteorological/109149_34039.json
Saving info at: ../data/raw/meteorological/164717_19129.json
Saving info at: ../data/raw/meteorological/101037_06067.json
Saving info at: ../data/raw/meteorological/156244_48141.json
Saving info at: ../data/raw/meteorological/100298_36075.json
Saving info at: ../data/raw/meteorological/155460_27139.json
Saving info at: ../data/raw/meteorological/166105_47157.json
Saving info at: ../data/raw/meteorological/106098_22033.json
Saving info at: ../data/raw/meteorological/136920_51700.json
Saving info at: ../data/raw/meteorological/142645_42091.json
Saving info at: ../data/raw/meteorological/152516_51550.json
Saving info at: ../data/raw/meteorological/121066_26065.json
Saving info at: ../data/raw/meteorological/110811_36063.json
Saving info at: ../data/raw/meteorological/162770_36029.json
Saving info at: ../data/raw/meteorological/101324_26063.json
Saving info at: ../data/raw/meteorological/151991_37015.json
Saving info at: ../data/raw/meteorological/164287_26097.json
Saving info at: ../data/raw/meteorological/171178_40109.json
Saving info at: ../data/raw/meteorological/158047_39113.json
Saving info at: ../data/raw/meteorological/130980_42091.json
Saving info at: ../data/raw/meteorological/156223_48225.json
Saving info at: ../data/raw/meteorological/118093_51041.json
Saving info at: ../data/raw/meteorological/156949_36027.json
Saving info at: ../data/raw/meteorological/151854_18141.json
Saving info at: ../data/raw/meteorological/168926_24017.json
Saving info at: ../data/raw/meteorological/150148_42017.json
Saving info at: ../data/raw/meteorological/126773_42029.json
Saving info at: ../data/raw/meteorological/154748_42077.json
Saving info at: ../data/raw/meteorological/108888_34027.json
Saving info at: ../data/raw/meteorological/140826_05085.json
Saving info at: ../data/raw/meteorological/166194_37019.json
Saving info at: ../data/raw/meteorological/158385_18127.json
Saving info at: ../data/raw/meteorological/172051_06067.json
Saving info at: ../data/raw/meteorological/94788_48409.json
Saving info at: ../data/raw/meteorological/142213_36055.json
Saving info at: ../data/raw/meteorological/135905_48135.json
Saving info at: ../data/raw/meteorological/117282_54033.json
Saving info at: ../data/raw/meteorological/125162_40009.json
Saving info at: ../data/raw/meteorological/177459_06037.json
Saving info at: ../data/raw/meteorological/143358_48325.json
Saving info at: ../data/raw/meteorological/175252_06107.json
Saving info at: ../data/raw/meteorological/93317_42003.json
Saving info at: ../data/raw/meteorological/133456_53035.json
Saving info at: ../data/raw/meteorological/183773_51087.json
Saving info at: ../data/raw/meteorological/95406_48325.json
Saving info at: ../data/raw/meteorological/140548_37187.json
Saving info at: ../data/raw/meteorological/146560_05105.json
Saving info at: ../data/raw/meteorological/179474_29175.json
Saving info at: ../data/raw/meteorological/165236_39073.json
Saving info at: ../data/raw/meteorological/151895_21111.json
Saving info at: ../data/raw/meteorological/159970_17111.json
Saving info at: ../data/raw/meteorological/147536_01051.json
Saving info at: ../data/raw/meteorological/163583_44009.json
Saving info at: ../data/raw/meteorological/106499_27021.json
Saving info at: ../data/raw/meteorological/178741_21027.json
Done with saving.
Starting

Dask Apply:   0%|          | 0/41 [00:00<?, ?it/s]

/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)

time it took 928.815918156004
Saving info at: ../data/raw/meteorological/149215_34009.json
Saving info at: ../data/raw/meteorological/124529_19105.json
Saving info at: ../data/raw/meteorological/99256_34025.json
Saving info at: ../data/raw/meteorological/162858_26089.json
Saving info at: ../data/raw/meteorological/152899_55127.json
Saving info at: ../data/raw/meteorological/172285_08101.json
Saving info at: ../data/raw/meteorological/153668_42091.json
Saving info at: ../data/raw/meteorological/131655_13261.json
Saving info at: ../data/raw/meteorological/135389_48375.json
Saving info at: ../data/raw/meteorological/131618_12086.json
Saving info at: ../data/raw/meteorological/95795_22017.json
Saving info at: ../data/raw/meteorological/135643_28089.json
Saving info at: ../data/raw/meteorological/160526_13135.json
Saving info at: ../data/raw/meteorological/148305_48355.json
Saving info at: ../data/raw/meteorological/108301_22073.json
Saving info at: ../data/raw/meteorological/148477_37007.json
Saving info at: ../data/raw/meteorological/130657_55131.json
Saving info at: ../data/raw/meteorological/101085_08014.json
Saving info at: ../data/raw/meteorological/134892_48113.json
Saving info at: ../data/raw/meteorological/135416_45053.json
Saving info at: ../data/raw/meteorological/185154_48113.json
Saving info at: ../data/raw/meteorological/100225_25023.json
Saving info at: ../data/raw/meteorological/143391_36113.json
Saving info at: ../data/raw/meteorological/106098_22005.json
Saving info at: ../data/raw/meteorological/150724_51153.json
Saving info at: ../data/raw/meteorological/180708_05051.json
Saving info at: ../data/raw/meteorological/170373_12086.json
Saving info at: ../data/raw/meteorological/169392_24031.json
Saving info at: ../data/raw/meteorological/179086_33001.json
Saving info at: ../data/raw/meteorological/185807_48491.json
Saving info at: ../data/raw/meteorological/117248_10003.json
Saving info at: ../data/raw/meteorological/160741_37067.json
Saving info at: ../data/raw/meteorological/184088_17031.json
Saving info at: ../data/raw/meteorological/153671_12057.json
Saving info at: ../data/raw/meteorological/153343_12101.json
Saving info at: ../data/raw/meteorological/183551_36119.json
Saving info at: ../data/raw/meteorological/174875_42133.json
Saving info at: ../data/raw/meteorological/185932_36029.json
Saving info at: ../data/raw/meteorological/153811_13121.json
Saving info at: ../data/raw/meteorological/176069_33015.json
Saving info at: ../data/raw/meteorological/170430_17197.json
Saving info at: ../data/raw/meteorological/136369_42019.json
Saving info at: ../data/raw/meteorological/126786_13121.json
Saving info at: ../data/raw/meteorological/152434_48457.json
Saving info at: ../data/raw/meteorological/112766_21015.json
Saving info at: ../data/raw/meteorological/115926_05111.json
Saving info at: ../data/raw/meteorological/110822_06073.json
Saving info at: ../data/raw/meteorological/128421_04013.json
Saving info at: ../data/raw/meteorological/125397_50025.json
Saving info at: ../data/raw/meteorological/178549_47053.json
Saving info at: ../data/raw/meteorological/130719_37155.json
Saving info at: ../data/raw/meteorological/119341_12021.json
Saving info at: ../data/raw/meteorological/181876_31055.json
Saving info at: ../data/raw/meteorological/145426_37067.json
Saving info at: ../data/raw/meteorological/184248_48471.json
Saving info at: ../data/raw/meteorological/106161_06029.json
Saving info at: ../data/raw/meteorological/175984_06093.json
Saving info at: ../data/raw/meteorological/169242_55083.json
Saving info at: ../data/raw/meteorological/106024_22011.json
Saving info at: ../data/raw/meteorological/99600_04019.json
Saving info at: ../data/raw/meteorological/157620_48423.json
Saving info at: ../data/raw/meteorological/105275_22017.json
Saving info at: ../data/raw/meteorological/171587_06063.json
Saving info at: ../data/raw/meteorological/131166_37191.json
Saving info at: ../data/raw/meteorological/149961_34025.json
Saving info at: ../data/raw/meteorological/137766_39165.json
Saving info at: ../data/raw/meteorological/96568_51059.json
Saving info at: ../data/raw/meteorological/181165_01069.json
Saving info at: ../data/raw/meteorological/156321_48163.json
Saving info at: ../data/raw/meteorological/117046_24035.json
Saving info at: ../data/raw/meteorological/132312_05143.json
Saving info at: ../data/raw/meteorological/110418_24031.json
Saving info at: ../data/raw/meteorological/158904_36067.json
Saving info at: ../data/raw/meteorological/185246_12057.json
Saving info at: ../data/raw/meteorological/116648_34029.json
Saving info at: ../data/raw/meteorological/167705_27097.json
Saving info at: ../data/raw/meteorological/143680_47037.json
Saving info at: ../data/raw/meteorological/106235_13067.json
Saving info at: ../data/raw/meteorological/141260_55075.json
Saving info at: ../data/raw/meteorological/184551_06071.json
Saving info at: ../data/raw/meteorological/150318_12031.json
Saving info at: ../data/raw/meteorological/125667_36049.json
Saving info at: ../data/raw/meteorological/177607_48381.json
Saving info at: ../data/raw/meteorological/104596_12111.json
Saving info at: ../data/raw/meteorological/168038_53041.json
Saving info at: ../data/raw/meteorological/108780_51177.json
Saving info at: ../data/raw/meteorological/104739_47037.json
Saving info at: ../data/raw/meteorological/163555_36087.json
Saving info at: ../data/raw/meteorological/184621_12031.json
Saving info at: ../data/raw/meteorological/147340_13257.json
Saving info at: ../data/raw/meteorological/133470_47165.json
Saving info at: ../data/raw/meteorological/186062_29217.json
Saving info at: ../data/raw/meteorological/164267_06089.json
Saving info at: ../data/raw/meteorological/133853_36063.json
Saving info at: ../data/raw/meteorological/158824_06071.json
Saving info at: ../data/raw/meteorological/166575_27131.json
Saving info at: ../data/raw/meteorological/107146_27017.json
Saving info at: ../data/raw/meteorological/170097_21111.json
Saving info at: ../data/raw/meteorological/181131_48439.json
Saving info at: ../data/raw/meteorological/131448_26125.json
Saving info at: ../data/raw/meteorological/146381_42091.json
Saving info at: ../data/raw/meteorological/159058_34019.json
Saving info at: ../data/raw/meteorological/155704_48209.json
Saving info at: ../data/raw/meteorological/159827_24009.json
Saving info at: ../data/raw/meteorological/96272_39035.json
Saving info at: ../data/raw/meteorological/102497_53053.json
Saving info at: ../data/raw/meteorological/146608_08077.json
Saving info at: ../data/raw/meteorological/180280_12031.json
Saving info at: ../data/raw/meteorological/158468_47009.json
Saving info at: ../data/raw/meteorological/166754_05035.json
Saving info at: ../data/raw/meteorological/162420_06071.json
Saving info at: ../data/raw/meteorological/182357_48085.json
Saving info at: ../data/raw/meteorological/123615_22073.json
Saving info at: ../data/raw/meteorological/90827_06111.json
Saving info at: ../data/raw/meteorological/106633_24033.json
Saving info at: ../data/raw/meteorological/169037_39133.json
Saving info at: ../data/raw/meteorological/120590_45029.json
Saving info at: ../data/raw/meteorological/164698_45077.json
Saving info at: ../data/raw/meteorological/146151_37101.json
Saving info at: ../data/raw/meteorological/152439_51087.json
Saving info at: ../data/raw/meteorological/156289_48245.json
Saving info at: ../data/raw/meteorological/184038_13233.json
Saving info at: ../data/raw/meteorological/94850_48113.json
Saving info at: ../data/raw/meteorological/169793_05101.json
Saving info at: ../data/raw/meteorological/146641_06029.json
Saving info at: ../data/raw/meteorological/145167_36077.json
Saving info at: ../data/raw/meteorological/155465_48145.json
Saving info at: ../data/raw/meteorological/92150_10003.json
Saving info at: ../data/raw/meteorological/162129_28147.json
Saving info at: ../data/raw/meteorological/103098_34029.json
Saving info at: ../data/raw/meteorological/185583_12017.json
Saving info at: ../data/raw/meteorological/132199_51117.json
Saving info at: ../data/raw/meteorological/139617_47051.json
Saving info at: ../data/raw/meteorological/159506_40111.json
Saving info at: ../data/raw/meteorological/115430_27003.json
Saving info at: ../data/raw/meteorological/162039_34007.json
Saving info at: ../data/raw/meteorological/103856_39115.json
Saving info at: ../data/raw/meteorological/98451_13135.json
Saving info at: ../data/raw/meteorological/162331_26099.json
Saving info at: ../data/raw/meteorological/161494_22073.json
Saving info at: ../data/raw/meteorological/177403_06059.json
Saving info at: ../data/raw/meteorological/156135_23019.json
Saving info at: ../data/raw/meteorological/167076_39141.json
Saving info at: ../data/raw/meteorological/128135_37063.json
Saving info at: ../data/raw/meteorological/133664_42029.json
Saving info at: ../data/raw/meteorological/162789_16001.json
Saving info at: ../data/raw/meteorological/156276_51011.json
Saving info at: ../data/raw/meteorological/117701_55047.json
Saving info at: ../data/raw/meteorological/153906_45083.json
Saving info at: ../data/raw/meteorological/178439_42003.json
Saving info at: ../data/raw/meteorological/137222_22017.json
Saving info at: ../data/raw/meteorological/133801_06013.json
Saving info at: ../data/raw/meteorological/152443_48167.json
Saving info at: ../data/raw/meteorological/133295_18151.json
Saving info at: ../data/raw/meteorological/156228_06037.json
Saving info at: ../data/raw/meteorological/97298_25001.json
Saving info at: ../data/raw/meteorological/138152_01003.json
Saving info at: ../data/raw/meteorological/159943_06071.json
Saving info at: ../data/raw/meteorological/183556_06059.json
Saving info at: ../data/raw/meteorological/176582_48355.json
Saving info at: ../data/raw/meteorological/173010_48491.json
Saving info at: ../data/raw/meteorological/173010_48299.json
Saving info at: ../data/raw/meteorological/96168_54107.json
Saving info at: ../data/raw/meteorological/166128_06077.json
Saving info at: ../data/raw/meteorological/164891_12086.json
Saving info at: ../data/raw/meteorological/147983_48029.json
Saving info at: ../data/raw/meteorological/151683_51095.json
Saving info at: ../data/raw/meteorological/108111_32003.json
Saving info at: ../data/raw/meteorological/125856_39113.json
Saving info at: ../data/raw/meteorological/135070_06109.json
Saving info at: ../data/raw/meteorological/186068_48439.json
Saving info at: ../data/raw/meteorological/150807_36067.json
Saving info at: ../data/raw/meteorological/185278_55139.json
Saving info at: ../data/raw/meteorological/133994_06085.json
Saving info at: ../data/raw/meteorological/121981_51085.json
Saving info at: ../data/raw/meteorological/91253_48485.json
Saving info at: ../data/raw/meteorological/177719_48171.json
Saving info at: ../data/raw/meteorological/115754_47157.json
Saving info at: ../data/raw/meteorological/171967_05049.json
Saving info at: ../data/raw/meteorological/148801_54039.json
Saving info at: ../data/raw/meteorological/145578_37183.json
Saving info at: ../data/raw/meteorological/115819_45079.json
Saving info at: ../data/raw/meteorological/92317_23021.json
Saving info at: ../data/raw/meteorological/102057_34025.json
Saving info at: ../data/raw/meteorological/127706_29077.json
Saving info at: ../data/raw/meteorological/119188_06071.json
Saving info at: ../data/raw/meteorological/120899_49035.json
Saving info at: ../data/raw/meteorological/101753_34025.json
Saving info at: ../data/raw/meteorological/93513_45045.json
Saving info at: ../data/raw/meteorological/178500_26099.json
Saving info at: ../data/raw/meteorological/95584_17031.json
Saving info at: ../data/raw/meteorological/92934_48085.json
Saving info at: ../data/raw/meteorological/149499_26099.json
Saving info at: ../data/raw/meteorological/150830_40017.json
Saving info at: ../data/raw/meteorological/162131_44009.json
Saving info at: ../data/raw/meteorological/174860_40109.json
Saving info at: ../data/raw/meteorological/108034_29189.json
Done with saving.
Starting

Dask Apply:   0%|          | 0/41 [00:00<?, ?it/s]

/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)

time it took 858.3908020829986
Saving info at: ../data/raw/meteorological/156286_22097.json
Saving info at: ../data/raw/meteorological/183270_42133.json
Saving info at: ../data/raw/meteorological/147748_12095.json
Saving info at: ../data/raw/meteorological/102238_40143.json
Saving info at: ../data/raw/meteorological/163687_36019.json
Saving info at: ../data/raw/meteorological/162129_28109.json
Saving info at: ../data/raw/meteorological/139467_48459.json
Saving info at: ../data/raw/meteorological/163555_36119.json
Saving info at: ../data/raw/meteorological/180245_01089.json
Saving info at: ../data/raw/meteorological/183474_51059.json
Saving info at: ../data/raw/meteorological/172855_48423.json
Saving info at: ../data/raw/meteorological/178388_12105.json
Saving info at: ../data/raw/meteorological/181733_47031.json
Saving info at: ../data/raw/meteorological/182359_48139.json
Saving info at: ../data/raw/meteorological/109965_25017.json
Saving info at: ../data/raw/meteorological/162819_48339.json
Saving info at: ../data/raw/meteorological/134608_42125.json
Saving info at: ../data/raw/meteorological/174603_06029.json
Saving info at: ../data/raw/meteorological/112435_06065.json
Saving info at: ../data/raw/meteorological/123702_22073.json
Saving info at: ../data/raw/meteorological/139033_47037.json
Saving info at: ../data/raw/meteorological/185327_47157.json
Saving info at: ../data/raw/meteorological/173918_48439.json
Saving info at: ../data/raw/meteorological/115185_55127.json
Saving info at: ../data/raw/meteorological/107321_42077.json
Saving info at: ../data/raw/meteorological/158400_06093.json
Saving info at: ../data/raw/meteorological/121682_36075.json
Saving info at: ../data/raw/meteorological/95571_08123.json
Saving info at: ../data/raw/meteorological/144149_36059.json
Saving info at: ../data/raw/meteorological/114914_55079.json
Saving info at: ../data/raw/meteorological/160989_34007.json
Saving info at: ../data/raw/meteorological/169232_17191.json
Saving info at: ../data/raw/meteorological/147540_13077.json
Saving info at: ../data/raw/meteorological/185424_22071.json
Saving info at: ../data/raw/meteorological/178889_21129.json
Saving info at: ../data/raw/meteorological/161750_36075.json
Saving info at: ../data/raw/meteorological/157473_35001.json
Saving info at: ../data/raw/meteorological/133639_55059.json
Saving info at: ../data/raw/meteorological/176641_39071.json
Saving info at: ../data/raw/meteorological/153553_01111.json
Saving info at: ../data/raw/meteorological/167755_18105.json
Saving info at: ../data/raw/meteorological/184829_47157.json
Saving info at: ../data/raw/meteorological/169323_49049.json
Saving info at: ../data/raw/meteorological/152144_12095.json
Saving info at: ../data/raw/meteorological/115930_22033.json
Saving info at: ../data/raw/meteorological/172236_01101.json
Saving info at: ../data/raw/meteorological/142782_28127.json
Saving info at: ../data/raw/meteorological/172710_48401.json
Saving info at: ../data/raw/meteorological/158158_23007.json
Saving info at: ../data/raw/meteorological/154105_37183.json
Saving info at: ../data/raw/meteorological/155591_06065.json
Saving info at: ../data/raw/meteorological/160783_15003.json
Saving info at: ../data/raw/meteorological/166145_48397.json
Saving info at: ../data/raw/meteorological/106595_18023.json
Saving info at: ../data/raw/meteorological/155818_06065.json
Saving info at: ../data/raw/meteorological/105094_13089.json
Saving info at: ../data/raw/meteorological/161056_17097.json
Saving info at: ../data/raw/meteorological/138816_47187.json
Saving info at: ../data/raw/meteorological/136860_37089.json
Saving info at: ../data/raw/meteorological/168921_51800.json
Saving info at: ../data/raw/meteorological/143522_48451.json
Saving info at: ../data/raw/meteorological/91142_50017.json
Saving info at: ../data/raw/meteorological/162383_42079.json
Saving info at: ../data/raw/meteorological/176805_24023.json
Saving info at: ../data/raw/meteorological/109645_37165.json
Saving info at: ../data/raw/meteorological/106889_06029.json
Saving info at: ../data/raw/meteorological/114666_18077.json
Saving info at: ../data/raw/meteorological/116816_16027.json
Saving info at: ../data/raw/meteorological/119889_29165.json
Saving info at: ../data/raw/meteorological/175063_47187.json
Saving info at: ../data/raw/meteorological/106970_17055.json
Saving info at: ../data/raw/meteorological/171006_40049.json
Saving info at: ../data/raw/meteorological/96444_26163.json
Saving info at: ../data/raw/meteorological/180338_12099.json
Saving info at: ../data/raw/meteorological/129282_08001.json
Saving info at: ../data/raw/meteorological/131655_13009.json
Saving info at: ../data/raw/meteorological/183919_48141.json
Saving info at: ../data/raw/meteorological/140955_27037.json
Saving info at: ../data/raw/meteorological/169918_21159.json
Saving info at: ../data/raw/meteorological/120347_13187.json
Saving info at: ../data/raw/meteorological/114282_13135.json
Saving info at: ../data/raw/meteorological/175117_06029.json
Saving info at: ../data/raw/meteorological/118903_06073.json
Saving info at: ../data/raw/meteorological/175804_05005.json
Saving info at: ../data/raw/meteorological/134607_39119.json
Saving info at: ../data/raw/meteorological/156321_48325.json
Saving info at: ../data/raw/meteorological/184600_13277.json
Saving info at: ../data/raw/meteorological/162302_12073.json
Saving info at: ../data/raw/meteorological/172987_47049.json
Saving info at: ../data/raw/meteorological/116045_48453.json
Saving info at: ../data/raw/meteorological/177755_54045.json
Saving info at: ../data/raw/meteorological/164287_26165.json
Saving info at: ../data/raw/meteorological/152882_26147.json
Saving info at: ../data/raw/meteorological/172489_48097.json
Saving info at: ../data/raw/meteorological/171337_27109.json
Saving info at: ../data/raw/meteorological/178741_21021.json
Saving info at: ../data/raw/meteorological/103313_47093.json
Saving info at: ../data/raw/meteorological/131808_06087.json
Saving info at: ../data/raw/meteorological/181177_13087.json
Saving info at: ../data/raw/meteorological/140637_22045.json
Saving info at: ../data/raw/meteorological/172236_01121.json
Saving info at: ../data/raw/meteorological/111808_36055.json
Saving info at: ../data/raw/meteorological/98103_51041.json
Saving info at: ../data/raw/meteorological/136732_37067.json
Saving info at: ../data/raw/meteorological/97447_45019.json
Saving info at: ../data/raw/meteorological/123915_26115.json
Saving info at: ../data/raw/meteorological/156469_05063.json
Saving info at: ../data/raw/meteorological/169832_08043.json
Saving info at: ../data/raw/meteorological/133275_06085.json
Saving info at: ../data/raw/meteorological/146171_23001.json
Saving info at: ../data/raw/meteorological/113915_16011.json
Saving info at: ../data/raw/meteorological/120591_50023.json
Saving info at: ../data/raw/meteorological/140675_39035.json
Saving info at: ../data/raw/meteorological/164556_53061.json
Saving info at: ../data/raw/meteorological/119924_25023.json
Saving info at: ../data/raw/meteorological/163809_35039.json
Saving info at: ../data/raw/meteorological/160871_28089.json
Saving info at: ../data/raw/meteorological/113171_13295.json
Saving info at: ../data/raw/meteorological/145776_33015.json
Saving info at: ../data/raw/meteorological/102267_12011.json
Saving info at: ../data/raw/meteorological/155530_21063.json
Saving info at: ../data/raw/meteorological/146714_06071.json
Saving info at: ../data/raw/meteorological/125947_47155.json
Saving info at: ../data/raw/meteorological/106141_05125.json
Saving info at: ../data/raw/meteorological/157287_48019.json
Saving info at: ../data/raw/meteorological/146665_36043.json
Saving info at: ../data/raw/meteorological/181713_05131.json
Saving info at: ../data/raw/meteorological/169134_06071.json
Saving info at: ../data/raw/meteorological/114111_22073.json
Saving info at: ../data/raw/meteorological/147762_42069.json
Saving info at: ../data/raw/meteorological/117902_29047.json
Saving info at: ../data/raw/meteorological/150437_17073.json
Saving info at: ../data/raw/meteorological/171544_17183.json
Saving info at: ../data/raw/meteorological/108909_13051.json
Saving info at: ../data/raw/meteorological/128184_29189.json
Saving info at: ../data/raw/meteorological/186149_48027.json
Saving info at: ../data/raw/meteorological/179180_48029.json
Saving info at: ../data/raw/meteorological/99119_37081.json
Saving info at: ../data/raw/meteorological/147279_37155.json
Saving info at: ../data/raw/meteorological/164956_24009.json
Saving info at: ../data/raw/meteorological/99100_12011.json
Saving info at: ../data/raw/meteorological/101488_40051.json
Saving info at: ../data/raw/meteorological/176005_23005.json
Saving info at: ../data/raw/meteorological/179193_39087.json
Saving info at: ../data/raw/meteorological/183473_24025.json
Saving info at: ../data/raw/meteorological/134142_36083.json
Saving info at: ../data/raw/meteorological/137108_48213.json
Saving info at: ../data/raw/meteorological/102857_36043.json
Saving info at: ../data/raw/meteorological/121926_06083.json
Saving info at: ../data/raw/meteorological/91142_50027.json
Saving info at: ../data/raw/meteorological/100724_26021.json
Saving info at: ../data/raw/meteorological/161184_36105.json
Saving info at: ../data/raw/meteorological/100236_16001.json
Saving info at: ../data/raw/meteorological/180253_06077.json
Saving info at: ../data/raw/meteorological/140694_37129.json
Saving info at: ../data/raw/meteorological/147470_22113.json
Saving info at: ../data/raw/meteorological/98868_34029.json
Saving info at: ../data/raw/meteorological/182261_48113.json
Saving info at: ../data/raw/meteorological/175661_08077.json
Saving info at: ../data/raw/meteorological/156292_12105.json
Saving info at: ../data/raw/meteorological/166004_06077.json
Saving info at: ../data/raw/meteorological/186614_29113.json
Saving info at: ../data/raw/meteorological/135084_01093.json
Saving info at: ../data/raw/meteorological/113114_45079.json
Saving info at: ../data/raw/meteorological/96410_12099.json
Saving info at: ../data/raw/meteorological/140165_36007.json
Saving info at: ../data/raw/meteorological/156621_37145.json
Saving info at: ../data/raw/meteorological/113570_18011.json
Saving info at: ../data/raw/meteorological/182520_48357.json
Saving info at: ../data/raw/meteorological/112887_21151.json
Saving info at: ../data/raw/meteorological/170380_48469.json
Saving info at: ../data/raw/meteorological/132555_51143.json
Saving info at: ../data/raw/meteorological/151777_19103.json
Saving info at: ../data/raw/meteorological/106821_35001.json
Saving info at: ../data/raw/meteorological/95589_34033.json
Saving info at: ../data/raw/meteorological/166331_06077.json
Saving info at: ../data/raw/meteorological/141065_06073.json
Saving info at: ../data/raw/meteorological/182227_45013.json
Saving info at: ../data/raw/meteorological/164222_06017.json
Saving info at: ../data/raw/meteorological/179201_06037.json
Saving info at: ../data/raw/meteorological/152610_48303.json
Saving info at: ../data/raw/meteorological/130540_45045.json
Saving info at: ../data/raw/meteorological/156532_37019.json
Saving info at: ../data/raw/meteorological/163893_55085.json
Saving info at: ../data/raw/meteorological/105825_47037.json
Done with saving.
Starting

Dask Apply:   0%|          | 0/41 [00:00<?, ?it/s]

/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)

time it took 838.3517716439965
Saving info at: ../data/raw/meteorological/179821_51087.json
Saving info at: ../data/raw/meteorological/94951_55085.json
Saving info at: ../data/raw/meteorological/122640_34013.json
Saving info at: ../data/raw/meteorological/167449_27025.json
Saving info at: ../data/raw/meteorological/162695_04019.json
Saving info at: ../data/raw/meteorological/155121_25021.json
Saving info at: ../data/raw/meteorological/129475_37081.json
Saving info at: ../data/raw/meteorological/155803_40041.json
Saving info at: ../data/raw/meteorological/110820_06073.json
Saving info at: ../data/raw/meteorological/147983_48265.json
Saving info at: ../data/raw/meteorological/103788_48339.json
Saving info at: ../data/raw/meteorological/111642_06073.json
Saving info at: ../data/raw/meteorological/137435_55097.json
Saving info at: ../data/raw/meteorological/111316_51800.json
Saving info at: ../data/raw/meteorological/144001_48453.json
Saving info at: ../data/raw/meteorological/176711_55075.json
Saving info at: ../data/raw/meteorological/176583_51197.json
Saving info at: ../data/raw/meteorological/159641_16085.json
Saving info at: ../data/raw/meteorological/171007_40015.json
Saving info at: ../data/raw/meteorological/102041_55133.json
Saving info at: ../data/raw/meteorological/147430_12021.json
Saving info at: ../data/raw/meteorological/153358_06067.json
Saving info at: ../data/raw/meteorological/159567_36027.json
Saving info at: ../data/raw/meteorological/106286_27057.json
Saving info at: ../data/raw/meteorological/113468_25001.json
Saving info at: ../data/raw/meteorological/168276_01117.json
Saving info at: ../data/raw/meteorological/147803_34029.json
Saving info at: ../data/raw/meteorological/124430_37181.json
Saving info at: ../data/raw/meteorological/178732_05037.json
Saving info at: ../data/raw/meteorological/187867_34023.json
Saving info at: ../data/raw/meteorological/154034_48141.json
Saving info at: ../data/raw/meteorological/152592_04007.json
Saving info at: ../data/raw/meteorological/180197_13009.json
Saving info at: ../data/raw/meteorological/163520_23025.json
Saving info at: ../data/raw/meteorological/111728_23019.json
Saving info at: ../data/raw/meteorological/152629_13067.json
Saving info at: ../data/raw/meteorological/152321_22113.json
Saving info at: ../data/raw/meteorological/126644_33015.json
Saving info at: ../data/raw/meteorological/152058_35013.json
Saving info at: ../data/raw/meteorological/155843_05091.json
Saving info at: ../data/raw/meteorological/155272_15003.json
Saving info at: ../data/raw/meteorological/141024_34013.json
Saving info at: ../data/raw/meteorological/175822_20155.json
Saving info at: ../data/raw/meteorological/164747_06037.json
Saving info at: ../data/raw/meteorological/166030_48225.json
Saving info at: ../data/raw/meteorological/115029_25027.json
Saving info at: ../data/raw/meteorological/120347_13009.json
Saving info at: ../data/raw/meteorological/162539_42029.json
Saving info at: ../data/raw/meteorological/153772_40039.json
Saving info at: ../data/raw/meteorological/158601_06019.json
Saving info at: ../data/raw/meteorological/171774_51143.json
Saving info at: ../data/raw/meteorological/170255_04015.json
Saving info at: ../data/raw/meteorological/154005_48141.json
Saving info at: ../data/raw/meteorological/186214_48215.json
Saving info at: ../data/raw/meteorological/99267_18127.json
Saving info at: ../data/raw/meteorological/159763_06065.json
Saving info at: ../data/raw/meteorological/130590_04013.json
Saving info at: ../data/raw/meteorological/103808_19091.json
Saving info at: ../data/raw/meteorological/159706_12031.json
Saving info at: ../data/raw/meteorological/106614_42091.json
Saving info at: ../data/raw/meteorological/111845_47157.json
Saving info at: ../data/raw/meteorological/122887_12073.json
Saving info at: ../data/raw/meteorological/103278_12009.json
Saving info at: ../data/raw/meteorological/161607_55063.json
Saving info at: ../data/raw/meteorological/117071_55049.json
Saving info at: ../data/raw/meteorological/158099_08001.json
Saving info at: ../data/raw/meteorological/123237_42091.json
Saving info at: ../data/raw/meteorological/119102_19061.json
Saving info at: ../data/raw/meteorological/132631_39165.json
Saving info at: ../data/raw/meteorological/148908_25027.json
Saving info at: ../data/raw/meteorological/158226_42029.json
Saving info at: ../data/raw/meteorological/134555_24027.json
Saving info at: ../data/raw/meteorological/156171_51053.json
Saving info at: ../data/raw/meteorological/162629_04017.json
Saving info at: ../data/raw/meteorological/177965_48085.json
Saving info at: ../data/raw/meteorological/153671_12081.json
Saving info at: ../data/raw/meteorological/106098_22007.json
Saving info at: ../data/raw/meteorological/121644_13311.json
Saving info at: ../data/raw/meteorological/109514_22033.json
Saving info at: ../data/raw/meteorological/176823_35005.json
Saving info at: ../data/raw/meteorological/179804_17197.json
Saving info at: ../data/raw/meteorological/163577_48121.json
Saving info at: ../data/raw/meteorological/93681_12057.json
Saving info at: ../data/raw/meteorological/173918_48397.json
Saving info at: ../data/raw/meteorological/161166_01097.json
Saving info at: ../data/raw/meteorological/177436_06053.json
Saving info at: ../data/raw/meteorological/147364_37159.json
Saving info at: ../data/raw/meteorological/164954_26139.json
Saving info at: ../data/raw/meteorological/161392_06071.json
Saving info at: ../data/raw/meteorological/155908_25015.json
Saving info at: ../data/raw/meteorological/145987_27137.json
Saving info at: ../data/raw/meteorological/168395_06037.json
Saving info at: ../data/raw/meteorological/162555_20091.json
Saving info at: ../data/raw/meteorological/185085_48029.json
Saving info at: ../data/raw/meteorological/178509_36039.json
Saving info at: ../data/raw/meteorological/131454_20117.json
Saving info at: ../data/raw/meteorological/122893_39073.json
Saving info at: ../data/raw/meteorological/112532_39061.json
Saving info at: ../data/raw/meteorological/155555_39085.json
Saving info at: ../data/raw/meteorological/133747_42091.json
Saving info at: ../data/raw/meteorological/154181_22085.json
Saving info at: ../data/raw/meteorological/141123_40109.json
Saving info at: ../data/raw/meteorological/164897_17201.json
Saving info at: ../data/raw/meteorological/98831_20161.json
Saving info at: ../data/raw/meteorological/132538_21029.json
Saving info at: ../data/raw/meteorological/153717_05005.json
Saving info at: ../data/raw/meteorological/168819_48085.json
Saving info at: ../data/raw/meteorological/121109_33011.json
Saving info at: ../data/raw/meteorological/153664_28047.json
Saving info at: ../data/raw/meteorological/120869_55079.json
Saving info at: ../data/raw/meteorological/141423_24510.json
Saving info at: ../data/raw/meteorological/161916_24031.json
Saving info at: ../data/raw/meteorological/152444_06067.json
Saving info at: ../data/raw/meteorological/111192_25021.json
Saving info at: ../data/raw/meteorological/186010_48449.json
Saving info at: ../data/raw/meteorological/104090_06037.json
Saving info at: ../data/raw/meteorological/98723_18097.json
Saving info at: ../data/raw/meteorological/158468_47093.json
Saving info at: ../data/raw/meteorological/186051_32003.json
Saving info at: ../data/raw/meteorological/125637_37081.json
Saving info at: ../data/raw/meteorological/195777_04007.json
Saving info at: ../data/raw/meteorological/161526_05093.json
Saving info at: ../data/raw/meteorological/131858_26161.json
Saving info at: ../data/raw/meteorological/142670_10005.json
Saving info at: ../data/raw/meteorological/95337_26163.json
Saving info at: ../data/raw/meteorological/120004_36113.json
Saving info at: ../data/raw/meteorological/126839_42071.json
Saving info at: ../data/raw/meteorological/182407_22057.json
Saving info at: ../data/raw/meteorological/96068_47027.json
Saving info at: ../data/raw/meteorological/162616_49021.json
Saving info at: ../data/raw/meteorological/163226_12133.json
Saving info at: ../data/raw/meteorological/121050_23011.json
Saving info at: ../data/raw/meteorological/103355_34027.json
Saving info at: ../data/raw/meteorological/175535_33003.json
Saving info at: ../data/raw/meteorological/170551_18097.json
Saving info at: ../data/raw/meteorological/108576_12017.json
Saving info at: ../data/raw/meteorological/183412_47093.json
Saving info at: ../data/raw/meteorological/122206_48439.json
Saving info at: ../data/raw/meteorological/183662_46135.json
Saving info at: ../data/raw/meteorological/130639_12023.json
Saving info at: ../data/raw/meteorological/98577_20177.json
Saving info at: ../data/raw/meteorological/124517_51023.json
Saving info at: ../data/raw/meteorological/130192_40109.json
Saving info at: ../data/raw/meteorological/157350_42107.json
Saving info at: ../data/raw/meteorological/153456_37193.json
Saving info at: ../data/raw/meteorological/173748_40017.json
Saving info at: ../data/raw/meteorological/158379_17031.json
Saving info at: ../data/raw/meteorological/149713_10001.json
Saving info at: ../data/raw/meteorological/93917_22047.json
Saving info at: ../data/raw/meteorological/166765_36031.json
Saving info at: ../data/raw/meteorological/182926_01089.json
Saving info at: ../data/raw/meteorological/160664_26105.json
Saving info at: ../data/raw/meteorological/104093_06111.json
Saving info at: ../data/raw/meteorological/149884_08041.json
Saving info at: ../data/raw/meteorological/171279_37195.json
Saving info at: ../data/raw/meteorological/169047_06073.json
Saving info at: ../data/raw/meteorological/158954_06073.json
Saving info at: ../data/raw/meteorological/182947_29095.json
Saving info at: ../data/raw/meteorological/156713_36027.json
Saving info at: ../data/raw/meteorological/185961_29113.json
Saving info at: ../data/raw/meteorological/154844_41057.json
Saving info at: ../data/raw/meteorological/181814_08035.json
Saving info at: ../data/raw/meteorological/162645_37123.json
Saving info at: ../data/raw/meteorological/97105_48029.json
Saving info at: ../data/raw/meteorological/147423_12021.json
Saving info at: ../data/raw/meteorological/147315_54039.json
Saving info at: ../data/raw/meteorological/176864_40027.json
Saving info at: ../data/raw/meteorological/176229_47093.json
Saving info at: ../data/raw/meteorological/154436_04019.json
Saving info at: ../data/raw/meteorological/162024_36021.json
Saving info at: ../data/raw/meteorological/127371_51179.json
Saving info at: ../data/raw/meteorological/167828_12117.json
Saving info at: ../data/raw/meteorological/138559_34023.json
Saving info at: ../data/raw/meteorological/166144_55079.json
Saving info at: ../data/raw/meteorological/123144_35037.json
Saving info at: ../data/raw/meteorological/167739_06073.json
Saving info at: ../data/raw/meteorological/171070_06093.json
Saving info at: ../data/raw/meteorological/156618_41003.json
Saving info at: ../data/raw/meteorological/187862_06037.json
Saving info at: ../data/raw/meteorological/183305_12011.json
Saving info at: ../data/raw/meteorological/160593_28159.json
Saving info at: ../data/raw/meteorological/153199_23011.json
Saving info at: ../data/raw/meteorological/102857_36027.json
Saving info at: ../data/raw/meteorological/171608_29207.json
Saving info at: ../data/raw/meteorological/177043_06019.json
Saving info at: ../data/raw/meteorological/171673_47037.json
Saving info at: ../data/raw/meteorological/127976_47157.json
Done with saving.
Starting

Dask Apply:   0%|          | 0/41 [00:00<?, ?it/s]

/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)

time it took 821.6842419570021
Saving info at: ../data/raw/meteorological/112323_25015.json
Saving info at: ../data/raw/meteorological/174634_06071.json
Saving info at: ../data/raw/meteorological/181325_40027.json
Saving info at: ../data/raw/meteorological/172821_34029.json
Saving info at: ../data/raw/meteorological/187305_48085.json
Saving info at: ../data/raw/meteorological/162266_06065.json
Saving info at: ../data/raw/meteorological/186630_48455.json
Saving info at: ../data/raw/meteorological/129369_34039.json
Saving info at: ../data/raw/meteorological/155546_06029.json
Saving info at: ../data/raw/meteorological/146304_28075.json
Saving info at: ../data/raw/meteorological/137435_55073.json
Saving info at: ../data/raw/meteorological/184005_45083.json
Saving info at: ../data/raw/meteorological/158786_12011.json
Saving info at: ../data/raw/meteorological/147846_28137.json
Saving info at: ../data/raw/meteorological/148467_48473.json
Saving info at: ../data/raw/meteorological/102566_10001.json
Saving info at: ../data/raw/meteorological/128927_39061.json
Saving info at: ../data/raw/meteorological/131661_48355.json
Saving info at: ../data/raw/meteorological/163152_37063.json
Saving info at: ../data/raw/meteorological/95486_42033.json
Saving info at: ../data/raw/meteorological/133448_42111.json
Saving info at: ../data/raw/meteorological/170378_12021.json
Saving info at: ../data/raw/meteorological/176178_48245.json
Saving info at: ../data/raw/meteorological/122419_10003.json
Saving info at: ../data/raw/meteorological/116586_28085.json
Saving info at: ../data/raw/meteorological/177679_40051.json
Saving info at: ../data/raw/meteorological/186123_22011.json
Saving info at: ../data/raw/meteorological/138585_34023.json
Saving info at: ../data/raw/meteorological/169093_51107.json
Saving info at: ../data/raw/meteorological/169118_06073.json
Saving info at: ../data/raw/meteorological/175159_17197.json
Saving info at: ../data/raw/meteorological/150781_37187.json
Saving info at: ../data/raw/meteorological/157838_22063.json
Saving info at: ../data/raw/meteorological/119520_12103.json
Saving info at: ../data/raw/meteorological/173927_48113.json
Saving info at: ../data/raw/meteorological/171782_24047.json
Saving info at: ../data/raw/meteorological/182327_47093.json
Saving info at: ../data/raw/meteorological/104321_55131.json
Saving info at: ../data/raw/meteorological/163098_25009.json
Saving info at: ../data/raw/meteorological/130611_36091.json
Saving info at: ../data/raw/meteorological/183368_01055.json
Saving info at: ../data/raw/meteorological/177080_48215.json
Saving info at: ../data/raw/meteorological/131206_17031.json
Saving info at: ../data/raw/meteorological/153504_20035.json
Saving info at: ../data/raw/meteorological/112985_37179.json
Saving info at: ../data/raw/meteorological/111550_25027.json
Saving info at: ../data/raw/meteorological/156251_48321.json
Saving info at: ../data/raw/meteorological/98435_18003.json
Saving info at: ../data/raw/meteorological/114896_34023.json
Saving info at: ../data/raw/meteorological/163075_40143.json
Saving info at: ../data/raw/meteorological/148740_39093.json
Saving info at: ../data/raw/meteorological/106029_36043.json
Saving info at: ../data/raw/meteorological/124390_23031.json
Saving info at: ../data/raw/meteorological/149496_51087.json
Saving info at: ../data/raw/meteorological/132234_13043.json
Saving info at: ../data/raw/meteorological/185016_22079.json
Saving info at: ../data/raw/meteorological/181847_34027.json
Saving info at: ../data/raw/meteorological/115313_12023.json
Saving info at: ../data/raw/meteorological/182357_48289.json
Saving info at: ../data/raw/meteorological/112075_25021.json
Saving info at: ../data/raw/meteorological/113055_06071.json
Saving info at: ../data/raw/meteorological/132394_25023.json
Saving info at: ../data/raw/meteorological/109217_36029.json
Saving info at: ../data/raw/meteorological/122553_34021.json
Saving info at: ../data/raw/meteorological/175132_50017.json
Saving info at: ../data/raw/meteorological/110476_06029.json
Saving info at: ../data/raw/meteorological/185246_12053.json
Saving info at: ../data/raw/meteorological/109935_36103.json
Saving info at: ../data/raw/meteorological/117598_06071.json
Saving info at: ../data/raw/meteorological/119932_25025.json
Saving info at: ../data/raw/meteorological/130039_27053.json
Saving info at: ../data/raw/meteorological/170185_18095.json
Saving info at: ../data/raw/meteorological/108827_55025.json
Saving info at: ../data/raw/meteorological/105754_29189.json
Saving info at: ../data/raw/meteorological/163137_06071.json
Saving info at: ../data/raw/meteorological/104054_51061.json
Saving info at: ../data/raw/meteorological/141164_42003.json
Saving info at: ../data/raw/meteorological/156906_48291.json
Saving info at: ../data/raw/meteorological/129012_34039.json
Saving info at: ../data/raw/meteorological/178956_13123.json
Saving info at: ../data/raw/meteorological/168818_48429.json
Saving info at: ../data/raw/meteorological/102343_42029.json
Saving info at: ../data/raw/meteorological/167159_38017.json
Saving info at: ../data/raw/meteorological/123144_35009.json
Saving info at: ../data/raw/meteorological/109480_17163.json
Saving info at: ../data/raw/meteorological/170135_48355.json
Saving info at: ../data/raw/meteorological/127984_26163.json
Saving info at: ../data/raw/meteorological/144718_18129.json
Saving info at: ../data/raw/meteorological/142454_36031.json
Saving info at: ../data/raw/meteorological/158311_37023.json
Saving info at: ../data/raw/meteorological/108794_48117.json
Saving info at: ../data/raw/meteorological/161389_32003.json
Saving info at: ../data/raw/meteorological/185287_37183.json
Saving info at: ../data/raw/meteorological/164955_26077.json
Saving info at: ../data/raw/meteorological/177209_47009.json
Saving info at: ../data/raw/meteorological/163919_55133.json
Saving info at: ../data/raw/meteorological/162941_06063.json
Saving info at: ../data/raw/meteorological/185154_48309.json
Saving info at: ../data/raw/meteorological/134281_39045.json
Saving info at: ../data/raw/meteorological/113983_06037.json
Saving info at: ../data/raw/meteorological/182668_42091.json
Saving info at: ../data/raw/meteorological/178193_48373.json
Saving info at: ../data/raw/meteorological/140304_06071.json
Saving info at: ../data/raw/meteorological/182813_25009.json
Saving info at: ../data/raw/meteorological/186186_34013.json
Saving info at: ../data/raw/meteorological/98451_13089.json
Saving info at: ../data/raw/meteorological/94509_06067.json
Saving info at: ../data/raw/meteorological/164954_26081.json
Saving info at: ../data/raw/meteorological/186630_48339.json
Saving info at: ../data/raw/meteorological/152321_22009.json
Saving info at: ../data/raw/meteorological/128222_04013.json
Saving info at: ../data/raw/meteorological/107013_51031.json
Saving info at: ../data/raw/meteorological/181295_17179.json
Saving info at: ../data/raw/meteorological/138173_06077.json
Saving info at: ../data/raw/meteorological/163522_33003.json
Saving info at: ../data/raw/meteorological/128176_01037.json
Saving info at: ../data/raw/meteorological/128176_01047.json
Saving info at: ../data/raw/meteorological/146307_28067.json
Saving info at: ../data/raw/meteorological/145844_21195.json
Saving info at: ../data/raw/meteorological/91880_06107.json
Saving info at: ../data/raw/meteorological/177358_06081.json
Saving info at: ../data/raw/meteorological/107509_47157.json
Saving info at: ../data/raw/meteorological/152511_53033.json
Saving info at: ../data/raw/meteorological/179780_12011.json
Saving info at: ../data/raw/meteorological/183070_17099.json
Saving info at: ../data/raw/meteorological/153005_42123.json
Saving info at: ../data/raw/meteorological/105214_37183.json
Saving info at: ../data/raw/meteorological/108426_37119.json
Saving info at: ../data/raw/meteorological/142418_13121.json
Saving info at: ../data/raw/meteorological/132113_51115.json
Saving info at: ../data/raw/meteorological/154279_06059.json
Saving info at: ../data/raw/meteorological/176093_23009.json
Saving info at: ../data/raw/meteorological/146013_04025.json
Saving info at: ../data/raw/meteorological/99256_34023.json
Saving info at: ../data/raw/meteorological/135803_06071.json
Saving info at: ../data/raw/meteorological/92495_12065.json
Saving info at: ../data/raw/meteorological/146527_29095.json
Saving info at: ../data/raw/meteorological/133814_06045.json
Saving info at: ../data/raw/meteorological/167822_21111.json
Saving info at: ../data/raw/meteorological/116578_25003.json
Saving info at: ../data/raw/meteorological/152321_22039.json
Saving info at: ../data/raw/meteorological/153553_01085.json
Saving info at: ../data/raw/meteorological/164782_20161.json
Saving info at: ../data/raw/meteorological/177365_13067.json
Saving info at: ../data/raw/meteorological/150716_48423.json
Saving info at: ../data/raw/meteorological/153663_22057.json
Saving info at: ../data/raw/meteorological/158883_22071.json
Saving info at: ../data/raw/meteorological/156371_05037.json
Saving info at: ../data/raw/meteorological/165282_40109.json
Saving info at: ../data/raw/meteorological/103377_22105.json
Saving info at: ../data/raw/meteorological/143977_47155.json
Saving info at: ../data/raw/meteorological/91441_48439.json
Saving info at: ../data/raw/meteorological/182882_05031.json
Saving info at: ../data/raw/meteorological/165172_22055.json
Saving info at: ../data/raw/meteorological/133515_36013.json
Saving info at: ../data/raw/meteorological/115851_37119.json
Saving info at: ../data/raw/meteorological/169564_26099.json
Saving info at: ../data/raw/meteorological/187871_48085.json
Saving info at: ../data/raw/meteorological/160158_42115.json
Saving info at: ../data/raw/meteorological/182050_08031.json
Saving info at: ../data/raw/meteorological/131365_51085.json
Saving info at: ../data/raw/meteorological/155465_48309.json
Saving info at: ../data/raw/meteorological/172514_36005.json
Saving info at: ../data/raw/meteorological/144452_36029.json
Saving info at: ../data/raw/meteorological/101799_23005.json
Saving info at: ../data/raw/meteorological/145633_05123.json
Saving info at: ../data/raw/meteorological/182589_26049.json
Saving info at: ../data/raw/meteorological/172082_48215.json
Saving info at: ../data/raw/meteorological/107847_51059.json
Saving info at: ../data/raw/meteorological/165321_47125.json
Saving info at: ../data/raw/meteorological/156171_51145.json
Saving info at: ../data/raw/meteorological/156469_05097.json
Saving info at: ../data/raw/meteorological/152392_27123.json
Saving info at: ../data/raw/meteorological/134872_12053.json
Saving info at: ../data/raw/meteorological/186436_48121.json
Saving info at: ../data/raw/meteorological/182189_40109.json
Saving info at: ../data/raw/meteorological/151726_37073.json
Saving info at: ../data/raw/meteorological/93740_06065.json
Saving info at: ../data/raw/meteorological/168818_48121.json
Saving info at: ../data/raw/meteorological/158793_12011.json
Saving info at: ../data/raw/meteorological/144489_42011.json
Saving info at: ../data/raw/meteorological/181806_12011.json
Done with saving.
Starting

KeyboardInterrupt:

In [313]:
# This is not needed...

In [309]:
sample_outages_storms = outages_storms.sample(element_nb, random_state=random_seed)
meaning_dict = {'begin_datetime': 'storm_start', 'end_datetime': 'storm_end', 'run_start_time_min': 'outage_start', 'run_start_time_max': 'outage_end'}
sample_outages_storms = sample_outages_storms.rename(
    columns=meaning_dict
)
sample_outages_storms['one_day_before_storm'] = (sample_outages_storms['storm_start'] - pd.Timedelta(1, unit='D')).dt.date
sample_outages_storms['one_day_after_storm'] = (sample_outages_storms['storm_end'] + pd.Timedelta(1, unit='D')).dt.date
sample_outages_storms = sample_outages_storms.merge(counties[['fips_code_id', 'geometry']], on='fips_code_id')
sample_outages_storms = gpd.GeoDataFrame(sample_outages_storms)

In [310]:
sample_outages_storms['rep_point'] = sample_outages_storms.geometry.representative_point()
#sample_outages_storms['up'] = sample_outages_storms.extract_unique_points()
sample_outages_storms['cntroid'] = sample_outages_storms.geometry.centroid
sample_outages_storms['boundary_sample_p'] = sample_outages_storms.geometry.boundary.sample_points(10, random_seed=random_seed)
sample_outages_storms['sample_p1'] = sample_outages_storms.geometry.sample_points(size=1, random_seed=random_seed)
sample_outages_storms['sample_p2'] = sample_outages_storms.geometry.sample_points(size=1, random_seed=random_seed+1)
sample_outages_storms['sample_p3'] = sample_outages_storms.geometry.sample_points(size=1, random_seed=random_seed+2)

In [311]:
# #!pip install pointpats
# s = sample_outages_storms.sample(1)
# ax = s.plot()
# s.rep_point.plot(ax=ax, color='r')
# #s.up.plot(ax=ax, color='g')
# s.cntroid.plot(ax=ax, color='y')
# s.boundary_sample_p.plot(ax=ax, color='orange')
# s.sample_p1.plot(ax=ax, color='gray')
# s.sample_p2.plot(ax=ax, color='gray')
# s.sample_p3.plot(ax=ax, color='gray')

In [291]:

    
#sample_outages_storms['url__rep_point'] = sample_outages_storms.apply(get_url_params_from_row_point, desired_point='rep_point', axis=1)
sample_outages_storms['url__cntroid'] = sample_outages_storms.apply(get_url_params_from_row_point, desired_point='cntroid', axis=1)
#sample_outages_storms['url__sp1'] = sample_outages_storms.apply(get_url_params_from_row_point, desired_point='sample_p1', axis=1)
#sample_outages_storms['url__sp2'] = sample_outages_storms.apply(get_url_params_from_row_point, desired_point='sample_p2', axis=1)
#sample_outages_storms['url__sp3'] = sample_outages_storms.apply(get_url_params_from_row_point, desired_point='sample_p3', axis=1)

In [292]:
sample_outages_storms = sample_outages_storms[sample_outages_storms['url__cntroid'].notna()]

In [293]:
#sample_outages_storms.url__rep_point.iloc[0]

In [294]:
sample_outages_storms

,EPISODE_ID,fips_code_id,episode_description,storm_start,storm_end,storm_duration,episode_fips_id,storm_caused_outage,outage_index_id,outage_start_minus_storm_start,...,one_day_before_storm,one_day_after_storm,geometry,rep_point,cntroid,boundary_sample_p,sample_p1,sample_p2,sample_p3,url__cntroid
1134,177512,41007,"Combination of snow, sleet and freezing rain.",2022-12-22 16:00:00,2022-12-24 13:30:00,45.500000,177512_41007,1.0,41007__0028,1.104167,...,2022-12-21,2022-12-25,"POLYGON ((-124.01136 46.23622, -124.002 46.237...",POINT (-123.64603 46.02537),POINT (-123.65572 45.99514),"MULTIPOINT (-123.99276 45.94733, -123.98143 46...",POINT (-123.61519 46.16772),POINT (-123.80363 45.82972),POINT (-123.45997 46.25325),https://power.larc.nasa.gov/api/temporal/hourl...
1297,143238,48491,Nearly all of South Central Texas had less tha...,2019-10-01 00:00:00,2019-10-31 23:59:00,743.983333,143238_48491,1.0,48491__0043,24.010417,...,2019-09-30,2019-11-01,"POLYGON ((-98.04989 30.62416, -97.998 30.72021...",POINT (-97.63453 30.66086),POINT (-97.60028 30.64775),"MULTIPOINT (-97.92403 30.60898, -97.86906 30.5...",POINT (-97.27337 30.62153),POINT (-97.32981 30.50738),POINT (-97.72788 30.59015),https://power.larc.nasa.gov/api/temporal/hourl...
1298,133333,39045,Several waves of low pressure moved along a st...,2019-02-06 11:48:00,2019-02-08 01:40:00,37.866667,133333_39045,1.0,39045__0026,1.497917,...,2019-02-05,2019-02-09,"POLYGON ((-82.83646 39.62786, -82.83549 39.637...",POINT (-82.61561 39.75553),POINT (-82.63066 39.75161),"MULTIPOINT (-82.83847 39.60729, -82.83312 39.6...",POINT (-82.54017 39.63577),POINT (-82.64963 39.88632),POINT (-82.61747 39.70291),https://power.larc.nasa.gov/api/temporal/hourl...
1323,122191,01123,A significant snowstorm impacted central Alaba...,2017-12-08 06:00:00,2017-12-09 05:00:00,23.000000,122191_01123,1.0,01123__0000,1.281250,...,2017-12-07,2017-12-10,"POLYGON ((-86.00917 33.09026, -85.97456 33.090...",POINT (-85.7985 32.79904),POINT (-85.79737 32.86253),"MULTIPOINT (-86.00765 32.84728, -86.00273 32.8...",POINT (-85.74843 32.91815),POINT (-85.62518 32.82237),POINT (-85.90016 32.8075),https://power.larc.nasa.gov/api/temporal/hourl...
1324,140999,55131,Persistent southwest winds and the passage of ...,2019-07-19 09:00:00,2019-07-20 14:20:00,29.333333,140999_55131,1.0,55131__0012,1.385417,...,2019-07-18,2019-07-21,"POLYGON ((-88.41871 43.32544, -88.41856 43.365...",POINT (-88.22326 43.36869),POINT (-88.2306 43.36852),"MULTIPOINT (-88.41858 43.23706, -88.40971 43.1...",POINT (-88.18444 43.53001),POINT (-88.22479 43.37107),POINT (-88.34135 43.41851),https://power.larc.nasa.gov/api/temporal/hourl...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1685,162889,04021,A shortwave trough rotating through the region...,2021-08-16 22:20:00,2021-08-17 09:00:00,10.666667,162889_04021,1.0,04021__0023,0.309028,...,2021-08-15,2021-08-18,"POLYGON ((-112.20359 32.63781, -112.20352 32.8...",POINT (-111.32618 32.91065),POINT (-111.34481 32.90444),"MULTIPOINT (-112.19055 33.26471, -112.03076 33...",POINT (-111.88107 32.64663),POINT (-111.93212 32.94542),POINT (-111.88854 32.9753),https://power.larc.nasa.gov/api/temporal/hourl...
1686,132631,39017,An upper level low pressure center tracked nor...,2018-11-14 23:00:00,2018-11-15 12:00:00,13.000000,132631_39017,1.0,39017__0043,0.406250,...,2018-11-13,2018-11-16,"POLYGON ((-84.81935 39.30945, -84.81745 39.391...",POINT (-84.57696 39.44808),POINT (-84.57555 39.43865),"MULTIPOINT (-84.81544 39.51715, -84.81214 39.5...",POINT (-84.45194 39.41688),POINT (-84.44585 39.40869),POINT (-84.36739 39.39598),https://power.larc.nasa.gov/api/temporal/hourl...
1687,99672,29113,A frontal boundary was slowly sinking south ac...,2015-06-25 17:25:00,2015-06-26 14:55:00,21.500000,99672_29113,1.0,29113__0000,0.305556,...,2015-06-24,2015-06-27,"POLYGON ((-91.26311 39.037, -91.26023 39.13984...",POINT (-90.98767 39.05039),POINT (-90.95986 39.05802),"MULTIPOINT (-91.18894 38.95796, -91.17062 38.9...",POINT (-91.08214 38.89591),POINT (-90.90682 39.18039),POINT (-91.02052 38.92007),https://power.larc.nasa.gov/api/temporal/hourl...
1688,94338,06065,An upper-level trough deepened along the West ...,2015-03-01 00:00:00,2015-03-02 12:20:00,36.333333,94338_06065,1.0,06065__0015,0.250000,...,2015-02-28,2015-03-03,"POLYGON ((-117.67548 33.88812, -117.65488 33.8...",POINT (-116.02033 33.75369),POINT (-115.99477 33.74377),"MULTIPOINT (-117.44133 33.50502, -117.18768 33...",POINT (-117.2192 33.77591),POINT (-114.52887 33.79433),POINT (-115.81691 33.67794),https://power.larc.nasa.gov/api/temporal/hourl...
1689,120256,48029,A line of thunderstorms formed ahead of a cold...,2017-08-07 01:47:00,2017-08-07 13:15:00,11.466667,120256_48029,1.0,48029__0072,0.425694,...,2017-08-06,2017-08-08,"POLYGON ((-98.80655 29.69071, -98.77878 29.720...",POINT (-98.47099 29.43958),POINT (-98.51978 29.449),"MULTIPOINT (-98.8061 29.64888, -98.80477 29.26...",POINT (-98.51077 29.34134),POINT (-98.48982 29.51846),POINT (-98.59949 29.74299),https://power.larc.nasa.gov/api/temporal/hourl...

In [295]:
sample_outages_storms.url__cntroid.iloc[0]

'https://power.larc.nasa.gov/api/temporal/hourly/point?parameters=T2M,ALLSKY_SFC_SW_DWN,PS,WS50M,ALLSKY_SFC_LW_DWN,WD50M,PRECTOTCORR,GWETPROF,CLRSKY_SFC_SW_DWN,QV10M,RHOA,T10M,TO3,TQV,Z0M,TOA_SW_DWN,RH2M,WS2M,CLRSKY_SFC_LW_DWN,DISPH&community=RE&longitude=-123.6557206172946&latitude=45.995139447263576&start=20221221&end=20221225&format=JSON'

In [296]:
#sample_outages_storms.url__sp1.iloc[0]

In [297]:
#%%time
#sample_outages_storms['meteorological_info__rep_point'] = sample_outages_storms.url__rep_point.apply(meteorological_api.get_meteorological_info)

In [298]:
#%%time
#sample_outages_storms['meteorological_info__url__cntroid'] = sample_outages_storms.url__cntroid.apply(meteorological_api.get_meteorological_info)

In [299]:
%%time
sample_outages_storms['meteorological_info__cntroid'] = sample_outages_storms.url__cntroid.swifter.allow_dask_on_strings(enable=True).apply(meteorological_api.get_meteorological_info)

Dask Apply:   0%|          | 0/41 [00:00<?, ?it/s]

/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)
/mnt/c/Users/52333/Documents/projects/dynamic-rythms/venv/lib/python3.10/site-packages/dask/utils.py:1226: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  return getattr(__obj, self.method)(*args, **kwargs)

CPU times: user 770 ms, sys: 182 ms, total: 953 ms
Wall time: 14min 7s

In [300]:
#sample_outages_storms['meteorological_info__cntroid']

In [301]:
#rep_point = pd.DataFrame(sample_outages_storms.meteorological_info__rep_point.iloc[9]['properties']['parameter'])
centroid = pd.DataFrame(sample_outages_storms.meteorological_info__cntroid.iloc[9]['properties']['parameter'])
#rep_point-centroid

In [302]:
#sample_outages_storms['meteorological_info__cntroid'].iloc[0].get('properties')

In [303]:
def save_meteorological_info_from_row_point(storm_outage_row_iterated):
    idx, storm_outage_row = storm_outage_row_iterated
    identifier = storm_outage_row['episode_fips_id']
    meteorological_info = storm_outage_row['meteorological_info__cntroid']
    validate = meteorological_info.get('properties')
    save_path = f'../data/raw/meteorological/{identifier}.json'
    filexists = utils.check_if_filepath_exists(save_path)
    if (not filexists) and (validate is not None):
        meteorological_api.save_meteorological_information(information=meteorological_info, path=save_path)
        print(f'Saving info at: {save_path}')
        return 1
    return np.nan

In [304]:
for row in sample_outages_storms.iterrows():
    save_meteorological_info_from_row_point(row)

Saving info at: ../data/raw/meteorological/177512_41007.json
Saving info at: ../data/raw/meteorological/143238_48491.json
Saving info at: ../data/raw/meteorological/133333_39045.json
Saving info at: ../data/raw/meteorological/122191_01123.json
Saving info at: ../data/raw/meteorological/157072_48273.json
Saving info at: ../data/raw/meteorological/164104_06067.json
Saving info at: ../data/raw/meteorological/155446_48005.json
Saving info at: ../data/raw/meteorological/112444_12109.json
Saving info at: ../data/raw/meteorological/97063_24033.json
Saving info at: ../data/raw/meteorological/133253_17197.json
Saving info at: ../data/raw/meteorological/93589_21111.json
Saving info at: ../data/raw/meteorological/148533_39165.json
Saving info at: ../data/raw/meteorological/126901_12021.json
Saving info at: ../data/raw/meteorological/184949_49049.json
Saving info at: ../data/raw/meteorological/164151_06087.json
Saving info at: ../data/raw/meteorological/99116_48005.json
Saving info at: ../data/raw/meteorological/134345_06065.json
Saving info at: ../data/raw/meteorological/134538_06065.json
Saving info at: ../data/raw/meteorological/104264_26107.json
Saving info at: ../data/raw/meteorological/141619_36021.json
Saving info at: ../data/raw/meteorological/174264_48203.json
Saving info at: ../data/raw/meteorological/161858_25013.json
Saving info at: ../data/raw/meteorological/131166_37123.json
Saving info at: ../data/raw/meteorological/156321_48465.json
Saving info at: ../data/raw/meteorological/184921_20155.json
Saving info at: ../data/raw/meteorological/145328_04013.json
Saving info at: ../data/raw/meteorological/150047_34003.json
Saving info at: ../data/raw/meteorological/106024_22019.json
Saving info at: ../data/raw/meteorological/160514_04007.json
Saving info at: ../data/raw/meteorological/114059_50027.json
Saving info at: ../data/raw/meteorological/145819_39049.json
Saving info at: ../data/raw/meteorological/150236_17119.json
Saving info at: ../data/raw/meteorological/177338_47037.json
Saving info at: ../data/raw/meteorological/139445_22079.json
Saving info at: ../data/raw/meteorological/164372_06087.json
Saving info at: ../data/raw/meteorological/146516_54019.json
Saving info at: ../data/raw/meteorological/90230_42017.json
Saving info at: ../data/raw/meteorological/134108_35035.json
Saving info at: ../data/raw/meteorological/163919_55089.json
Saving info at: ../data/raw/meteorological/152382_34017.json
Saving info at: ../data/raw/meteorological/183758_41005.json
Saving info at: ../data/raw/meteorological/127298_04013.json
Saving info at: ../data/raw/meteorological/169728_17105.json
Saving info at: ../data/raw/meteorological/119913_13017.json
Saving info at: ../data/raw/meteorological/121544_42039.json
Saving info at: ../data/raw/meteorological/90725_18003.json
Saving info at: ../data/raw/meteorological/183562_48031.json
Saving info at: ../data/raw/meteorological/152231_06065.json
Saving info at: ../data/raw/meteorological/147122_25017.json
Saving info at: ../data/raw/meteorological/171296_48209.json
Saving info at: ../data/raw/meteorological/174000_04025.json
Saving info at: ../data/raw/meteorological/140393_24033.json
Saving info at: ../data/raw/meteorological/186011_51810.json
Saving info at: ../data/raw/meteorological/155423_51177.json
Saving info at: ../data/raw/meteorological/177791_06023.json
Saving info at: ../data/raw/meteorological/97062_51510.json
Saving info at: ../data/raw/meteorological/168819_48397.json
Saving info at: ../data/raw/meteorological/146665_36027.json
Saving info at: ../data/raw/meteorological/110196_36063.json
Saving info at: ../data/raw/meteorological/155112_48491.json
Saving info at: ../data/raw/meteorological/117231_39049.json
Saving info at: ../data/raw/meteorological/151109_27007.json
Saving info at: ../data/raw/meteorological/112539_13135.json
Saving info at: ../data/raw/meteorological/112506_13067.json
Saving info at: ../data/raw/meteorological/133534_06073.json
Saving info at: ../data/raw/meteorological/145060_45045.json
Saving info at: ../data/raw/meteorological/152460_33013.json
Saving info at: ../data/raw/meteorological/124860_22097.json
Saving info at: ../data/raw/meteorological/108538_24031.json
Saving info at: ../data/raw/meteorological/187437_34029.json
Saving info at: ../data/raw/meteorological/155010_23011.json
Saving info at: ../data/raw/meteorological/118839_37067.json
Saving info at: ../data/raw/meteorological/137253_48021.json
Saving info at: ../data/raw/meteorological/178104_19113.json
Saving info at: ../data/raw/meteorological/123770_48309.json
Saving info at: ../data/raw/meteorological/156087_34013.json
Saving info at: ../data/raw/meteorological/106335_34035.json
Saving info at: ../data/raw/meteorological/156020_40019.json
Saving info at: ../data/raw/meteorological/170371_40051.json
Saving info at: ../data/raw/meteorological/138645_34033.json
Saving info at: ../data/raw/meteorological/167223_35027.json
Saving info at: ../data/raw/meteorological/140919_26125.json
Saving info at: ../data/raw/meteorological/109638_12071.json
Saving info at: ../data/raw/meteorological/180991_13115.json
Saving info at: ../data/raw/meteorological/153709_48117.json
Saving info at: ../data/raw/meteorological/122759_22103.json
Saving info at: ../data/raw/meteorological/140016_55055.json
Saving info at: ../data/raw/meteorological/139112_37119.json
Saving info at: ../data/raw/meteorological/166891_22069.json
Saving info at: ../data/raw/meteorological/142435_42017.json
Saving info at: ../data/raw/meteorological/135202_39061.json
Saving info at: ../data/raw/meteorological/174642_12119.json
Saving info at: ../data/raw/meteorological/150377_24025.json
Saving info at: ../data/raw/meteorological/176783_39015.json
Saving info at: ../data/raw/meteorological/130050_04021.json
Saving info at: ../data/raw/meteorological/146171_23005.json
Saving info at: ../data/raw/meteorological/145656_44007.json
Saving info at: ../data/raw/meteorological/156127_48041.json
Saving info at: ../data/raw/meteorological/151601_36091.json
Saving info at: ../data/raw/meteorological/126331_55079.json
Saving info at: ../data/raw/meteorological/182540_51041.json
Saving info at: ../data/raw/meteorological/154179_48365.json
Saving info at: ../data/raw/meteorological/119913_13019.json
Saving info at: ../data/raw/meteorological/163714_24033.json
Saving info at: ../data/raw/meteorological/178652_48029.json
Saving info at: ../data/raw/meteorological/173037_13067.json
Saving info at: ../data/raw/meteorological/174934_36089.json
Saving info at: ../data/raw/meteorological/127824_20173.json
Saving info at: ../data/raw/meteorological/146748_55075.json
Saving info at: ../data/raw/meteorological/129605_37159.json
Saving info at: ../data/raw/meteorological/124558_36097.json
Saving info at: ../data/raw/meteorological/159177_54019.json
Saving info at: ../data/raw/meteorological/170750_51107.json
Saving info at: ../data/raw/meteorological/184029_51680.json
Saving info at: ../data/raw/meteorological/91777_42039.json
Saving info at: ../data/raw/meteorological/164083_06033.json
Saving info at: ../data/raw/meteorological/109819_42021.json
Saving info at: ../data/raw/meteorological/137909_22017.json
Saving info at: ../data/raw/meteorological/112507_13135.json
Saving info at: ../data/raw/meteorological/157900_48325.json
Saving info at: ../data/raw/meteorological/134806_42119.json
Saving info at: ../data/raw/meteorological/185759_36021.json
Saving info at: ../data/raw/meteorological/185927_48439.json
Saving info at: ../data/raw/meteorological/156321_48029.json
Saving info at: ../data/raw/meteorological/135950_22071.json
Saving info at: ../data/raw/meteorological/145814_48203.json
Saving info at: ../data/raw/meteorological/136741_34037.json
Saving info at: ../data/raw/meteorological/174597_37069.json
Saving info at: ../data/raw/meteorological/171442_42079.json
Saving info at: ../data/raw/meteorological/118416_55101.json
Saving info at: ../data/raw/meteorological/138099_36003.json
Saving info at: ../data/raw/meteorological/154693_12001.json
Saving info at: ../data/raw/meteorological/148818_47055.json
Saving info at: ../data/raw/meteorological/180900_26099.json
Saving info at: ../data/raw/meteorological/157949_53063.json
Saving info at: ../data/raw/meteorological/155293_08005.json
Saving info at: ../data/raw/meteorological/156537_08041.json
Saving info at: ../data/raw/meteorological/127262_18167.json
Saving info at: ../data/raw/meteorological/170371_40119.json
Saving info at: ../data/raw/meteorological/177811_05103.json
Saving info at: ../data/raw/meteorological/152427_25021.json
Saving info at: ../data/raw/meteorological/147485_45013.json
Saving info at: ../data/raw/meteorological/146304_28029.json
Saving info at: ../data/raw/meteorological/135106_48005.json
Saving info at: ../data/raw/meteorological/186653_12001.json
Saving info at: ../data/raw/meteorological/102565_34029.json
Saving info at: ../data/raw/meteorological/115930_22051.json
Saving info at: ../data/raw/meteorological/178679_50025.json
Saving info at: ../data/raw/meteorological/142527_48091.json
Saving info at: ../data/raw/meteorological/142791_12011.json
Saving info at: ../data/raw/meteorological/147349_45045.json
Saving info at: ../data/raw/meteorological/130541_37021.json
Saving info at: ../data/raw/meteorological/174597_37085.json
Saving info at: ../data/raw/meteorological/141828_23009.json
Saving info at: ../data/raw/meteorological/177352_48145.json
Saving info at: ../data/raw/meteorological/171120_12109.json
Saving info at: ../data/raw/meteorological/110178_19013.json
Saving info at: ../data/raw/meteorological/163112_48085.json
Saving info at: ../data/raw/meteorological/146526_22081.json
Saving info at: ../data/raw/meteorological/111194_44007.json
Saving info at: ../data/raw/meteorological/140412_51003.json
Saving info at: ../data/raw/meteorological/132946_51047.json
Saving info at: ../data/raw/meteorological/142735_37191.json
Saving info at: ../data/raw/meteorological/113558_40017.json
Saving info at: ../data/raw/meteorological/158355_42027.json
Saving info at: ../data/raw/meteorological/114706_22001.json
Saving info at: ../data/raw/meteorological/124007_34003.json
Saving info at: ../data/raw/meteorological/110132_12099.json
Saving info at: ../data/raw/meteorological/124422_02020.json
Saving info at: ../data/raw/meteorological/170279_12099.json
Saving info at: ../data/raw/meteorological/170782_51075.json
Saving info at: ../data/raw/meteorological/135654_19081.json
Saving info at: ../data/raw/meteorological/113471_44005.json
Saving info at: ../data/raw/meteorological/151962_06037.json
Saving info at: ../data/raw/meteorological/141656_05143.json
Saving info at: ../data/raw/meteorological/181723_28049.json
Saving info at: ../data/raw/meteorological/172729_48473.json
Saving info at: ../data/raw/meteorological/119604_36119.json
Saving info at: ../data/raw/meteorological/105825_47165.json
Saving info at: ../data/raw/meteorological/154314_36111.json
Saving info at: ../data/raw/meteorological/100907_13139.json
Saving info at: ../data/raw/meteorological/162889_04021.json
Saving info at: ../data/raw/meteorological/132631_39017.json
Saving info at: ../data/raw/meteorological/99672_29113.json
Saving info at: ../data/raw/meteorological/94338_06065.json
Saving info at: ../data/raw/meteorological/120256_48029.json

In [305]:
sample_outages_storms

,EPISODE_ID,fips_code_id,episode_description,storm_start,storm_end,storm_duration,episode_fips_id,storm_caused_outage,outage_index_id,outage_start_minus_storm_start,...,one_day_after_storm,geometry,rep_point,cntroid,boundary_sample_p,sample_p1,sample_p2,sample_p3,url__cntroid,meteorological_info__cntroid
1134,177512,41007,"Combination of snow, sleet and freezing rain.",2022-12-22 16:00:00,2022-12-24 13:30:00,45.500000,177512_41007,1.0,41007__0028,1.104167,...,2022-12-25,"POLYGON ((-124.01136 46.23622, -124.002 46.237...",POINT (-123.64603 46.02537),POINT (-123.65572 45.99514),"MULTIPOINT (-123.99276 45.94733, -123.98143 46...",POINT (-123.61519 46.16772),POINT (-123.80363 45.82972),POINT (-123.45997 46.25325),https://power.larc.nasa.gov/api/temporal/hourl...,"{'type': 'Feature', 'geometry': {'type': 'Poin..."
1297,143238,48491,Nearly all of South Central Texas had less tha...,2019-10-01 00:00:00,2019-10-31 23:59:00,743.983333,143238_48491,1.0,48491__0043,24.010417,...,2019-11-01,"POLYGON ((-98.04989 30.62416, -97.998 30.72021...",POINT (-97.63453 30.66086),POINT (-97.60028 30.64775),"MULTIPOINT (-97.92403 30.60898, -97.86906 30.5...",POINT (-97.27337 30.62153),POINT (-97.32981 30.50738),POINT (-97.72788 30.59015),https://power.larc.nasa.gov/api/temporal/hourl...,"{'type': 'Feature', 'geometry': {'type': 'Poin..."
1298,133333,39045,Several waves of low pressure moved along a st...,2019-02-06 11:48:00,2019-02-08 01:40:00,37.866667,133333_39045,1.0,39045__0026,1.497917,...,2019-02-09,"POLYGON ((-82.83646 39.62786, -82.83549 39.637...",POINT (-82.61561 39.75553),POINT (-82.63066 39.75161),"MULTIPOINT (-82.83847 39.60729, -82.83312 39.6...",POINT (-82.54017 39.63577),POINT (-82.64963 39.88632),POINT (-82.61747 39.70291),https://power.larc.nasa.gov/api/temporal/hourl...,"{'type': 'Feature', 'geometry': {'type': 'Poin..."
1323,122191,01123,A significant snowstorm impacted central Alaba...,2017-12-08 06:00:00,2017-12-09 05:00:00,23.000000,122191_01123,1.0,01123__0000,1.281250,...,2017-12-10,"POLYGON ((-86.00917 33.09026, -85.97456 33.090...",POINT (-85.7985 32.79904),POINT (-85.79737 32.86253),"MULTIPOINT (-86.00765 32.84728, -86.00273 32.8...",POINT (-85.74843 32.91815),POINT (-85.62518 32.82237),POINT (-85.90016 32.8075),https://power.larc.nasa.gov/api/temporal/hourl...,"{'type': 'Feature', 'geometry': {'type': 'Poin..."
1324,140999,55131,Persistent southwest winds and the passage of ...,2019-07-19 09:00:00,2019-07-20 14:20:00,29.333333,140999_55131,1.0,55131__0012,1.385417,...,2019-07-21,"POLYGON ((-88.41871 43.32544, -88.41856 43.365...",POINT (-88.22326 43.36869),POINT (-88.2306 43.36852),"MULTIPOINT (-88.41858 43.23706, -88.40971 43.1...",POINT (-88.18444 43.53001),POINT (-88.22479 43.37107),POINT (-88.34135 43.41851),https://power.larc.nasa.gov/api/temporal/hourl...,{'message': 'Internal server error'}
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1685,162889,04021,A shortwave trough rotating through the region...,2021-08-16 22:20:00,2021-08-17 09:00:00,10.666667,162889_04021,1.0,04021__0023,0.309028,...,2021-08-18,"POLYGON ((-112.20359 32.63781, -112.20352 32.8...",POINT (-111.32618 32.91065),POINT (-111.34481 32.90444),"MULTIPOINT (-112.19055 33.26471, -112.03076 33...",POINT (-111.88107 32.64663),POINT (-111.93212 32.94542),POINT (-111.88854 32.9753),https://power.larc.nasa.gov/api/temporal/hourl...,"{'type': 'Feature', 'geometry': {'type': 'Poin..."
1686,132631,39017,An upper level low pressure center tracked nor...,2018-11-14 23:00:00,2018-11-15 12:00:00,13.000000,132631_39017,1.0,39017__0043,0.406250,...,2018-11-16,"POLYGON ((-84.81935 39.30945, -84.81745 39.391...",POINT (-84.57696 39.44808),POINT (-84.57555 39.43865),"MULTIPOINT (-84.81544 39.51715, -84.81214 39.5...",POINT (-84.45194 39.41688),POINT (-84.44585 39.40869),POINT (-84.36739 39.39598),https://power.larc.nasa.gov/api/temporal/hourl...,"{'type': 'Feature', 'geometry': {'type': 'Poin..."
1687,99672,29113,A frontal boundary was slowly sinking south ac...,2015-06-25 17:25:00,2015-06-26 14:55:00,21.500000,99672_29113,1.0,29113__0000,0.305556,...,2015-06-27,"POLYGON ((-91.26311 39.037, -91.26023 39.13984...",POINT (-90.98767 39.05039),POINT (-90.95986 39.05802),"MULTIPOINT (-91.18894 38.95796, -91.17062 38.9...",POINT (-91.08214 38.89591),POINT (-90.90682 39.18039),POINT (-91.02052 38.92007),https://power.larc.nasa.gov/api/temporal/hourl...,"{'type': 'Feature', 'geometry': {'type': 'Poin..."
1688,94338,06065,An upper-level trough deepened along the West ...,2015-03-01 00:00:00,2015-03-02 12:20:00,36.333333,94338_06065,1.0,06065__0015,0.250000,...,2015-03-03,"POLYGON ((-117.67548 33.88812, -117.65488 33.8...",POINT (-116.02033 33.75369),POINT (-115.99477 33.74377),"MULTIPOINT (-117.44133 33.50502, -117.18768 33...",POINT (-117.2192 33.77591),POINT (-114.52887 33.79433),POINT (-115.81691 33.67794),https://power.larc.nasa.gov/api/temporal/hourl...,"{'type': 'Feature', 'geometry': {'type': 'Poin..."
1689,120256,48029,A line of thunderstorms formed ahead of a cold...,2017-08-07 01:47:00,2017-08-07 13:15:00,11.466667,120256_48029,1.0,48029__0072,0.425694,...,2017-08-08,"POLYGON ((-98.80655 29.69071, -98.77878 29.720...",POINT (-98.47099 29.43958),POINT (-98.51978 29.449),"MULTIPOINT (-98.8061 29.64888, -98.80477 29.26...",POINT (-98.51077 29.34134),POINT (-98.48982 29.51846),POINT (-98.59949 29.74299),https://power.larc.nasa.gov/api/temporal/hourl...,"{'type': 'Feature', 'geometry': {'type': 'Poin..."